feat(partition): flame and icicle performance and tweening
elastic/elastic-charts pull request #1041
Opened 2021-03-02 15:04 UTC by monfera

## Summary

- increases performance on all partition charts that don't `showLegend` by not computing it
- adds optional (default: none) tween with configurable duration to the icicle/flame chart when using clipping
- increases drilldown performance by deferring the reprojection (zoom/pan) and elimination of invisible boxes, using focus information in the renderer, a WebGL-compatible approach, therefore avoiding the need to recompute the viewmodel proper
- as the drilldown logic is different, the recently added `groupByRollup` and `tree.ts` additions for drilldown became unnecessary, they got removed
- optimizes the clipped text render path for icicle/flame for speed, by adding a specialized render function with reduced API and function call count, and by avoiding multirow text fill calculation in `viewmodel.ts`
- caches calls to time consuming `chroma` functions for a 2-3 OOM reduction of `chroma` calls
- moves commonly used functions eg. fill coloring out of `partition-chart`
- removes some `let` and conditionalization from the color logic

https://user-images.githubusercontent.com/1548516/109667342-5787c000-7b70-11eb-9dc6-a5a9354bd184.mp4

### Checklist

Delete any items that are not applicable to this PR.

- [X] This was checked for cross-browser compatibility
- [X] Proper documentation or storybook story was added for features that require explanation or tutorials
- [X] Unit tests were updated or added to match the most common scenarios

2021-03-02 15:31 UTC, monfera commented on src/chart_types/partition_chart/layout/viewmodel/viewmodel.ts
> +  const pickQuads: PickFunction = (x, y, { currentFocusX0, currentFocusX1 }) => {
I'll conditionalize it outside the loop, ie. `const pickQuads = sunburstLayout ? ... : ...`

2021-03-04 20:08 UTC, markov00 requested changes
I don't know exactly what happen but the drilldown no longer works in the flame chart and icicle chart examples in storybook. The drilldown is configured but didn't change the chart rendering:  ` drilldown: true` 
Seems that the svg highlighter get the drilldown, but not the canvas renderer

2021-03-04 20:47 UTC, monfera commented on src/chart_types/partition_chart/renderer/canvas/canvas_linear_renderers.ts
> +let latestRaf: number;
Thanks, will do!

2021-03-04 20:55 UTC, monfera commented on src/chart_types/partition_chart/renderer/canvas/partition.tsx
> +  geometriesFoci: [],
just checked, `focuses` as plural is legit too, if you have some preference for the latter, glad to switch

2021-03-05 10:25 UTC, monfera commented
Thanks for the catch @markov00 I added cc273f5d7caa2b5119764b3431db76715be9e842 to prevent drilldown on non-cropping versions

2021-03-05 10:26 UTC, monfera commented on src/chart_types/partition_chart/renderer/canvas/canvas_linear_renderers.ts
> +let latestRaf: number;
Done in ca4e1156f26d2ed03e0359cfb2edbe246c92e320

2021-03-05 10:48 UTC, markov00 commented on src/chart_types/partition_chart/renderer/canvas/canvas_linear_renderers.ts
> +let latestRaf: number;
Thank you

2021-03-05 10:50 UTC, markov00 approved these changes
Tested locally, LGTM

2021-03-05 10:54 UTC, merged

2021-03-09 22:15 UTC, nickofthyme commented
:tada: This PR is included in version 25.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v25.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/25.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: