fix: chromium area path render bug
elastic/elastic-charts pull request #1067
Opened 2021-03-09 19:03 UTC by nickofthyme

## Summary

fixes #1053 

There is an issue with chromium where the area line can be _pinched_ causing the filled area to _not_ be rendered.

### Before
![Image 2021-03-09 at 12 41 50 PM](https://user-images.githubusercontent.com/19007109/110523211-6a057a80-80d7-11eb-835a-a79764200062.jpg)

### After
![Image 2021-03-09 at 12 42 54 PM](https://user-images.githubusercontent.com/19007109/110523226-6d990180-80d7-11eb-9a6c-d1106b7c984d.jpg)

The temporary fix is to add a small imperceptible pixel value to the scaled `y1` value when it's equal to the `y0` value.

Additionally, this PR adds rounding to the scaled values to avoid unnecessarily precise scaled values in the path strings.

### Checklist

- [x] This was checked for cross-browser compatibility
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios

2021-03-09 19:10 UTC, monfera commented
neat bug, can you pls. link the chromium issue? If you ran into it and triaged yourself, and there are no obvious finds in https://bugs.chromium.org/p/chromium/issues/list maybe it's worth adding an issue for this, eg. with a super minimal codepen repro

2021-03-09 19:27 UTC, nickofthyme commented
Yup will do @monfera thanks for the link.

2021-03-09 21:25 UTC, nickofthyme commented
causes a bunch of very small pixel changes in vrt

2021-03-10 09:37 UTC, monfera requested changes
Asking for a change of logic, so we check for the actual Chrome bug trigger condition, which is likely some pixel (or pixel in relation to shape/chart width) threshold, and is not safely inferrable from what the domain datum is, before we map it to pixel values (eg. a scale can diminish or magnify differences). Also, the error is not just triggered if the pixel difference is zero; a too small difference triggers it too.

The decimal truncation of the X pixels feels unrelated to the fix, worth separating, for the case when Google fixes the error, easier to make the reverse PR, maybe just a git revert.

2021-03-10 10:37 UTC, markov00 commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return ({ x }) => roundScaledValue(xScale.scaleOrThrow(x) - xScaleOffset);
> why are we adjusting with xScaleOffset with this subtraction, rather than setting up the scale to do this for us?
This is for historical reasons, we should change that after refactoring how our scales works

2021-03-10 10:39 UTC, markov00 commented on src/chart_types/xy_chart/rendering/utils.ts
> +    return roundScaledValue(yScale.scaleOrThrow(yValue)) + extra;
I think we tested with Nick the rounding, but not sure if this now needed if we add an extra sub-pixel.

2021-03-10 20:39 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return y0 === y1 ? SMALL_PIXEL : 0;
Yeah, I thought about doing it based on the px value but it seemed to be unnecessary to execute the `y0` scale value twice, once for `y0` and now again for `y1`. But I think you are right, this is a safer option.

Fixed here e9364c5

2021-03-10 20:40 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +    const extra = chromeRenderBugBuffer(datum);
yup, see e9364c5 and https://github.com/elastic/elastic-charts/pull/1067#discussion_r591855028

2021-03-10 20:41 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return ({ x }) => roundScaledValue(xScale.scaleOrThrow(x) - xScaleOffset);
You are right @monfera the rounding should be in a different PR and is likely the cause of the vrt diffs too.

See fa6b018

2021-03-10 20:43 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +    roundScaledValue(
Reverted here fa6b018.

2021-03-10 20:44 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +    return roundScaledValue(yScale.scaleOrThrow(yValue)) + extra;
Yeah the rounding has nothing to do with the bug nor the fix. Moving to different PR.

2021-03-10 21:28 UTC, monfera commented on src/chart_types/xy_chart/rendering/utils.ts
> +    const extra = chromeRenderBugBuffer(datum);
Thanks Nick! I suppose, the points are computed consecutively in the series, so if there were a speed concern, we could refer back to the previously encountered Y value. Though it'd be a much bigger change to the code, and hopefully Google fixes it soon, so your choice looks good. Not worth a bigger refactoring.

2021-03-10 21:29 UTC, monfera commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return ({ x }) => roundScaledValue(xScale.scaleOrThrow(x) - xScaleOffset);
Nice! All images gone indeed

2021-03-10 21:31 UTC, monfera commented on src/chart_types/xy_chart/rendering/utils.ts
> +    roundScaledValue(
Thanks! I'll run a couple of more tests in the morning unless it's super urgent, and there's some CI failures too

2021-03-10 21:33 UTC, nickofthyme commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return ({ x }) => roundScaledValue(xScale.scaleOrThrow(x) - xScaleOffset);
New PR is here https://github.com/elastic/elastic-charts/pull/1072

We can pick up this discussion there.

2021-03-11 12:03 UTC, monfera requested changes
Thanks for the changes, all of them look good 👍 

One more find: these mocks lost their zero lines due to the shift. Worth jittering in the other direction, it's less likely to happen on the top (would be good to check though, there are already test cases which have a straight line on the top, from the time Cartesians clipped the topmost points and lines in half, which got fixed ~2yrs ago - but they may not trigger the new offset logic)

![image](https://user-images.githubusercontent.com/1548516/110783142-54738a80-8268-11eb-8a8b-95b4aa1d36d3.png)

![image](https://user-images.githubusercontent.com/1548516/110783497-d499f000-8268-11eb-8758-f7c189989df6.png)

and the next ~8 files. There's also impact somewhere else, a thicker line on the floor got thinned, same reason

2021-03-11 23:37 UTC, nickofthyme commented
Good catch @monfera. I thought the reference point was the other way. Flipped the add to subtract. (aka ➕ ➡️ ➖)

2021-03-15 21:57 UTC, monfera approved these changes
Looks good to me, thanks! I sampled several dozen images via the slider, around 20% of all, and scan-compared the rest. I think it's OK due to the type of change, previous reviews and the fact that so many of them are very very similar (looking at you, percentage based area charts).

I didn't see any showstopper in this PR. The `0.5` values and the mentioned constants could perhaps be DRYed up in this PR or a follow-up one.

There are a couple of places when the appearance of multiple zero-prone lines changed, though one is not superior to the other, eg.: `integration/tests/__image_snapshots__/line-stories-test-ts-line-series-stories-line-paths-for-ordered-values-should-render-correct-line-path-stacked-1-snap.png`

:tada: Also, the small upward shift visually fixes the frequent case of 1px width zero-prone lines, which used to be chopped in half, eg. more seamless, uniform thickness line here:

![image](https://user-images.githubusercontent.com/1548516/111225798-85451e00-85e0-11eb-8d3b-72912004c08d.png)

2021-03-15 21:57 UTC, monfera commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +const CLIPPING_MARGINS = 0.5;
Can/should it be shared with `CHROME_PINCH_BUG_EPSILON` or be one defined by the other?

2021-03-15 21:57 UTC, monfera commented on src/chart_types/xy_chart/rendering/utils.ts
> +  return diff <= CHROME_PINCH_BUG_EPSILON ? 0.5 : 0;
Minor: wondering if the `0.5` here should be extracted into a constant

2021-03-15 21:57 UTC, monfera commented on src/renderers/canvas/index.ts
> +        context.rect(0, -0.5, clippedRanges[0][0], height);
Same here, maybe worth linking these `0.5`s to a common constant

2021-03-15 22:04 UTC, monfera commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +const CLIPPING_MARGINS = 0.5;
... on a 2nd thought, it feels like, two constants altogether would suffice:
- `CHROME_PINCH_BUG_EPSILON` (for testing, as you already do
- `CHROME_PINCH_BUG_WORKAROUND_OFFSET` (for offsetting)
and maybe not worth making one depend on the other, though it'd be nice if they were right next to one another, with the comment about the chromium bug link and short explanation atop of it. Still in the nit category, just lets us centralize the workaround and its eventual hopeful reversal of this bad bug

2021-03-15 23:19 UTC, nickofthyme commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +const CLIPPING_MARGINS = 0.5;
@monfera I think the idea here is to be generic to expand this later to prevent clipping of lines, points, areas, etc outside of the clipped range. In this case it should be the value of `SMALL_PIXEL` so maybe something like this would suffice.

```suggestion
const CLIPPING_MARGINS = SMALL_PIXEL;
```

But for the purposes of backporting this, I think this can wait for another time.

2021-03-15 23:22 UTC, nickofthyme reviewed
LGTM after seemingly millions of screenshot reviews 😭

2021-03-16 00:29 UTC, merged

2021-03-23 14:40 UTC, nickofthyme commented
:tada: This PR is included in version 25.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v25.4.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/25.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-12-13 19:33 UTC, nickofthyme commented
This bug appears to have been fixed and we can not revert this workaround. See https://bugs.chromium.org/p/chromium/issues/detail?id=1163912#c6