feat(a11y): improve chart figure
elastic/elastic-charts pull request #1104
Opened 2021-04-01 17:00 UTC by rshen91

## Summary
Closes #1099 

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-04-02 14:08 UTC, rshen91 commented
jenkins test this please

2021-04-05 22:37 UTC, nickofthyme approved these changes
Overall, LGTM. I just left a few comments.

2021-04-05 22:37 UTC, nickofthyme commented on integration/tests/accessibility.test.ts
> +describe('Accessibility tree', () => {
😍

2021-04-05 22:37 UTC, nickofthyme commented on src/chart_types/xy_chart/renderer/dom/_screen_reader.scss
> +  height: 1px;
Does this need to be visible to work with the screen reader? we could add `pointer-events: none` and `visibility: hidden`?

```suggestion
  position: absolute;
  pointer-events: none;
  visibility: hidden;
  width: 1px;
  height: 1px;
```

2021-04-05 22:37 UTC, nickofthyme commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +                })}
simplified...

```suggestion
                {seriesTypes.map((value, index) => <dd key={`${index}`}>{value}</dd>)}
```

2021-04-06 09:12 UTC, markov00 requested changes
Despite the fact that I like the approach taken, I think we should follow what was suggested in the original issue first.
`I'd recommend tackling this after #1096, #1097, and #1098 otherwise it's too much structure for too little info`

2021-04-06 09:12 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +      </figure>
few words here:
- the `dl` tag represents a `description list` where we should include subsequent pairs of `dt` (description term) and `dd` (description details). https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl 
Having a `term` with no `details` looks like semantically wrong to me. and instead of having `<dt>No series in chart</dt>` we can also remove the `dl` completely if we don't provide more info. I'm also pretty sure that if we don't have series in chart, the chart is not rendered and we have a "no data available" text instead.
- the screen readers are not very smart and a text like `Chart type(s)` is probably read as `chart type open parentesis s closed parentesis`. As we know how many chart types we can be smarter and have something like.
```html
<dt>Chart type</dt>
<dd>Bar chart</dt>
```
or, when we have multiple types:
```html
<dt>Chart type</dt>
<dd>Mixed chart: bar and line chart</dd>
```

2021-04-06 16:16 UTC, myasonik commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    });
How would you recommend getting this data if not using the object keys?

On the i18n front, I don't think it's fair to expect a PR that improves a11y to  also solve Charts' i18n in one fell swoop. Without an existing i18n solution in place (correct me if I'm wrong as I'm only loosely familiar with the codebase), building with a hypothetical solution in mind brings a lot of overhead with little gain imo.

2021-04-06 16:22 UTC, myasonik commented on src/chart_types/xy_chart/renderer/dom/_screen_reader.scss
> +  height: 1px;
Hiding stuff has historically been fraught with bugs so it's best avoided at the time being. 

This almost matches [EUI's screen reader only mixin](https://github.com/elastic/eui/blob/master/src/global_styling/mixins/_helpers.scss#L90-L97) which has been battle tested for a while now.

The only thing that EUI has that this is missing is `overflow: hidden;` which I'd recommend adding to clip the text off from the 1px by 1px box we're shoving it into.

2021-04-06 16:34 UTC, myasonik commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +      </figure>
**RE: DL semantics**
Having a term with no details _is_ allowed but, I agree, it _is_ weird... (It also has some weird fall-through rules if there is a definition later...) 

If the chart isn't rendered with no data then I guess we don't need it anyways.

**RE: Chart types(s)**
By default, most screen readers actually ignore punctuation and communicate much of it by intonation or specific tones. But generally we shouldn't worry about how a specific screen reader is going to read something, because, however it does it, it is ultimately expected by the user. We don't need to try to preempt a user's assistive tech with our own assumptions. 

That said, I do like your adjusted phrasing though. 😄 It's more definitive and flows a little nicer.

2021-04-06 21:52 UTC, myasonik commented
> Despite the fact that I like the approach taken, I think we should follow what was suggested in the original issue first.
> > I'd recommend tackling this after #1096, #1097, and #1098 otherwise it's too much structure for too little info

@markov00 I know I wrote that ☝️ but this PR still does improve the state of charts a11y so I'd rather merge it (when it's green) and do the issues in a different order than have to sit on this PR while it rots.

It does actually mean less work in the long run imo because this PR changes the DOM structure somewhat and the other work can be built directly into this new structure instead of needing to refactor it after the fact.

**TL;DR** The new structure is arguably a little overkill... But that's better than the vast gap we have now...

2021-04-06 22:20 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +      </figure>
Please see e7d1230 - thank you!

2021-04-06 22:20 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          aria-label="Chart"
Please see e7d1230 thanks!

2021-04-06 22:20 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    });
Refactored in e7d1230 thank you!

2021-04-06 22:20 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/dom/_screen_reader.scss
> +.screen-reader {
good call thank you - fixed in e7d1230

2021-04-06 22:20 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +                })}
thank you fixed in e7d1230

2021-04-06 22:21 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/dom/_screen_reader.scss
> +  height: 1px;
Thank you - please see e7d1230

2021-04-06 22:28 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          aria-label="Chart"
In e7d1230 I ended up removing the aria-label because it's not read by VoiceOver and this PR adds more information. I was leaning towards not having the aria-label since it's not providing more information on the `<dl>` tags.

2021-04-07 09:47 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    });
> How would you recommend getting this data if not using the object keys?

I'm referring to the fact that we are extracting the chart type "strings" from an object `geometries` that is an internal object which structure can change in the future easily. 

This refactoring increase also the current issue: if the `geometries` object change its signature, the `getNameFunction` can just return `unkown chart` for each chart type without being warned.

```
Object.entries(geometries).forEach((value) => {
      if (value[1].length > 0 && value[0]) {
        seriesTypes.push(getNameFunction(value[0]));
      }
    });
....
export const getNameFunction = (key: string): string => {
  const screenReader: Map<string, string> = new Map();
  screenReader
    .set('bars', 'Bar chart')
    .set('areas', 'Area chart')
    .set('lines', 'Line chart')
    .set('bubbles', 'Bubble chart');
  return screenReader.get(key) ?? 'unknown chart';
};
```

The concept of chart type is already built into each `spec`, the react component that specifies the chart configuration. I'm saying that. instead of taking the chart type information from an internal object, like `geometris`, we should create that information from the actual specs using an already well-known and exposed enum called `SeriesType`.

A selector that picks the actual series types and creates a Set of unique `SeriesType`s is cleaner and we can map the well-known `SeriesType` enum values to a set of internationalized strings.

2021-04-07 21:12 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    });
Ok thanks please see 9e036d3

2021-04-07 21:12 UTC, rshen91 commented
jenkins test this please

2021-04-07 21:19 UTC, rshen91 commented
jenkins test this please

2021-04-08 19:07 UTC, myasonik approved these changes
🚀

2021-04-12 09:42 UTC, markov00 approved these changes
Looks good to me, I've added few minor comments

2021-04-12 14:16 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    seriesTypes.forEach((value) => multipleSeriesTypes.push(value));
Thank you! 9b11e85

2021-04-12 14:16 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +            <dt> Chart type </dt>
Thank you! 9b11e85

2021-04-12 14:16 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/dom/_screen_reader.scss
> +.echScreen-reader {
Good call - 9b11e85

2021-04-12 15:20 UTC, rshen91 commented
Jenkins, test this please

2021-04-12 15:48 UTC, merged

2021-04-13 14:28 UTC, nickofthyme commented
:tada: This PR is included in version 28.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v28.1.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/28.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: