feat(a11y): add alt text for all chart types
elastic/elastic-charts pull request #1118
Opened 2021-04-13 19:40 UTC by rshen91

## Summary
Fixes https://github.com/elastic/elastic-charts/issues/1107

If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-04-29 16:20 UTC, nickofthyme commented on src/components/accessibility/types.tsx
> +  if (!props.defaultSummaryId) return null;
The prop type and the component names should match

2021-04-29 16:22 UTC, nickofthyme commented on src/components/accessibility/screen_reader_summary.tsx
> +      <Types {...a11ySettings} chartSeriesTypes={seriesTypes} />
Just my opinion here but I think these components should be more specific because `Label` is very general. Maybe like `ScreenReaderLabel` or something.

2021-04-29 16:23 UTC, nickofthyme commented on src/components/accessibility/types.tsx
> +  chartSeriesTypes: string;
I think if this component name is more specific the prop name doesn't need to be this specific. Something like `chartTypeDescription`.

2021-04-29 16:25 UTC, nickofthyme commented on src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +  seriesTypes: string;
I really don't like this variable name because it is not an array of series types as one would think. This is more like a chart type description or something similar. Same goes for `chartSeriesTypes`

2021-04-29 16:48 UTC, markov00 reviewed
Looks good, I have added few comments, in particular you should remove all props from `          <ScreenReaderSummary />` as all the required props are injected by redux.

2021-04-29 16:48 UTC, markov00 commented on src/components/accessibility/types.tsx
> +      <dd id={props.defaultSummaryId}>{props.chartSeriesTypes}</dd>
Why are you adding two times the same ID? That's not allowed.
This was the previous code:
```tsx
{a11ySettings.defaultSummaryId && (
  <dl id={a11ySettings.defaultSummaryId}>
    <dt>Chart type</dt>
    <dd>{chartSeriesTypes}</dd>
    </dl>
)}
```

2021-04-29 16:48 UTC, markov00 commented on src/components/accessibility/screen_reader_summary.tsx
> +export const ScreenReaderSummary = memo(connect(mapStateToProps)(ScreenReaderSummaryComponent));
not sure we need `memo` here, @nickofthyme ?

2021-04-29 16:48 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          <ScreenReaderSummary a11ySettings={a11ySettings} seriesTypes={seriesTypes} />
`<ScreenReaderSummary>` is already connected to redux store, so you don't have to pass any props

2021-04-29 16:48 UTC, markov00 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
I think we should reuse the way we are doing that in the other charts with the `figure` + the ScreenReaderSummary

2021-04-29 16:48 UTC, markov00 commented on src/chart_types/partition_chart/state/selectors/get_series_types.ts
> +  return `${partitionSpec?.chartType} chart` ?? 'Partition chart';
In this case we should be return the `particionSpec.config.partitionLayout` instead, that provides the exact chart type we are using

2021-04-29 17:31 UTC, rshen91 commented on src/components/accessibility/types.tsx
> +      <dd id={props.defaultSummaryId}>{props.chartSeriesTypes}</dd>
Sorry for the confusion adding this due to https://github.com/elastic/elastic-charts/pull/1121#discussion_r618524462

2021-04-29 17:38 UTC, nickofthyme commented on src/components/accessibility/screen_reader_summary.tsx
> +export const ScreenReaderSummary = memo(connect(mapStateToProps)(ScreenReaderSummaryComponent));
I don't think it's doing a whole lot but this is basically like using `PureComponent` which does a _shallow prop and state comparison_. I tend to just use them by default when creating a class `Component`.

2021-04-29 19:03 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          <ScreenReaderSummary a11ySettings={a11ySettings} seriesTypes={seriesTypes} />
Thank you!! ea91feb

2021-04-29 19:03 UTC, rshen91 commented on src/components/accessibility/types.tsx
> +  chartSeriesTypes: string;
Thank you! ea91feb

2021-04-29 19:04 UTC, rshen91 commented on src/components/accessibility/screen_reader_summary.tsx
> +      <Types {...a11ySettings} chartSeriesTypes={seriesTypes} />
Thank you!! ea91feb

2021-04-29 19:04 UTC, rshen91 commented on src/components/accessibility/types.tsx
> +  if (!props.defaultSummaryId) return null;
Good point 😅 ea91feb

2021-04-29 19:41 UTC, myasonik commented on src/components/accessibility/types.tsx
> +      <dd id={props.defaultSummaryId}>{props.chartSeriesTypes}</dd>
The `id` needs to only be on the `<dd>` because this text is being used in an `aria-describedby` which does not understand structured content (e.g., the markup within a `<dl>` so it needs to a point to a simple string).

```
{a11ySettings.defaultSummaryId && (
  <dl>
    <dt>Chart type</dt>
    <dd id={a11ySettings.defaultSummaryId}>{chartSeriesTypes}</dd>
    </dl>
)}


```

2021-04-30 10:57 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          <ScreenReaderSummary a11ySettings={a11ySettings} seriesTypes={seriesTypes} />
Good, but you there are some injected properties not used now, like seriesTypes. If a component doesn't use those, let's not add them to the mapStateToProps

2021-04-30 22:53 UTC, rshen91 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
Ok I wasnt sure because of the svg nature of it https://www.deque.com/blog/creating-accessible-svgs/

2021-05-03 13:30 UTC, rshen91 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
Please see 93a93a1 thanks

2021-05-03 14:26 UTC, rshen91 commented on src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +  seriesTypes: string;
Ok sweet I think I found them all and have changed in this commit e967711

2021-05-03 14:30 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          <ScreenReaderSummary a11ySettings={a11ySettings} seriesTypes={seriesTypes} />
🤯 fa3ddcd thank you

2021-05-03 15:56 UTC, nickofthyme approved these changes

2021-05-06 20:38 UTC, myasonik approved these changes

2021-05-06 20:38 UTC, myasonik commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +const uniqeWordCloudId = `test--description`;
`test--description`? Was this supposed to be temporary or should this be passed into `a11ySettings` somehow?

2021-05-06 20:38 UTC, myasonik commented on src/components/accessibility/types.tsx
> +    <dl id={props.defaultSummaryId}>
```suggestion
    <dl>
```

The `id` is used below.

2021-05-10 13:26 UTC, rshen91 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +const uniqeWordCloudId = `test--description`;
Good catch - since word cloud doesn't have a chart ID the same way as the cartesian charts I'm pulling the id from the default a11y settings `id={`${DEFAULT_A11Y_SETTINGS.descriptionId}--description`}>` 843b955

2021-05-10 18:01 UTC, nickofthyme commented on src/components/accessibility/types.tsx
> +      <dd id={props.defaultSummaryId}>{props.chartSeriesTypes}</dd>
@rshen91 is the resolved? Can you add the commit.

2021-05-12 16:03 UTC, markov00 requested changes
Few missing things that needs to be fixed

2021-05-12 16:03 UTC, markov00 commented on src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +    seriesTypes: 'heatmap chart',
this prop doesn't seems to be used anywhere in the code, let's remove it from the `ReactiveChartStateProps`

2021-05-12 16:03 UTC, markov00 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
We should use the same `ScreenReaderSummary` componenent used elsewhere to avoid duplicate code.

2021-05-12 16:04 UTC, markov00 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
and anyway we can't use an id like this `id={`${DEFAULT_A11Y_SETTINGS.descriptionId}--description`}` because it can conflicts with other world cloud charts

2021-05-13 16:29 UTC, rshen91 commented on src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +    seriesTypes: 'heatmap chart',
Sorry I missed this yesterday - please see e9c5255

2021-05-13 16:29 UTC, rshen91 commented on src/chart_types/wordcloud/renderer/svg/connected_component.tsx
> +    </title>
Please see: e9c5255 Thank you

2021-05-14 14:06 UTC, markov00 approved these changes
LGTM, I've pushed a slight change on the wordcloud to move the ScreenReaderSummary out of the SVG and changed the `svg` `role` to `presentation` as done in the other canvases

2021-05-14 16:33 UTC, merged

2021-05-25 17:50 UTC, nickofthyme commented
:tada: This PR is included in version 29.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v29.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/29.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: