feat(legend): disable handleLabelClick for one legend item
elastic/elastic-charts pull request #1134
Opened 2021-04-22 20:39 UTC by rshen91

## Summary

Summarize your PR.

If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-04-22 22:29 UTC, nickofthyme requested changes
Looks like the `ItemLabel` is still toggleable. We need to update that in addition to the click handler.

![Screen Recording 2021-04-22 at 05 27 27 PM](https://user-images.githubusercontent.com/19007109/115792613-341f0b80-a390-11eb-9caf-55f7f36dc958.gif)

2021-04-23 14:20 UTC, rshen91 commented
> Looks like the `ItemLabel` is still toggleable. We need to update that in addition to the click handler.
> 
> ![Screen Recording 2021-04-22 at 05 27 27 PM](https://user-images.githubusercontent.com/19007109/115792613-341f0b80-a390-11eb-9caf-55f7f36dc958.gif)

ah good catch - please see a34bf4a thank you!

2021-04-23 14:47 UTC, nickofthyme commented on src/components/legend/legend_item.tsx
> +    }
Why is this logic here and not in the condition for the `isToggleable` prop?

2021-04-23 15:30 UTC, rshen91 commented on src/components/legend/legend_item.tsx
> +    }
Oh man so I thought this was in master but it isn't so I removed it in 8e57477. Also changed the accessibility integration tests to test the HTML since the accessibility tree functionality in puppetteer is spotty and unreliable. I think we might be moving to playwright eventually so I'm just loading the HTML for now.

2021-04-23 15:49 UTC, nickofthyme commented on src/components/legend/legend_item.tsx
> +    }
Is the spotty accessibility tree logic failing just this PR? If not I would say move that to another PR.

So to be clear the `legendItemId.length` had no impact on the toggle ability of the legend items, correct?

2021-04-23 15:50 UTC, nickofthyme commented on src/components/legend/legend_item.tsx
> +            isToggleable={totalItems > 1 ? item.isToggleable : false}
```suggestion
            isToggleable={totalItems > 1 && item.isToggleable}
```

2021-04-23 16:17 UTC, rshen91 commented on src/components/legend/legend_item.tsx
> +            isToggleable={totalItems > 1 ? item.isToggleable : false}
Much cleaner! 586adbf

2021-04-23 16:23 UTC, nickofthyme commented on src/chart_types/xy_chart/state/chart_state.accessibility.test.ts
> +    expect(ariaUseDefaultSummary).toBeTruthy();
Isn't this a `boolean` why the looser assertion?

2021-04-23 17:33 UTC, rshen91 commented on src/chart_types/xy_chart/state/chart_state.accessibility.test.ts
> +    expect(ariaUseDefaultSummary).toBeTruthy();
🤔 I'm facing this error in my IDE `any Property 'toBeTrue' does not exist on type 'JestMatchers<boolean>'.ts(2339)`

2021-04-23 17:42 UTC, nickofthyme commented on src/components/legend/legend_item.tsx
>        return;
Let's merge these branches

2021-04-23 18:32 UTC, nickofthyme commented on src/chart_types/xy_chart/state/chart_state.accessibility.test.ts
> +    expect(ariaUseDefaultSummary).toBeTruthy();
UGH!! 🙄 

This should fix that https://github.com/elastic/elastic-charts/pull/1136. It's a vscode thing not a type issue. You should be able to revert this and just save the file ignoring the error. Test it by running...

```
yarn typecheck:all
```

2021-04-23 19:57 UTC, rshen91 commented on src/components/legend/legend_item.tsx
>        return;
Thank you - please see 2da6e3d

2021-04-23 21:08 UTC, rshen91 commented on src/components/legend/legend_item.tsx
> +    }
Yep! Ok I can open a separate PR for the accessibility tree logic failing. 👍🏻 And the legendItemId.length should not impact the toggle ability of the legend items.

2021-04-23 21:25 UTC, rshen91 commented on src/components/legend/legend_item.tsx
> +    }
removed test changes in 390c73d and opened a new PR to address the accessibility integration test changes. https://github.com/elastic/elastic-charts/pull/1137

2021-04-23 23:40 UTC, nickofthyme commented on integration/tests/accessibility.test.ts
> +  // });
`xit` (aka `it.skip` or `xtest`) is much cleaner way to skip tests, less code line diff. One exception is if the test has a type error. See https://jestjs.io/docs/api#testskipname-fn

```suggestion
  xit('should include the series types if one type of series', async () => {
    const tree = await common.testAccessibilityTree(
      'http://localhost:9001/iframe.html?id=annotations-lines--x-continuous-domain',
      '.echCanvasRenderer',
    );
    // the legend has bars and lines as value.descriptions not value.name
    const hasTextOfChartTypes = tree.children.filter((value) => {
      return value.name === 'bar chart';
    });
    expect(hasTextOfChartTypes[0].name).toBe('bar chart');
  });
```

2021-04-23 23:40 UTC, nickofthyme commented on integration/tests/legend_stories.test.ts
> +    });
Seeing as this test does not expect a screenshot. I think it could be done in an enzyme/jest unit test with much less overhead and achieve the same goal. What do you think?

2021-04-26 13:24 UTC, rshen91 commented on integration/tests/accessibility.test.ts
> +  // });
Thank you!! The linter changed xit -> it.skip 22bfe35

2021-04-26 16:45 UTC, rshen91 commented on integration/tests/legend_stories.test.ts
> +    });
Yasss please see 7dce80e

2021-04-26 16:50 UTC, nickofthyme approved these changes
LGTM, just a few minor comments

2021-04-26 16:50 UTC, nickofthyme commented on src/components/legend/legend.test.tsx
> +      const onLegendItemClick = jest.fn();
Exactly!

2021-04-26 16:50 UTC, nickofthyme commented on src/components/legend/legend.test.tsx
> +            yAccessors={['y']}
These are default so could remove.

```suggestion
```

2021-04-26 16:50 UTC, nickofthyme commented on src/components/legend/legend.test.tsx
> +      const legendItems = legendWrapper.find(LegendListItem);
This is an unnecessary step. You just need to get the `LegendListItem`

```suggestion
      const legendItems = wrapper.find(LegendListItem);
```

2021-04-26 17:38 UTC, rshen91 commented on src/components/legend/legend.test.tsx
> +      const legendItems = legendWrapper.find(LegendListItem);
02b5f97

2021-04-26 18:54 UTC, merged

2021-05-25 17:50 UTC, nickofthyme commented
:tada: This PR is included in version 29.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v29.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/29.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: