feat(legend): add shape to legend item
elastic/elastic-charts pull request #1227
Opened 2021-06-29 20:50 UTC by rshen91

## Summary

## Details

## Issues

### Checklist

- [ ] The proper chart type label was added (e.g. :xy, :partition) if the PR involves a specific chart type
- [ ] The proper feature label was added (e.g. :interactions, :axis) if the PR involves a specific chart feature
- [ ] Whenever possible, please check if the closing issue is connected to a running GH project
- [ ] Any consumer-facing exports were added to `packages/charts/src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-07-01 12:30 UTC, monfera reviewed
I haven't runtime tested; please consider some code changes, see the comments

2021-07-01 12:30 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
An explanation for the code change, part 2 (types). The `spec` may or may not have a `bubbleSeriesStyle` in part because the `spec` may or may not be a bubble series spec (we wouldn't need the `if` if we knew in advance). The original snippet solves it with a _type assertion_ (`as BubbleSeriesSpec`), which removes typing power, therefore a bit brittle (iow we try to avoid `as`, except in occasional literal assignments, as TS is kinda dumb). While this assertion is simple and trivial now, a future code change may violate this, and it wouldn't be caught, because `as` basically tells TypeScript, "ignore this type check". (So it's not an assertion like in other languages, where it _increases_ rather than _undercuts_ safety).

The current solution for these is to use a _type guard_. In this case, as the predicate (`seriesType === 'bubble')` is, and can now only be, a runtime predicate (meaning, it's not possible to know if it's true or false in code editing time), it must be a function. This is always the case if the subtyping depends on some property value. Luckily there is a function for this already: `isBubbleSeriesSpec`. These are called _type predicates_. Upon code reading, we can recognize type predicatie functions after the `someValue **is** SomeType` instead of the usual `boolean`, ie. the `is`. Worth reading up on type predicates, and type guards in general [in the doc](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates).

2021-07-01 12:30 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
Here, the specific benefit of using a type predicate function is that you get both the correct value (true/false) even if, in the future, the logic of determining how you identify a bubble series changes; and TypeScript grokking that in the `true` branch of the ternary, the spec will be of type `BubbleSeriesSpec`. It's good to not repeat these in the code, so `spec.seriesType === 'bubble'`, and similar, are ideally never found in the code, except in the single source of truth that `function isBubbleSeriesSpec...` in `packages/charts/src/chart_types/xy_chart/utils/specs.ts` is.

2021-07-01 12:30 UTC, monfera commented on packages/charts/src/components/icons/icon.tsx
> +export type IconType = keyof typeof typeToIconMap & string;
I think the `& string` is unnecessary.  

The type intersection operator `&` intersect the type on the left and the type on the right, ie. both the left and the right type must simultaneously apply. `IconType` needs to be both a key of `typeToIconMap` and a `string`. 

But `keyof typeof typeToIconMap` is only ever a `string`, because  each key of the `typeToIconMap` object is a string. JavaScript objects can _have_ key types of `string` or `symbol` only, but this object has no `symbol`s. (It's possible to _specify_ other object keys eg. numbers, but they'll be coerced into `string` first)

2021-07-01 12:35 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
(my local TS is acting up so if you see an issue, might worth checking with Nick or Marco until my setup gets fixed; hope the above code has no red squigglies)

2021-07-01 15:25 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
Hey thanks for the review - In a68797c I'm actually trying to account for any pointstyles in area and lines too. I'll keep thinking about the ternary format but I'm not sure if it will get too convoluted with these other two types also included?

2021-07-01 16:43 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
Whether it's `if` or ternary is secondary (haha). You can still avoid tests like `spec.seriesType === 'line'` in favor of calling the types of functions shown above, eg. `isBubbleSeriesSpec` and similar (reasons above).

Also, https://github.com/elastic/elastic-charts/commit/a68797c61aca5f7e074e7283263ca47d11596cbc does two things within each type branch:
1. recovering the style object (linked with the `spec.xxxxSeriesStyle` property)
2. assignment is the same for each: `shape = seriesStyle?.point?.shape ?? 'dot'`
Maybe it's nicer to separate the two parts, so that you make a function outside the already long `getLegendExtra` function, which returns a seriesStyle object, and then you just take the `seriesStyle?.point?.shape ?? 'dot'` value.

Something like this (haven't tested and my TS is in shambles):

```
function getSeriesStyle(spec): BubbleSeriesStyle | undefined {
      return isBubbleSeriesSpec(spec)
        ? spec.bubbleSeriesStyle
        : isLineSeriesSpec(spec)
        ? spec.lineSeriesStyle
        : isAreaSeriesSpec(spec)
        ? spec.areaSeriesStyle
        : undefined;
}

...

    const shape: IconType = getSeriesStyle(spec)?.point?.shape ?? 'dot';
```

I used `BubbleSeriesStyle` in the function return type above, because that has the `point` and that's all we need, though you can DRY up the types if needed, and use some newly created interface `PointSeriesStyle` which has `point`:
```
/** @public */
export interface PointSeriesStyle {
  point: PointStyle;
}

/** @public */
export type BubbleSeriesStyle = PointSeriesStyle;

/** @public */
export interface LineSeriesStyle extends PointSeriesStyle {
  line: LineStyle;
}

/** @public */
export interface AreaSeriesStyle extends PointSeriesStyle {
  area: AreaStyle;
  line: LineStyle;
}
```

@markov00 @nickofthyme do we have objects which have more than one `xxxSeriesStyle`? Can't we just rename these props to `seriesStyle` for uniformity across the series types? Looks like, at least across bubble, line and area, it'd be enough, and there'd be no need for such weird getters.

2021-07-07 21:58 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
hey

2021-07-07 22:27 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
> do we have objects which have more than one xxxSeriesStyle

No @monfera, I agree with you, I think the naming of the `xxxSeriesStyle` is a little unorthodox and redundant to say something like...

```tsx
<LineSeries lineSeiesStyles={{}} />
```

That being said all of these `xxxSeriesStyle` props are overrides for the matching name in the chart `Theme` object so `LineSeries.lineSeriesStyle` overrides `Theme.lineSeriesStyle` so there is nice consistency in naming. Also, these `xxxSeriesStyle` props are `Partials` of their respective `Theme` styles so the types also have a consistency. I don't think this change is warranted in this PR, but happy to discuss in a separate issue.

Merging the various types to extend `PointSeriesStyle` is a good improvement to enforce consistency, but the `getSeriesStyle` function you show above would work either way without using `as`.

As for the type guards you mentioned, these are only necessary because we `extend` the `BasicSeriesSpec` to form the bubble, line and area specs and use the `BasicSeriesSpec` as a shorthand type rather than a union of `BubbleSeriesSpec|AreaSeriesSpec|LineSeriesSpec|...`. We could discuss changing this to improve performance but this is a common thing across charts.

2021-07-07 22:37 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
Also we need to provide a fallback from the `Theme` for the respective point styles so extracting the style logic into separate function might be a little redundant.

```ts
function getSeriesStyle(spec): PointSeriesStyle | undefined {
  return isBubbleSeriesSpec(spec)
    ? spec.bubbleSeriesStyle
    : isLineSeriesSpec(spec)
    ? spec.lineSeriesStyle
    : isAreaSeriesSpec(spec)
    ? spec.areaSeriesStyle
    : undefined;
}

function getDefaultSeriesStyle(spec, theme): PointSeriesStyle | undefined {
  return isBubbleSeriesSpec(spec)
    ? theme.bubbleSeriesStyle
    : isLineSeriesSpec(spec)
    ? theme.lineSeriesStyle
    : isAreaSeriesSpec(spec)
    ? theme.areaSeriesStyle
    : undefined;
}

const pointStyles = (getSeriesStyle(spec) ?? getDefaultSeriesStyle(spec, theme)).point;
```

rather than just using the one round...

```ts
function getPointSeriesStyle(spec, theme): PointStyle | undefined {
  return isBubbleSeriesSpec(spec)
    ? spec.bubbleSeriesStyle?.point ?? theme.bubbleSeriesStyle.point
    : isLineSeriesSpec(spec)
    ? spec.lineSeriesStyle?.point ?? theme.lineSeriesStyle.point
    : isAreaSeriesSpec(spec)
    ? spec.areaSeriesStyle?.point ?? theme.areaSeriesStyle.point
    : undefined;
}

const pointStyles = getPointSeriesStyle(spec, theme);
```

2021-07-08 10:16 UTC, markov00 reviewed
I took a look at the point shapes example and looks like that square doesn't support the fill property as specified in the chart. We should fully align the shapes styles to the one in the chart. If the square has a red border and a yellow fill, we should reflect this in the legend

2021-07-08 13:52 UTC, rshen91 commented
> I took a look at the point shapes example and looks like that square doesn't support the fill property as specified in the chart. We should fully align the shapes styles to the one in the chart. If the square has a red border and a yellow fill, we should reflect this in the legend

This makes a lot of sense to me - I have removed the fill for the square icon in this commit 37cf9c1

2021-07-08 14:17 UTC, nickofthyme commented on packages/charts/src/components/icons/icon.tsx
> +  triangle: TriangleIcon,
Is there a reason you are not using the `PointShapes` here?

I think this map here should only be for actual icons not shapes.

We have a map called `ShapeRendererFn` of all `PointShapes` used for rendering the points on the chart and for textures. I think we should reuse these to be consistent and keep the code DRY.

https://github.com/elastic/elastic-charts/blob/87629e23e7cc8aef125a8b6d2b87092085abe2bd/packages/charts/src/chart_types/xy_chart/renderer/shapes_paths.ts#L28-L63

Which might be a little harder to use here than just a simple `svg` cuz you need to account for the rotation. Here is a usage example.

https://github.com/elastic/elastic-charts/blob/87629e23e7cc8aef125a8b6d2b87092085abe2bd/packages/charts/src/chart_types/xy_chart/renderer/dom/highlighter.tsx#L53-L61

So I think you should say does it have a shape then render a the pointShape, otherwise render the `DotIcon`, thus they are treated different.

2021-07-08 15:07 UTC, rshen91 commented on packages/charts/src/components/icons/icon.tsx
> +export type IconType = keyof typeof typeToIconMap | undefined;
I get the following error in the getPointShape() function (```return spec.bubbleSeriesStyle?.point?.shape ?? theme.bubbleSeriesStyle.point.shape;``` and for the line and area series return statements too)(typescript issue) when I make this not undefined. But I don't think it matters because we are returning the PointShape.Circle if there is no point.shape or theme.point shape: 
```Type 'PointShape | undefined' is not assignable to type '"alert" | "dot" | "empty" | "eye" | "eyeClosed" | "list" | "questionInCircle" | "circle" | "x" | "plus" | "diamond" | "square" | "triangle"'.
  Type 'undefined' is not assignable to type '"alert" | "dot" | "empty" | "eye" | "eyeClosed" | "list" | "questionInCircle" | "circle" | "x" | "plus" | "diamond" | "square" | "triangle"'.
```

Would it make sense to get rid of the type | undefined as suggested and then use @ts-ignore or something in the getPointShape() function? Thanks!

2021-07-08 16:10 UTC, nickofthyme commented on packages/charts/src/common/legend.ts
> +  shape?: IconType;
Yeah this maybe optional now once you separate the shapes from the icons. So when this is undefined use the `DotIcon`.

2021-07-09 12:59 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/compute_legend.ts
>        settings.sortSeriesBy,
Thank you! Commit 957d817 for changes

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/renderer/dom/highlighter.tsx
> +export function renderPath(geom: PointGeometry) {
it doesn't look like this is used externally, we can remove the export

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  NonXY: 'non-xy' as const,
I don't see where this change is used, actually. This type is also very specific to XY charts so it doesn't have sense to have a non XY here

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/color.tsx
> +  pointStyle.fill !== 'blue'
I don't get the reason why checking against a color like the blue.
Can you explain a bit better what this `custominzation` represent?
is not clear what we are checking: a color, a specific radius (bigger or smaller radius then 2 is ok?)

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/color.tsx
> +                )}
I think we should clean this up a bit more: checking the VRT screenshots you can see that the difference between the original dot and the markers are really big, we should align the size of the geometry to the one of the original dot.
<img width="73" alt="Screenshot 2021-07-12 at 16 38 09" src="https://user-images.githubusercontent.com/1421091/125308039-dec01e00-e330-11eb-88f6-a1acc95855e5.png">

<img width="132" alt="Screenshot 2021-07-12 at 16 37 59" src="https://user-images.githubusercontent.com/1421091/125307889-bf28f580-e330-11eb-8046-b471a74cf917.png">

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/color.tsx
> +            // @ts-ignore
can we try to advoid ignore here, what was the reason?

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/color.tsx
> +  pointStyle.fill !== 'blue'
You are returning a boolean (better if we avoid completely the `undefined`), so it's more common to name a function like that as `isCustomized` or `isCustom`

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/color.tsx
> +            <Icon type="dot" color={color} aria-label={`series color: ${color}`} />
can we instead of this, always render through `renderShape` and render a filled dot if the pointstyle is not specified (the default case)?
We can get rid of a condition in the code and probably we can get rid of the `getCustomization` function

2021-07-12 14:56 UTC, markov00 commented on packages/charts/src/components/legend/legend_item.tsx
> +            seriesType={seriesType ?? 'non-xy'}
if that was the reason for adding the `SeriesType.NonXY` you can mark the `seriesType` as optional, or just use the pointStyle to identify whenever use a specific share or the default dot.

2021-07-13 16:01 UTC, nickofthyme requested changes

2021-07-13 16:01 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +    return <Icon type="dot" color={color} aria-label={`series color: ${color}`} />;
Do you know why the dot size got bigger? I don't see from these changes where that happened.

![Image 2021-07-13 at 10 58 31 AM](https://user-images.githubusercontent.com/19007109/125485481-52cc67db-6179-4bf3-93ea-cd9ab75dfed9.jpg)

I think we should keep the old size for now unless the shape is specified because in that case a bigger icon is better to see the details of the marker.

2021-07-13 16:01 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +  const adjustedSize = MARKER_SIZE - strokeWidth;
What happened to the `strokeWidth` ratio and conditional adjusted size we talked about?

2021-07-13 16:16 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +    return <Icon type="dot" color={color} aria-label={`series color: ${color}`} />;
The larger size is when the shapeRendererFn is called for Circle, but the dot.tsx asset is the smaller icon (the default pre this PR). I think the refactoring in b2df204 is to change the default to the shapeRendererFn?

2021-07-14 15:13 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +  const adjustedSize = MARKER_SIZE - strokeWidth;
I think 2bc10ec has the changes thanks!

2021-07-14 15:14 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/renderer/dom/highlighter.tsx
> +export function renderPath(geom: PointGeometry) {
refactored in 4197004 thanks!

2021-07-14 15:15 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  NonXY: 'non-xy' as const,
Good call - major refactoring in 4197004

2021-07-14 15:15 UTC, rshen91 commented on packages/charts/src/components/legend/color.tsx
> +            // @ts-ignore
Refactored! 4197004

2021-07-14 15:15 UTC, rshen91 commented on packages/charts/src/components/legend/legend_item.tsx
> +            seriesType={seriesType ?? 'non-xy'}
Good call - 4197004

2021-07-15 16:43 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
This code has changed to reflect comments, so just gonna resolve this one.

2021-07-15 17:38 UTC, nickofthyme reviewed
Looking good. Just a few comments to cleanup the color icon logic.

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/scenegraph.ts
> +  const config = mergePartial<Config>(defaultConfig, partialConfig, { mergeOptionalPartialValues: true });
Thanks 👍🏼 

@markov00 We have noticed that in several places where `mergePartial` is use we have have issues where there are optional parameters on the base object that when `mergeOptionalPartialValues` is `false` will not look for such values on the partial object.

What do you think we make this option default to `true`?

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/texture.ts
> +const getPath = (textureStyle: TexturedStyles, size: number, strokeWidth: number): [path: Path2D, rotation: number] => {
😅

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +    <svg width={MARKER_SIZE * 2} height={MARKER_SIZE * 2} viewBox="0 0 16 16" aria-label={`series color: ${color}`}>
is `viewBox` necessary here?

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +  return Math.min(adjustedRadius, (radius ?? strokeWidth) * 2);
I think we could just set a static min of `1px` and max of the `MARKER_SIZE / 2`

```suggestion
  const adjustedRadius = isNil(radius) ? strokeWidth : ((MARKER_SIZE / 2) * strokeWidth) / (radius * 2);

  return Math.max(Math.min(adjustedRadius, MARKER_SIZE / 2), 1);
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +const getRatio = (radius: number | undefined, strokeWidth: number) => {
This should be `getAdjustedRadius` no?

```suggestion
const getAdjustedRadius = (radius: number | undefined, strokeWidth: number) => {
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +// to limit size, set a min and max
Let's make this a tsdocs comment

```suggestion
/** to limit size, set a min and max */
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +  const adjustedFill = shape ? fill ?? color : color;
```suggestion
  const { shape, fill = color, stroke, strokeWidth = 1, opacity, radius } = pointStyle?.shape ? 
    pointStyle ?? { } : {
      fill: color,
    };
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +          d={pointStyle?.shape === PointShape.Diamond ? shapeFn(adjustedSize / 3) : shapeFn(adjustedSize / 2)}
What is this for? We shouldn't divide by `3` cuz that's just arbitrary. Some shapes may appear bigger than others but they are all still the same size.

```suggestion
          d={shapeFn(adjustedSize / 2)}
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
>            stroke={stroke ?? color}
This should be assigned only when `shape` is defined

```suggestion
          stroke={shape ? stroke ?? color : undefined}
```

2021-07-15 17:38 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +          fill={adjustedFill}
Now applied in destructuring

```suggestion
          fill={fill}
```

2021-07-15 20:18 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +          d={pointStyle?.shape === PointShape.Diamond ? shapeFn(adjustedSize / 3) : shapeFn(adjustedSize / 2)}
The diamonds only have cutoff but the other shapes seem fine with `/2`

2021-07-15 20:32 UTC, nickofthyme commented on packages/charts/src/components/legend/color.tsx
> +            <Icon type="dot" color={color} aria-label={`series color: ${color}`} />
done, not sure what commit though

2021-07-15 20:32 UTC, nickofthyme commented on packages/charts/src/components/legend/color.tsx
> +                )}
now match `8` previous size for all shaped. See latest changes.

2021-07-15 20:33 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +          d={pointStyle?.shape === PointShape.Diamond ? shapeFn(adjustedSize / 3) : shapeFn(adjustedSize / 2)}
can you show me a pic of what you mean?

2021-07-15 20:45 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +          fill={adjustedFill}
80c4cea thank you!

2021-07-15 20:45 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
>            stroke={stroke ?? color}
80c4cea thanks!

2021-07-15 20:45 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +  const adjustedFill = shape ? fill ?? color : color;
Sweet! I think I am following - I did something similar in 80c4cea LMK what you think

2021-07-15 20:45 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +// to limit size, set a min and max
80c4cea thanks!

2021-07-15 20:45 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +const getRatio = (radius: number | undefined, strokeWidth: number) => {
80c4cea thank you!!!

2021-07-15 20:46 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +  return Math.min(adjustedRadius, (radius ?? strokeWidth) * 2);
Woah! Cool 80c4cea

2021-07-15 20:46 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +    <svg width={MARKER_SIZE * 2} height={MARKER_SIZE * 2} viewBox="0 0 16 16" aria-label={`series color: ${color}`}>
No it is not!  80c4cea

2021-07-15 21:14 UTC, rshen91 commented
jenkins test this please

2021-07-16 06:22 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
I agree it'd be nicer in a separate function, with a slight twist. Instead of a serial set of boolean predicates, how about something like
```
switch(spec.seriesType) {
    case SeriesType.Bubble: 
        return spec.bubbleSeriesStyle?.point?.shape ?? theme.bubbleSeriesStyle.point.shape;
    case SeriesType.Line: 
        return spec.lineSeriesStyle?.point?.shape ?? theme.lineSeriesStyle.point.shape;
    case SeriesType.Area: 
        return spec.areaSeriesStyle?.point?.shape ?? theme.areaSeriesStyle.point.shape;
    default: 
        return PointShape.Circle;
}
```

OK this wouldn't work as these tests don't act as type guards, while the `is...` functions do.

What do y'all think about the `switch(true)` pattern? Something like
```
switch(true) {
    case isBubbleSeriesSpec(spec): 
        return spec.bubbleSeriesStyle?.point?.shape ?? theme.bubbleSeriesStyle.point.shape;
    case isLineSeriesSpec(spec): 
        return spec.lineSeriesStyle?.point?.shape ?? theme.lineSeriesStyle.point.shape;
    case isAreaSeriesSpec(spec): 
        return spec.areaSeriesStyle?.point?.shape ?? theme.areaSeriesStyle.point.shape;
    default: 
        return PointShape.Circle;
}
```
It has a minimal learning curve and especially with TypeScript's need for boolean type guards, it's a closer abstraction than an `if` chain. It is also perfectly legit JS, no worse than other `switch` statements. Probably more controversial in webapp code than in library code eg. our use case. Here's [more](https://medium.com/trabe/using-switch-true-in-javascript-986e8ad8ae4f) on `switch(true)`.

2021-07-16 06:22 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
A related term [yoda condition](https://eslint.org/docs/rules/yoda) is.

2021-07-16 13:54 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +    }
wow 🤩 🤯

2021-07-16 13:59 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +const getRatio = (radius: number | undefined, strokeWidth: number) => {
Ugh sorry I'm dumb this should be `getAdjustedStrokeWidth`

2021-07-16 14:14 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +        stroke: color,
This `stroke` is never used cuz of line 50...

```tsx
stroke={shape ? stroke ?? color : undefined}
```

```suggestion
```

2021-07-16 14:15 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +  const adjustedFill = shape ? fill ?? color : color;
Yeah that looks fine. I just made one comment on the stroke default. https://github.com/elastic/elastic-charts/pull/1227#discussion_r671288361

2021-07-16 18:27 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +        stroke: color,
13e576d for changes, thank you!

2021-07-20 10:27 UTC, markov00 approved these changes
It looks great, works as expected.
Just a minor comment: in the legend we can ignore the `strokeWidth` if greater than 1 to avoid having a big stroke that cover the entire icon.
We can also ignore `opacity` that is less than 0.5 if we don't want to see the icon disappear

2021-07-20 10:27 UTC, markov00 commented on packages/charts/src/components/icons/icon.tsx
> +  fillColor?: IconColor;
`fillColor`is not a valid attribute of an `svg` element and it seems not be used anyway by our code

2021-07-20 14:12 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
>      ? pointStyle ?? {}
The idea behind checking the `pointStyle.shape` and using `{ fill: color }` is to avoid applying default styles to the default dot. Otherwise you could have the default dot with an opacity (etc.) that is not desirable. I think we pull this into a separate function and provide defaults easier.

Something like this but figure out the typings
```ts
const getStyles = (color: string, {
  radius,
  fill,
  strokeWidth,
  stroke,
  shape,
  opacity,
}: PointStyle = {}) => (shape ? {
  radius,
  fill,
  strokeWidth: strokeWidth ?? 1,
  stroke: stroke ?? color,
  shape: shape ?? PointShape.Circle,
  opacity: opacity ?? 1,
} : {
  fill: color,
  shape: shape ?? PointShape.Circle,
});
```

2021-07-20 14:12 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +    radius = 4,
This is not needed, this default is handled in the logic below.

```suggestion
    radius,
```

2021-07-20 21:51 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
>      ? pointStyle ?? {}
Lmk if you think this is ok! 57d1684 thanks!

2021-07-20 21:51 UTC, rshen91 commented on packages/charts/src/components/legend/legend_icon.tsx
> +    radius = 4,
57d1684 thank you!

2021-07-20 21:57 UTC, rshen91 commented on packages/charts/src/components/icons/icon.tsx
> +  fillColor?: IconColor;
this makes sense to me, thanks for the catch of the invalid svg prop - let me know what you think about changes in 150b3d6 thanks

2021-07-21 17:45 UTC, nickofthyme commented on stories/stylings/stylings.stories.tsx
> +export { Example as shapeLegendMultipleSeries } from './25_mixed_chart_shapes';
Generally we match these so they are easy to find

```suggestion
export { Example as mixedChartShapes } from './25_mixed_chart_shapes';
```

2021-07-21 18:39 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_icon.tsx
> +          d={pointStyle?.shape === PointShape.Diamond ? shapeFn(adjustedSize / 3) : shapeFn(adjustedSize / 2)}
Ok I see what you mean here. I think a better solution would be to scale down the diamond to fit inside of the "viewport". Like described [here](https://math.stackexchange.com/a/60722/952008). 

![image](https://user-images.githubusercontent.com/19007109/126541924-1e5a67d0-269d-4e10-b959-c3041851ca56.png)

### Before
![Image 2021-07-21 at 12 57 13 PM](https://user-images.githubusercontent.com/19007109/126542015-3f44975c-7394-4619-bed7-7798d2803c12.jpg)

### After
![Image 2021-07-21 at 1 16 54 PM](https://user-images.githubusercontent.com/19007109/126542031-b62743dc-66d8-4fdb-8c17-aec3f98d6a59.jpg)

> Notice the diamond is now contained inside the square. See code changes in 8637423b929d3ee55f2e7d3ba8b556f4a605d45a.

2021-07-21 19:02 UTC, nickofthyme commented on packages/charts/src/components/legend/color.tsx
> +  pointStyle.fill !== 'blue'
gone

2021-07-21 19:13 UTC, nickofthyme commented on packages/charts/src/components/legend/color.tsx
> +                )}
Fixed in latest changes...

![image](https://user-images.githubusercontent.com/19007109/126546340-c0458530-1db5-4a20-add5-cc7677ceeb69.png)

2021-07-21 19:24 UTC, nickofthyme approved these changes
Ok sorry for all the back and forth. I think this is good to merge now. We can discuss my changes tomorrow and modify them as you see fit.

2021-07-21 19:24 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/shapes_paths.ts
>  };
See https://github.com/elastic/elastic-charts/pull/1227#discussion_r674236783 and rational [here](https://math.stackexchange.com/a/60722/952008)

2021-07-21 19:24 UTC, nickofthyme commented on packages/charts/src/components/legend/legend_item.tsx
> +            pointStyle={alignLegendPointStyles ? pointStyle : undefined}
Used to explicitly control legend point style alignment by user. We could infer when to apply the styles as a fallback by comparing the local `[area/line/bubble]SeriesStyles.point` to the respective value on the `Theme`. This could be something like...

```ts
deepEqual(areaSeriesStyles.point, theme.area.point, true); // true for partial comparison
```

But that seems a bit much for now.

2021-07-21 19:24 UTC, nickofthyme commented on packages/charts/src/components/legend/legend.tsx
> +          {items.map((item, index) => renderLegendItem(item, itemProps, index))}
removed unused argument

2021-07-21 20:26 UTC, nickofthyme commented on packages/charts/src/components/legend/color.tsx
> +            <LegendIcon pointStyle={pointStyle} color={color} ariaLabel={`Change series color, currently ${color}`} />
I'm not sure about this in the future. When the point styles take over this could mean the series color being selected/set would not be reflected in the color icon. Should revisit at a later time.

2021-07-22 15:48 UTC, rshen91 commented
@markov00 @nickofthyme updated the vrts in 46ab4e4. The large file change is because of the styling for the pointStyles are taken from the theme by default with the empty fill. Let me know if this looks good to you thanks!

2021-07-22 16:22 UTC, rshen91 commented
@elastic/eui-design do you mind providing a review on this PR please?

2021-07-22 16:28 UTC, rshen91 commented
jenkins test this

2021-07-22 16:45 UTC, rshen91 commented
jenkins test this please

2021-07-22 18:27 UTC, nickofthyme commented
@miukimiu the basic changes here is that for any area, line or bubble chart that has visible points we use the point styles on the legend icon. This would be all area styles now have hollow points with white fill. 👇🏼 

![image](https://user-images.githubusercontent.com/19007109/126690061-d74e3091-1e3e-4ccb-904b-2be3d0d57a45.png)

If this is not desirable we could only apply the styles to the legend icon with they differ from the main them styles.

2021-07-26 10:11 UTC, monfera requested changes
tl;dr using solid colored shapes would help readability and accessibility, for when there's no solid/holey shape ambiguity on a given chart. WCAG guidelines don't sufficiently address, yet still acknowledge the impact of shape size and aspect ratio when it comes to distinguishing colors or contrast. An example: given the same bounding box for the marker in the legend, the full paint of that bounding box will be more ink than a solid disk in that bounding box, which is still better than, say, an empty circle with a thin border.

-------------------------------

_Thanks for letting in a late comment after the Kibana testing week and PTO. I'd still like to squeeze in a question relating to this as a significant BREAKING change, specifically, the mass changes to mocks due to solid to hollow markers, as those can't be solved well with a follow-up PR._

If there's a variety of markers, it's indeed great to give the user a marker shape cue, as in this change, which is good for cross-referencing and accessibility:

![image](https://user-images.githubusercontent.com/1548516/126967753-a8fcbba4-06f3-49f9-b586-e9f7fd834189.png)

Yet most charts, thankfully, don't have a plethora of marker types. In fact it's almost always a bad idea to mix marker types, as
- on line charts, it's redundant, and the markers themselves introduce noise (see the above example for this as well - it's exaggerated, but real line charts will turn to such barbed wire charts easily)
- on scatterplots, each marker type has different characteristics (ink surface area; ink bounding box; occlusion effects; crowding effects; perceptibility, saliency etc.) so a medium or high overplotting scatterplot will be a bit of a mess
- etc

The upshot is that most of the charts won't need legend disambiguation for marker shape.

![image](https://user-images.githubusercontent.com/1548516/126967701-8ec81a40-b337-4a9e-9acd-2b976bb25da5.png)

Using holey markers (circle instead of disk etc.) has the negative that the legend ink area is diminished to a fraction of it, which reduces the ability to find the right legend item, discern colors etc. and is thus an accessibility issue. Even if the shape is holey on the line, it's easier to discern the color of a long line than of a small circle. Even if we disregard it, it's useful if at least the legend colors have significant "meat", for easier cross-referencing.

Proposal: 
- use solid markers in the legend if there's no ambiguity about holey vs solid markers on a given chart
- even if the user opts for some other marker, eg. `x` everywhere on a chart, use solid colors in the legend (*)
- if it's needed, please point a well discussed use case (eg. issue comments, PR comments here and conclusions) and add an option for enforcing the behavior currently in this PR commit; eg. which user team would need holey legends on non-ambiguous charts, and why 

(*) Comments for where it might be heading, post this PR:

Currently, the legends area is a singleton on the chart. Therefore the encoded information of the markers are conflated. For example, it's currently not possible to have three distinct legends for color, marker type and size. This impairs readability of each encoding channel. So the long term thing is to treat legends as data visualizations in and of themselves (a recurring theme) so that a legend is not a singleton on the chart, and also, so that multiple charts can share some legend(s).

![image](https://user-images.githubusercontent.com/1548516/126971013-53b9ac91-3d1a-4add-96a5-09aead66ba40.png)

In light of such future, we can restate my request this way: when there's no marker ambiguity, let's NOT EVEN try to use the legend swatch to convey anything about marker shape; it's just a color swatch.

Also, having decoupled the marker shape from the color assignment for non-ambiguous cases, we can do better and switch to squares or rectangles for the color swatch (with or without rounded corner) to further increase the color ink area.

2021-07-26 10:21 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +}
It's not a PR comment, yet a great example for how TS leads to hoops we have to jump through (in the code, as well as runtime) to satisfy its type verification operations. TS requires a specific, and sometimes artificial coding style. Maybe we could eventually move the series type to distinct classes, as class instances have both static and runtime type, and something like this `if` cascade would become a simple method call

2021-07-27 07:57 UTC, monfera approved these changes

2021-07-27 09:15 UTC, markov00 approved these changes
Changes looks good to me!

2021-07-27 13:33 UTC, merged

2021-07-28 16:49 UTC, nickofthyme commented
:tada: This PR is included in version 33.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v33.1.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/33.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: