feat(heatmap): limit brush tool through brush area
elastic/elastic-charts pull request #1270
Opened 2021-07-27 15:47 UTC by rshen91

## Summary

## Details

## Issues

### Checklist

- [ ] The proper chart type label was added (e.g. :xy, :partition) if the PR involves a specific chart type
- [ ] The proper feature label was added (e.g. :interactions, :axis) if the PR involves a specific chart feature
- [ ] Whenever possible, please check if the closing issue is connected to a running GH project
- [ ] Any consumer-facing exports were added to `packages/charts/src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-07-28 12:19 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape!.height - start.y : end.y - start.y,
`dragShape` can be undefined, we should be careful here

2021-07-28 15:50 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape!.height - start.y : end.y - start.y,
Thank you, good catch. I added checking for dragShape in 5fc5f9c

2021-07-28 16:11 UTC, rshen91 commented
jenkins test this

2021-07-29 16:03 UTC, nickofthyme approved these changes
Code LTGM.

2021-07-29 17:21 UTC, rshen91 commented
jenkins test this

2021-08-02 14:08 UTC, rshen91 commented
jenkins test this

2021-08-02 16:38 UTC, markov00 requested changes

2021-08-02 16:38 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
As chatted on zoom, the height needs always to be computed as the `endY - startY`. The solution to fix this correctly is to limit the `endY` value from 0 to the height of the chart area computed as `gridHeightParams.gridCellHeight * gridHeightParams.pageSize`

2021-08-02 17:01 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
thank you 🙏🏻

2021-08-02 17:45 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
Please see 08657e2!

2021-08-16 13:40 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
Hey @rshen91 it doesn't work, I'm pretty sure you are wrongly using `gridParams.height` instead of `gridParams.gridCellHeight`

2021-08-16 15:23 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
ah, my bad, sorry! Please see 206713d for updates

2021-08-16 16:11 UTC, rshen91 commented
jenkins, test this

2021-08-18 16:51 UTC, monfera commented
Do we want to continue to sport the unusual white border around the actually selected, snapped area? I get it if it needs to be a separate PR but is there consensus toward solving it?

2021-08-18 17:06 UTC, monfera commented on packages/charts/src/chart_types/heatmap/renderer/dom/highlighter.tsx
> +              {/* the rectangle box */}
Nice documentation embedded 😍

2021-08-18 17:24 UTC, monfera reviewed
The code changes look good!

I see a bit of grey flashing on the very bottom of the "After" version gif, toward the end of the gif recording, not sure if it means that the issue scope is not fully met, so I'm planning to approve right after the acceptability of that flashing is clarified

Not the scope of this PR, I can't vouch for the preexisting grey/white/grey banding so I'd leave it to @markov00 to consider the timing of a design update there

2021-08-19 14:36 UTC, rshen91 commented
Good call @monfera,



 no rush to approve this PR or anything, but the refactoring done since those initial screenshots seem to have fixed the issue. I'll update the after screenshot in the issue too. Here is a new giphy: 

https://user-images.githubusercontent.com/20343860/130087709-7e8de58d-f50c-42bb-8466-bb9d6999b639.mp4

2021-08-20 12:44 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts
> +          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
looks good now, thanks

2021-08-20 12:46 UTC, markov00 approved these changes
It works correctly after the last changes.
Please merge master and update the screenshots accordingly
Good to merge after that

2021-08-20 13:14 UTC, monfera approved these changes
LGTM! 

I's not the making or the topic of this PR, could you please create and link an issue to this PR to discuss the grey/white/grey nested selection box styling concern? I think the simplest solution would be the removal of the inner grey rectangle, which looks off, is an unusual aesthetic. But maybe there have been discussions about it

2021-08-20 14:47 UTC, merged

2021-08-23 14:52 UTC, nickofthyme commented
:tada: This PR is included in version 34.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v34.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/34.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: