feat(annotations): add onClickHandler for annotationss
elastic/elastic-charts pull request #1293
Opened 2021-08-10 18:41 UTC by rshen91

## Summary

## Details

## Issues
Closes #1211 

### Checklist

- [ ] The proper chart type label was added (e.g. :xy, :partition) if the PR involves a specific chart type
- [ ] The proper feature label was added (e.g. :interactions, :axis) if the PR involves a specific chart feature
- [ ] Whenever possible, please check if the closing issue is connected to a running GH project
- [ ] Any consumer-facing exports were added to `packages/charts/src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-08-18 17:44 UTC, monfera commented
What's the approach for the mouse capture area padding? For example, the actual line of a line annotation is very thin, and Fitts law needs significant meat for being able to reliably select. Then again, there may be some tightly spaced lines, in which case the generous padding is constrained so that the midline between two nearby parallel lines determines if this or that line gets selected (otherwise the capture zone of one line can occlude the other line). So, a one-dimensional Voronoi version of [this 2D example](https://bl.ocks.org/Kcnarf/6d5ace3aa9cc1a313d72b810388d1003)—or the Voronoi picker @nickofthyme added to charts—at least conceptually, and the 1D Voronoi logic can be extracted into a `common` directory for later reuse.

Capture zone padding gets more complicated with mixed or overlapping annotations: both horizontal and vertical lines; lines over rectangles; overlapping rectangles; annotation over the text of some other annotation; annotation over bars, data point markers or other interactive elements. 

So, just curious about what we have as current goals for this, maybe on the original issue, or on a separate issue that goes into this kind of detail (or discussed as part of the PR)

2021-08-18 19:38 UTC, rshen91 commented
> What's the approach for the mouse capture area padding? For example, the actual line of a line annotation is very thin, and Fitts law needs significant meat for being able to reliably select. Then again, there may be some tightly spaced lines, in which case the generous padding is constrained so that the midline between two nearby parallel lines determines if this or that line gets selected (otherwise the capture zone of one line can occlude the other line). So, a one-dimensional Voronoi version of [this 2D example](https://bl.ocks.org/Kcnarf/6d5ace3aa9cc1a313d72b810388d1003)—or the Voronoi picker @nickofthyme added to charts—at least conceptually, and the 1D Voronoi logic can be extracted into a `common` directory for later reuse.
> 
> Capture zone padding gets more complicated with mixed or overlapping annotations: both horizontal and vertical lines; lines over rectangles; overlapping rectangles; annotation over the text of some other annotation; annotation over bars, data point markers or other interactive elements.
> 
> So, just curious about what we have as current goals for this, maybe on the original issue, or on a separate issue that goes into this kind of detail (or discussed as part of the PR)

Hey! I might be misinterpreting, but this only should make the line annotation marker clickable if passed an onAnnotationClick listener not the whole line.

2021-08-19 08:54 UTC, monfera commented
> this only should make the line annotation marker clickable if passed an onAnnotationClick listener not the whole line

Thanks Rachel! It wasn't clear to me, as the issue (to which I need to compare the PR) mentions annotations, and specifically the line and rectangle annotations. Could the scope be added to the gh issue, ie. it's just the annotation markerand not the entire rectangle or line, so I only review things in the PR that are agreed to change.

I guess that for the annotation marker, it'll stay as it is, basically no padding. @markov00 do we want to add padding to the markers, and are there signs of needs for capture events on the lines/rectangles?

2021-08-19 16:42 UTC, nickofthyme requested changes
Looking good! I made a few suggestions along with some questions. Ping me if something doesn't make sense.

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/specs/rect_annotation.tsx
> +  specComponentFactory<RectAnnotationSpec, 'groupId' | 'annotationType' | 'zIndex' | 'style' | 'onClickHandler'>(
```suggestion
  specComponentFactory<RectAnnotationSpec, 'groupId' | 'annotationType' | 'zIndex' | 'style'>(
```

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.ts
> +          // marker: <div /> ,
```suggestion
```

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.ts
> +  });
Could you also add a test for line marker clicks and clicking two rect annotations (i.e. where `rects: [{ ... }, { ... }]`)

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    // no pointer if there is a onAnnotionClick but there is a highlighted geometry
```suggestion
    // no pointer if there is a onAnnotationClick but there is a highlighted geometry
```

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    }
So this is applied even if there are no annotations actively hovered?

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
>          }
I don't think we should fire the annotation click **AND** the element click handler, but instead just the element or just the annotation, where element is higher priority.

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +      });
There is a type guard for this that will likely fix the `@ts-ignore` below.

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +    const lineAnnotations = [];
nit

```suggestion
    const rects = [];
    const lines = [];
```

Making this the eventual object keys simplifies line 121. Unless there is a good case for this I tend to match the keys. Since the context of this function is already annotation (i.e. `tryFiringOnAnnotationClick`) I think this is just easier.

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +    }
There is a type guard for this that will likely fix the @ts-ignore below.

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  onClickHandler?: MouseEventHandler<Element>;
```suggestion
```

Stale remnant

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  id: string;
```suggestion
```

This is redundant as it extends `Spec` which has `{ id: string; }`

2021-08-19 16:42 UTC, nickofthyme commented on packages/charts/src/components/portal/tooltip_portal.tsx
> +  onClickHandler?: MouseEventHandler<Element>;
```suggestion
```

Stale remnant

2021-08-19 16:42 UTC, nickofthyme commented on storybook/main.js
> +    '@storybook/addon-actions',
❤️

2021-08-20 13:49 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    }
As far as Im understanding, the highlighted geometries does not include the annotations. That pointer logic is tied to the annotation tooltip. I'm noticing though that the current implementation isn't working --- the pointer is being applied on all parts of the chart that aren't the elements if there's an annotation. Thank you for the catch, I'll make sure to update with a fix

2021-08-20 13:52 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/specs/rect_annotation.tsx
> +  specComponentFactory<RectAnnotationSpec, 'groupId' | 'annotationType' | 'zIndex' | 'style' | 'onClickHandler'>(
Thank you! afa3069

2021-08-20 13:52 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.ts
> +          // marker: <div /> ,
Thank you! afa3069 for this change

2021-08-20 13:52 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    // no pointer if there is a onAnnotionClick but there is a highlighted geometry
Lols my bad, thanks afa3069

2021-08-20 13:53 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  id: string;
Thank you! afa3069

2021-08-20 13:53 UTC, rshen91 commented on packages/charts/src/components/portal/tooltip_portal.tsx
> +  onClickHandler?: MouseEventHandler<Element>;
Thank you! afa3069

2021-08-20 14:00 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
> +  onClickHandler?: MouseEventHandler<Element>;
Missed this! 8cc5e7f for changes

2021-08-20 14:01 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    }
8cc5e7f has updates thank you for the catch!

2021-08-20 15:06 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
>          }
Thank you for this catch! I agree, only elementclick or annotationclick should happen in one click action. 8cc5e7f for changes thank you!

2021-08-20 15:12 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
>          }
Sorry, wrong commit 7d7700d for changes thank you

2021-08-20 15:12 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +      });
Thank you for the zoom to clarify 7d7700d for changes

2021-08-20 15:12 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +    const lineAnnotations = [];
7d7700d for changes thanks!

2021-08-20 15:12 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +    }
7d7700 for changes thank you!

2021-08-20 19:32 UTC, nickofthyme requested changes
Most changes were addressed, just a few more comments.

2021-08-20 19:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
> +    expect(callArgs.rects[0].id).toEqual('rect2');
wouldn't you expect both to be in `rects`?

```suggestion
    expect(callArgs.rects[0].id).toEqual('rect1');
    expect(callArgs.rects[1].id).toEqual('rect2');
```

2021-08-20 19:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
>      }
I see why this is here now. I think you can simplify this logic to just this...

```suggestion
    if (highlightedGeometries.length === 0 && settingsSpec.onAnnotationClick && tooltipState) {
      return 'pointer';
    }
```

Are you sure you don't need to check the `tooltipState` for anything? Just if it exists that means it has something?

2021-08-20 19:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    tooltipState,
This context is not obvious I think we rename this to be clear.

```suggestion
    annotationTooltipState,
```

2021-08-20 19:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
>      }
Not needed with change in logic

```suggestion
```

2021-08-20 19:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_click_caller.ts
> +        if (!elementClickFired && onAnnotationClick && tooltipState) {
👍🏼

2021-08-20 19:33 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    // no pointer if there is a onAnnotionClick but there is a highlighted geometry
My first spelling correction that's not my own 🏆

2021-08-20 21:43 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
>      }
Removed in cb44d3e thank you!

2021-08-20 21:43 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
> +    tooltipState,
Smart suggestion cb44d3e

2021-08-20 21:44 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_cursor_pointer.ts
>      }
Yep! Good call cb44d3e

2021-08-23 17:57 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
> +    expect(callArgs.rects[0].id).toEqual('rect2');
I attempted a large scale refactoring but then backtracked in 495fc1b. I think it might introduce a breaking change in what is returned for tooltips so it might be better for a new PR.

2021-08-23 18:39 UTC, nickofthyme commented on .github/workflows/pull_request.yaml
> +name: '@elastic/charts - CI'
This was an old file picked up from merging. You can delete this.

2021-08-23 18:39 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/annotations/tooltip.ts
> +        customTooltipDetails: customTooltipDetails ?? spec.renderTooltip,
So this is in lieu of the refactoring that backfired?

2021-08-23 21:12 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/annotations/tooltip.ts
> +        customTooltipDetails: customTooltipDetails ?? spec.renderTooltip,
Cleaned up here: a4c1713

2021-08-23 21:12 UTC, rshen91 commented on .github/workflows/pull_request.yaml
> +name: '@elastic/charts - CI'
Removed in a4c1713 thanks!

2021-08-24 14:27 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/annotations.tsx
>        />,
Probably best to use a consistent naming `onDOMElementClick`

2021-08-24 14:28 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
>      expect(onAnnotationClick).toBeCalled();
Can you say something like `expect(onAnnotationClick).toBeCalledWith({ lines: [...] });`?

2021-08-24 15:52 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
>      expect(onAnnotationClick).toBeCalled();
I changed the test a little in 726d952 let me know if this seems valid

2021-08-24 21:02 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
> +    expect(annotation.debug()).toContain('onDOMElementClick');
This test doesn't assert what the interaction does just that a function was passed

2021-08-24 21:47 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/chart_state.interactions.test.tsx
> +    expect(annotation.debug()).toContain('onDOMElementClick');
I also missed updating the two rectangle annotation test - f37ec94 for changes. Lmk what you think thank you

2021-08-25 14:10 UTC, rshen91 commented
In aa8c050 I updated the failing vrts - these were exclusively screenshots that had line annotations and had slight pixel changes

2021-08-30 19:16 UTC, nickofthyme requested changes
The cursor pointer logic does not match the actual logic. The `onAnnotationClick` event should **NOT** fire over element geometry. Also check how this acts with line charts when clicking points above the rect annotations.


https://user-images.githubusercontent.com/19007109/131392512-c6e45a8e-81ee-4ea7-96b0-095894430264.mp4

2021-08-31 18:37 UTC, rshen91 commented
> The cursor pointer logic does not match the actual logic. The `onAnnotationClick` event should **NOT** fire over element geometry. Also check how this acts with line charts when clicking points above the rect annotations.
> 
>  Screen.Recording.2021-08-30.at.02.13.54.PM.mp4

Please see 4c07301 for the fix thank you for catching this!

2021-09-01 13:01 UTC, nickofthyme approved these changes
Looks great @rshen91! Great work.

2021-09-01 13:59 UTC, merged

2021-09-13 15:58 UTC, nickofthyme commented
:tada: This PR is included in version 35.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v35.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/35.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: