feat(heatmap): add text color contrast to heatmap cells
elastic/elastic-charts pull request #1342
Opened 2021-08-30 14:58 UTC by rshen91

## Summary
Text will now take into account the background color of the cell and adjust its contrast to 4.5. 

## Details
Still to do:
- [x] Confirm that true textContrast will default to 4.5
- [x] Fix the makeHighContrastColor function for cases where contrast is hard/impossible (commit 2eaa8e6)
- [x] Take into account the background color of the chart in addition to the background color (commit 5c6b739)

## Issues
Closes #1296 

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
-  [x] New public API exports have been added to `packages/charts/src/index.ts`
- [x] The proper documentation and/or storybook story has been added or updated

2021-08-31 16:15 UTC, markov00 commented
@rshen91 I've few doubts on your todo list:
> Fix bullet chart stories without having contrast defined

we should fix the bullet chart in a different PR not this one. I'm also not sure what you mean by fix stories without having contrast defined.

> Take into account the background color of the chart in addition to the background color

Can you please explain to me why? in heatmap we are rendering the text on top of a cell, that is colored. Why we need to consider the background color of the chart? for semi-transparent colors?

2021-08-31 16:58 UTC, rshen91 commented
Hi @markov00 good questions. Sorry, these points might have been misleading:

> Fix bullet chart stories without having contrast defined
> 
> we should fix the bullet chart in a different PR not this one. I'm also not sure what you mean by fix stories without having contrast defined.
I have some stories locally that look like they're failing these changes but they seem to be fine in vrt testing in master. I'm thinking because they're not failing in master then it's fine? 


In https://github.com/elastic/elastic-charts/issues/1296, they mention

> Extra feature: add a way to pass the page background color as well to handle constrast measurement with rgba values (we hit this bug already in table Lens dynamic coloring).

Should I do this in a future PR? I might be misunderstanding thank you!

2021-09-02 09:54 UTC, markov00 requested changes

2021-09-02 09:54 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
> +        : font.textColor;
I think we should not patch the code at the renderer level.
This rendering method should be agnostic and should not know If we are rendering a heatmap cell text or something else.
It renders a text with a color specified by the `font` property.
The optimal solution is to move the calculation of the correct `textColor` within the cell calculation code, you can probably add to the `Cell` type a new property to describe the textColor and change the way the `renderText` method is called using that `textColor` instead of the default one coming from the `config` like:
```
config.cell.label.visible &&
        withContext(ctx, () => {
          // render text on cells
          const { x, y } = heatmapViewModel.gridOrigin;
          ctx.translate(x, y);
          filteredCells.forEach((cell) => {
            if (cell.visible && !Number.isNaN(cell.fontSize))
              renderText(ctx, { x: cell.x + cell.width / 2, y: cell.y + cell.height / 2 }, cell.formatted, {
                ...config.cell.label,
                textColor: cell.textColor,
              });
          });
        }),
```

2021-09-02 09:54 UTC, markov00 commented on packages/charts/src/common/color_calcs.ts
> +      return getContrast(contrastColor, background) > ratio ? contrastColor : scaledContrast.toString();
two comments here:
1- can you explain why you have made these changes? 
2- instead of use both hex and rgba values, can you please always use `rgba` strings instead where possible?

2021-09-02 13:50 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
> +  const convertPageBackgroundColor = getHexValue(pageBackgroundColor);
For sure! So the issue I was facing was using rgba(0,0,0,0) instead of #00000 both pointing to a transparent color. The fillTextColor() has a warning for rgba values with an alpha value of 0. But yes, overall I do think it makes the most sense to have the fillTextColor() just using rgba values.

2021-09-02 13:54 UTC, rshen91 commented on packages/charts/src/common/color_calcs.ts
> +      return getContrast(contrastColor, background) > ratio ? contrastColor : scaledContrast.toString();
1. I was noticing one of the cell background colors (rgba(44, 127, 184, 1),  #2c7fb8) was going to white text with worse contrast than if it was black text. I hunted the issue down to this edge case and added this to catch this issue in the future.

2. I agree, I will make sure to refactor to use rgba values where possible instead of hex. I got hung up on the transparent hex value being passed by default but I agree that the rgba value makes the most sense. Will include this in my refactoring, thanks!

2021-09-02 15:35 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
> +        : font.textColor;
Thank you! I think I am following - f32b32d for changes

2021-09-02 15:36 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/types/config_types.ts
> +      textContrast: boolean | number;
f32b32d for changes thanks!

2021-09-02 15:36 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/types/config_types.ts
> +  pageBackgroundColor: Color;
Can you let me know if I did this right in f32b32d? thanks!

2021-09-02 15:36 UTC, rshen91 commented on packages/charts/src/common/color_library_wrappers.ts
> +
Refactored in f32b32d thank you!

2021-09-02 16:22 UTC, rshen91 commented
jenkins, test this

2021-09-02 17:09 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +        theme.background.color === 'transparent' ? '#000000' : theme.background.color,
if with this code you mean: if the theme background color is `transparent` keyword use `black` as the fallback, I think we need to change that to use `white` instead, as the default theme is the LIGHT one
Use white rgba if possible `rgba(255,255,255,1)`

2021-09-02 17:09 UTC, markov00 commented on packages/charts/src/common/color_calcs.ts
> +          : '#fff';
```suggestion
          ? 'rgba(0,0,0,1)'
          : 'rgba(255,255,255,1)';
```

2021-09-02 17:09 UTC, markov00 commented on packages/charts/src/common/color_library_wrappers.ts
> +
it looks like the function still there

2021-09-02 17:09 UTC, markov00 commented on packages/charts/src/common/fill_text_color.ts
> +    backgroundColor === 'transparent' ? '#000000' : backgroundColor,
similar to a previous comment:
the background fallback for transparent color should be white (because the default theme is the light one)
So if you need to replace the `transparent` with a valid fallback please use `rgba(255,255,255,1)`

2021-09-02 17:09 UTC, markov00 commented on storybook/stories/heatmap/heatmap.stories.tsx
> +export { Example as textColorContrast } from './4_color_text.story';
instead of creating a new vrt for that, just show by default the value labels on the categorical example,we can save two new tests (please also remove the added test as this replace the need of the vrt added)

2021-09-02 17:11 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/primitives/text.ts
> +  const convertPageBackgroundColor = getHexValue(pageBackgroundColor);
`rgba(0,0,0,0)` is `transparent`
If you want to use black is `rgba(0,0,0,1)` with full opacity

2021-09-02 17:52 UTC, rshen91 commented on storybook/stories/heatmap/heatmap.stories.tsx
> +export { Example as textColorContrast } from './4_color_text.story';
I think I did this in 0a9a914 thank you

2021-09-02 17:52 UTC, rshen91 commented on packages/charts/src/common/fill_text_color.ts
> +    backgroundColor === 'transparent' ? '#000000' : backgroundColor,
Good catch thank you 0a9a914

2021-09-02 17:52 UTC, rshen91 commented on packages/charts/src/common/color_calcs.ts
> +          : '#fff';
Yikes sorry! 0a9a914 thanks

2021-09-02 17:52 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +        theme.background.color === 'transparent' ? '#000000' : theme.background.color,
0a9a914 thank you!

2021-09-02 17:52 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +        config.cell.label.textContrast ? 4.5 : false,
Ok I think Im following 0a9a914 thanks!

2021-09-02 17:52 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/types/config_types.ts
> +      textContrast: boolean;
Ok cool sounds good to me 0a9a914 for changes thanks!

2021-09-02 17:53 UTC, rshen91 commented on packages/charts/src/common/color_library_wrappers.ts
> +
removed in 0a9a914 sorry!

2021-09-08 10:22 UTC, markov00 approved these changes
I'm ok merging this PR for now.
I will take a look and clean up the color contrast functions in a next PR because it doesn't look very clean and readable.

2021-09-08 14:42 UTC, merged

2021-09-13 15:57 UTC, nickofthyme commented
:tada: This PR is included in version 35.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v35.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/35.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: