build: update webpack server to v4
elastic/elastic-charts pull request #1353
Opened 2021-09-02 12:42 UTC by markov00

I've updated webpack dev server to v4
(it just clears up a bit the yarn install warnings about wrong dependencies)

2021-09-02 14:27 UTC, nickofthyme requested changes
Requesting the dependencies stay in their relative workspace, see comment below.

2021-09-02 14:27 UTC, nickofthyme commented on storybook/package.json
> -    "typescript": "^4.1.3"
Why are we doing this? The idea behind moving these deps deeper was to isolate package ownership between different workspaces. If you want these for the integration server you should add them to the top-level `package.json` until we make integration it's own workspace.

2021-09-02 14:27 UTC, nickofthyme commented on storybook/package.json
> -    "sass": "~1.32.0",
What's the reasoning for switching back to `node-sass`, is is faster than the dart compiled version? I also agree with moving to `dart-sass`.

2021-09-02 16:12 UTC, markov00 commented on storybook/package.json
> -    "sass": "~1.32.0",
chatted online, reverted change

2021-09-02 16:12 UTC, markov00 commented on storybook/package.json
> -    "typescript": "^4.1.3"
chatted online, reverted change

2021-09-02 16:21 UTC, nickofthyme approved these changes

2021-09-02 16:40 UTC, merged

2021-09-13 15:58 UTC, nickofthyme commented
:tada: This PR is included in version 35.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v35.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/35.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: