Heatmap theming
elastic/elastic-charts pull request #1356
Opened 2021-09-02 19:40 UTC by nickofthyme

## Summary

Adds dark mode to goal charts with configurable theme styles.

![Screen Recording 2021-09-02 at 02 31 07 PM](https://user-images.githubusercontent.com/19007109/131904992-3ac326a4-8a79-4c2f-a90d-1ed16707fc17.gif)

### BREAKING CHANGES

The `HeatmapSpec.config` prop is removed. All properties have been moved/renamed under new `Theme.heatmap` options with the following exceptions:

- `HeatmapSpec.margin` was not used, `Theme.chartMargins` should be used in the future.
- `HeatmapSpec.fontFamily` `HeatmapSpec.width` and `HeatmapSpec.height` all removed as they were never used.

## Details

The `Heatmap`, `Partition` and `WordCloud` specs all have no connection to the chart theme and thus have no canonical inheritance to dark mode. This PR fixes this for the `Heatmap` chart and adds some added styles to the text labels as exposed in xy charts. The `HeatmapConfig` was broken down and moved into `Theme` or the `HeatmapSpec` accordingly. We should avoid having a `Config` option to control theme as this not only creates a disconnect but also allows for multiple sources of truth for similar options and another property requirement to toggle for theming between dark and light modes.

In the future I think it would great if we have a `Config` alternative to the react props in addition to the `Theme` options.

## Issues

closes #1335

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-09-06 10:31 UTC, markov00 requested changes
I can see a visible difference on the `echHighlighterMask` in this PR in dark mode:
the Y axis and the selected areas are not transparent anymore as in the old implementation:
This PR:
<img width="475" alt="Screenshot 2021-09-06 at 12 21 09" src="https://user-images.githubusercontent.com/1421091/132203702-8a4128d8-3be1-44bd-8c3e-624fc3b6db63.png">
Current master:
<img width="431" alt="Screenshot 2021-09-06 at 12 30 14" src="https://user-images.githubusercontent.com/1421091/132203745-dc966a88-dede-44c7-87bb-0792851df921.png">

Despite the black text, the behaviour on master is the correct one. clearly visible also in the light theme
<img width="469" alt="Screenshot 2021-09-06 at 12 21 02" src="https://user-images.githubusercontent.com/1421091/132203830-475e13e9-4e8f-4a62-87c4-dc6ce8950220.png">

2021-09-06 10:31 UTC, markov00 commented on packages/charts/src/utils/themes/dark_theme.ts
> +      fill: 'white', // white === transparent
what do you mean by `white === transparent`

2021-09-06 10:31 UTC, markov00 commented on packages/charts/src/utils/themes/theme.ts
> +export interface HeatmapStyles {
What if this is renamed as singular? because it covers the style of the heatmap, not multiple styles.

2021-09-06 10:31 UTC, markov00 commented on packages/charts/src/utils/themes/theme.ts
> +export interface HeatmapStyles {
I know that this goes in tandem with the GoalStyles (that IMHO we should rename to singular)
Happy to discuss this

2021-09-06 14:18 UTC, markov00 commented
just remember that the `heatmap` is in `@alpha` and we can also avoid having BREAKING CHANGES there

2021-09-07 14:29 UTC, nickofthyme commented on packages/charts/src/utils/themes/theme.ts
> +export interface HeatmapStyles {
Yeah probably right about being consistent with others like `BarSeriesStyle`, and like `<div style={{}} />`. I just think of it as there are multiple styles to define, not a singular style.

2021-09-07 14:29 UTC, nickofthyme commented on packages/charts/src/utils/themes/dark_theme.ts
> +      fill: 'white', // white === transparent
this was an old comment from the config that I kept.

2021-09-07 18:25 UTC, nickofthyme commented
> I'd also like to chat about when a style needs to be pushed into the theme and when it needs to be local on the spec.

Aside from what we discussed in todays meeting, I tend to through all function thing like formatters in the spec rather than the theme.

2021-09-07 20:19 UTC, nickofthyme commented on packages/charts/src/utils/themes/dark_theme.ts
> +      fill: 'white', // white === transparent
This `fill` was applied to a `<mask>` for some reason. Made it optional to be transparent by default unless someone wants to color the mask `#ff0000` or something. See c8b5ea7.

![Screen Recording 2021-09-07 at 02 57 53 PM](https://user-images.githubusercontent.com/19007109/132405730-db076add-55a9-4715-b38e-156a3ac11c1e.gif)

2021-09-07 20:23 UTC, nickofthyme commented on packages/charts/src/utils/themes/theme.ts
> +export interface HeatmapStyles {
4f91559

2021-09-08 10:35 UTC, markov00 approved these changes
Looks good to me
tested locally and all the issues are now gone!

2021-09-08 14:02 UTC, merged