ci: remove EUI initialization
elastic/elastic-charts pull request #1366
Opened 2021-09-08 15:04 UTC by markov00

I've found that due to a generic import we where also importing and initializing part of EUI in our VR server app.
This should reduce the load time of a page by ~200ms for each test.
I've also removed the icon preload and I will eventually move

2021-09-08 16:22 UTC, nickofthyme requested changes

2021-09-08 16:22 UTC, nickofthyme commented on integration/server/generate/vrt_page_template.js
> -document.querySelector('html')?.classList.add('disable-animations');
Why is this to be removed? This is to prevent icons causing diffs in VRT.

2021-09-08 16:28 UTC, markov00 commented on integration/server/generate/vrt_page_template.js
> -document.querySelector('html')?.classList.add('disable-animations');
to reduce the loading time on every chart
From what I'm testing only one test is getting failures on the icon. We can probably replace that icon with a simple, non EUI icon.

2021-09-08 16:42 UTC, markov00 commented on integration/server/generate/vrt_page_template.js
> -document.querySelector('html')?.classList.add('disable-animations');
let me tray again including just this part https://github.com/elastic/elastic-charts/pull/1366/commits/2b3fc7c045befa1894a4c9db574eb1b216ab4750

The `disable-animations` class was already in the `html` tag so is safe to remove that last line

2021-09-08 17:00 UTC, nickofthyme commented on integration/server/generate/vrt_page_template.js
> -document.querySelector('html')?.classList.add('disable-animations');
Ok, but I don't think the error would be immediate. I would guess several will fail eventually & randomly if we do not preload the icons.

2021-09-08 21:17 UTC, markov00 commented on integration/server/generate/vrt_page_template.js
> -document.querySelector('html')?.classList.add('disable-animations');
with the preload icons it looks anyway good: 2b3fc7c

2021-09-09 20:38 UTC, nickofthyme approved these changes

2021-09-09 21:13 UTC, merged

2021-09-13 15:57 UTC, nickofthyme commented
:tada: This PR is included in version 35.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v35.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/35.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: