refactor: simplify text contrast code
elastic/elastic-charts pull request #1372
Opened 2021-09-10 14:20 UTC by markov00

## Summary

This PR simplifies the text color contrast code. This is required to complete https://github.com/elastic/elastic-charts/pull/1320

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-09-13 17:48 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/types/viewmodel_types.ts
> +    return getGreensColorScale(0.5, [highestValue, lowestValue])(value);
I'm actually created this as a very specific one just to move chromajs function into a single file. I can create have a more complex/functional fn when actually required

2021-09-16 13:12 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +  if (colorToRgba(theme.background.color)[3] < 1) {
I think this is great - I was seeing this in the sunburst stories because of the transparent default but I think it's fantastic to have a logger message to the consumer and just provide white as a fallback

2021-09-16 13:42 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/panels/panels.ts
> +        { color: [0, 0, 0, 0] },
Thank you for going through the codebase and making the color structured as in this case!

2021-09-16 15:27 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +  if (colorToRgba(theme.background.color)[3] < 1) {
should we change the default to white to avoid logging by default?

2021-09-16 15:27 UTC, nickofthyme approved these changes
Latest changes LGTM.

2021-09-16 15:27 UTC, nickofthyme commented on packages/charts/src/common/apca_color_contrast.ts
> +/* eslint-disable header/header */
Is this a file that makes sense to put under `packages/` like we do with `d3-delaunay`?

2021-09-16 15:45 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +  if (colorToRgba(theme.background.color)[3] < 1) {
I think there are few teams that relies on the `transparent` background because they are not using the EUI theme.
Before applying a white background by default I would first like to check the usage in Kibana and then make the change

2021-09-16 15:47 UTC, markov00 commented on packages/charts/src/common/apca_color_contrast.ts
> +/* eslint-disable header/header */
mmm I don't know it's worth rn
what are the benefits?

2021-09-16 16:36 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +  if (colorToRgba(theme.background.color)[3] < 1) {
Ohhh ok that makes sense thanks!

2021-09-16 16:37 UTC, rshen91 approved these changes
LGTM Marco! I love the consistent color formatting and trimming down the textInvertible and color contrast on by default 🙌🏻

2021-09-16 16:49 UTC, nickofthyme commented on packages/charts/src/common/apca_color_contrast.ts
> +/* eslint-disable header/header */
Isolating code that we duplicate from external sources, to later be deleted.

2021-09-17 11:00 UTC, monfera commented
Amazing! ![image](https://user-images.githubusercontent.com/1548516/133772043-0f0d01c4-4222-4952-a3d4-4786118dea50.png)

2021-09-17 11:24 UTC, monfera commented on packages/charts/src/common/apca_color_contrast.ts
> +/* eslint-disable header/header */
It's good for this PR but  I also suggested moving external code outside src and charts:
- our code isn't intermingled with external code
- we can better ensure that copyright notices are not impaired
- easier to collect external sources on an inevitable eventual future code audit
- lower risk of accidental manual or linter changes that might be at odds with copyright terms (someone accidentally fixes those `let`s without checking the header haha)
- we ourselves can more easily keep tabs on such deps (for newer version, npm availability etc.)
- the external code is not subject to the same linting standards etc. that we have for `src` and `charts`
- any such external dependency feasibly and preferably becomes a node module, eg. one of us discover that the functionality is now available as an npm module and we switch: easier to do
- it doesn't impact our metrics such as code coverage (I realize it's a pro/cons) 

I put it on #1303 and this item can be resolved now

2021-09-17 11:31 UTC, monfera commented
It looks like noticeably worse contrast here, with the elsewhere beneficial more eager use of white text:
![image](https://user-images.githubusercontent.com/1548516/133775577-861f877c-f451-4298-9ee2-05d7b50aa8c0.png)

2021-09-17 11:37 UTC, monfera commented
Aside from the above icicle graph, there seems to be cases where the switchover to white happens earlier than I think desired, and at least to me, the black font looks clearly more readable. This despite my wish for more white text when first seeing the former versions based on the old WCAG recommendations, so I was white leaning but it seems to overdo it esp. when the font is small. It's observable on a lot of partition charts
![image](https://user-images.githubusercontent.com/1548516/133776233-2f2828ed-5074-486e-b299-e23ed227a2b9.png)

2021-09-17 11:38 UTC, monfera commented
This is a great change :chefs_kiss:
![image](https://user-images.githubusercontent.com/1548516/133776523-d2d014e5-1f29-42c4-b602-51d142ccce02.png)

2021-09-17 11:41 UTC, monfera commented
Nice darkening of axis tick labels, a significant step in the right direction  
![image](https://user-images.githubusercontent.com/1548516/133776824-c53f2fb2-3892-4985-9869-fd91aa621183.png)

2021-09-17 11:44 UTC, monfera commented
Not sure if this and a few other Cartesian saturations are integral to the PR or some stories got updated for more color saturation, but something like this is way too Fisher-Price like; not necessarily in this PR but would prefer that our examples mostly reflect good practices 
![image](https://user-images.githubusercontent.com/1548516/133777081-323d0afd-3c37-4dc6-8c88-5a592cc7e06d.png)

2021-09-17 11:54 UTC, monfera reviewed
Code wise, and in spirit, looks great 🎉  

See some non-blocker comments inline.

The darkening of some (but for reason, not all; see most Cartesians and bullet/gauge/goal) axis tick labels is a welcome change, going from mid gray to slightly darker gray. Not necessarily in this PR, it'd be great to reach black or near-black. 

The level of text whitening seems excessive, at least to me resulting in clearly less readable text on lighter or mid luma backgrounds even when compared to the former dark gray, not to mention compared to using the new, real black which many partition charts now do for the dark. See individual comments for image examples

Some hover highlights (well, fading the other bits) got lost, for example:
![image](https://user-images.githubusercontent.com/1548516/133777397-1ee190e9-68ae-484c-b89a-9e6008e16f4a.png)
![image](https://user-images.githubusercontent.com/1548516/133777081-323d0afd-3c37-4dc6-8c88-5a592cc7e06d.png)

2021-09-20 10:17 UTC, markov00 commented
@monfera Thanks for catching the missing hover highlights: it was cased by my changes in the `clearCanvas`:
my initial idea was to clear the canvas with the background color from the theme to fix the wrong color blending value we have identified in one of our call. The solution was to fix the clearCanvas with:
```
function clearCanvas(ctx: CanvasRenderingContext2D, bgColor: Color) {
  withContext(ctx, () => {
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.fillStyle = bgColor;
    ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
  });
}
```
The problem happens when the `background` color is `transparent`  and the fillRect doesn't actually clear the screen.
I've pushed a change that does both: clear and fill with the background: https://github.com/elastic/elastic-charts/pull/1372/commits/70f17746f4ce19abf0f416e87e77e6a64aee2ab3

2021-09-20 10:18 UTC, markov00 commented
>  darkening of axis tick labels, 

@monfera and actually there is no darkening of the axis, but just the fact that the background didn't get cleared correctly caused the axis being rendered twice, one on top of the other, when moving the mouse over the legend (as in the linked screenshot)
We can definitely improve the default theme with better colors/styles

2021-09-20 16:14 UTC, monfera commented
@markov00 I had a vague recall that I did the`fillRect` instead of the default expectation `clearRect` for some reason, when we started phasing out Konva. An issue like this may or may not have been the reason. It'd be worth adding a comment line above the `fillRect` to explain why it's used instead of `clearRect` (eg. mentioning about which test case will fail). Though the test case will fail anyway 😄

2021-09-20 16:21 UTC, monfera approved these changes
Approving it with the note that I'm not the authority on the contrast criteria, so I can't speak for or against the extent the new algo leans toward white text over mid colored areas. Thanks for linking the external PR where you enquired about some of the apparent contrast regressions we saw

2021-09-20 16:57 UTC, cchaos commented
Thanks for the note @markov00. I love that you all continue to think through accessibility improvements. I will throw my quick concern out there for jumping into the APCA calculation (without much research of my own). Mainly, that I have 2 concerns.

1. Consistency with our calculations we use throughout Elastic products including any automated a11y testing like through Axe. 
2. Actually produces less contrast (based on previous criteria) which seems counter to other conversations being had around better accessibility (i.e. #1378).
<img width="494" alt="Screen Shot 2021-09-20 at 12 41 30 PM" src="https://user-images.githubusercontent.com/549577/134042427-afbabc71-ce8e-43b0-8cd0-1cb25572f397.png">

A ratio of `2.97` is notably lower than our typical `4.5` minimum.

2021-09-20 23:10 UTC, nickofthyme requested changes
I think in some cases the white what easier to read IMHO but seems like it's half way between how it was and how it is with these changes. Anyway, nothing to change if we still to the standard that is fine with me.

Is this intentional? Seems like an error to me.

![image](https://user-images.githubusercontent.com/19007109/134088234-19eaa481-75f0-4949-8b9f-212f27329cdf.png)

2021-09-21 08:51 UTC, markov00 commented
Thanks @cchaos for your comments, I'd like to add few more comments to clarify the choices:

> 1. Consistency with our calculations we use throughout Elastic products including any automated a11y testing like through Axe.

You are right, we should prefer a consistent methodology across Elastic. I reverted the changes to use the WCAG2/relative luminance algorithm, for now, but I will keep the APCA method around for testing.

If I'm not wrong Axe works testing accessibility of DOM elements, but it can't read/interpret the content of an image, providing valuable hints if a text has more/less contrast than its background. Charts are rendered in `canvas` and Axe can't give us hints on the accessibility of the image itself (we at the moment have a set of hidden texts surrounding the chart to improve the accessibility). We can check the a11y and readability of the chart (the canvas part) only manually at the moment, unfortunately.

> 2. Actually produces less contrast (based on previous criteria) which seems counter to other conversations being had around better accessibility (i.e. [feat(all): global, multi-channel prefers-contrast option #1378](https://github.com/elastic/elastic-charts/issues/1378)).

The method used in your example to calculate the contrast is the one available in the WCAG 2 specification (based on relative luminance, with a set of AA, AAA levels specific to the calculated contrast ratio). The APCA method instead shows that white on orange has higher contrast than black on orange (see this interesting article about the orange button problem in a11y https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio/). There are definitely differences in the calculated contrast but, as described [here](https://www.w3.org/TR/wcag-3.0/#issue-container-generatedID-7), these differences between old and new ways are the output of multiple research for improving text readability and contast.

The WCAG 3.0 is still a draft, but it's announced that the APCA method will replace the existing one: 
https://www.w3.org/TR/wcag-3.0/#issue-container-generatedID-7

Chrome also has added the APCA contrast in the dev tools (now only behind an experimental flag and with some bugs 😬 ) https://developer.chrome.com/blog/new-in-devtools-89/#apca

Anyway, I've already switched back to the previous WCAG 2.0 calculation for consistency. APCA is still in development/research so there can be improvement in the near feature that can push us to adopt it earlier, in the meantime, we can live with the relative luminance method.

2021-09-21 08:53 UTC, markov00 commented
> I think in some cases the white what easier to read IMHO but seems like it's half way between how it was and how it is with these changes. Anyway, nothing to change if we still to the standard that is fine with me.
> 
> Is this intentional? Seems like an error to me.
> 
> ![image](https://user-images.githubusercontent.com/19007109/134088234-19eaa481-75f0-4949-8b9f-212f27329cdf.png)

You have probably picked up an outdated commit, this was solved in https://github.com/elastic/elastic-charts/pull/1372/commits/70f17746f4ce19abf0f416e87e77e6a64aee2ab3

2021-09-21 15:02 UTC, nickofthyme approved these changes

2021-09-21 16:33 UTC, merged

2021-09-22 15:45 UTC, cchaos commented
Thanks for the explanation @markov00 . I definitely agree that the current luminance method is not ideal in certain situations, but I just couldn't believe **how** different the results between that and the new method were. It worries me a bit and since it's still in draft, I'd worry about jumping to use it right away. I appreciate that it's back to the original calculation at least for now. It's definitely something we'll want to continue to monitor and most likely an effort we'll want to take across multiple packages, not just charts.

As an FYI, I've also been monitoring this issue for a while, just now realizing that it was started/continues to be updated by the creator of that APCA method. https://github.com/w3c/wcag/issues/695

2021-10-05 10:16 UTC, nickofthyme commented
:tada: This PR is included in version 37.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v37.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/37.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-10-14 06:17 UTC, Myndex commented
Hello everyone, @monfera @cchaos @markov00 this post is replying specifically to Marco, Caroline, and Robert:

## First, just FYI, there is an [APCA repo _here_](https://github.com/Myndex/SAPC-APCA)
And I've opened the discussion tab to field any questions or concerns.

### Some general responses to comments in this thread:
1) WCAG 3 APCA is a paradigm shift in how visual contrast is predicted and how those predictions apply to design guidelines.
    - WCAG 3 does not compare directly to WCAG2 in terms of results or how it's used.
    - Font size and font weight are part of the key parameters to consider.
2) WCAG 2 contrast is known to be wrong in a number of areas, which is why I've been developing APCA.
    - WCAG 2 is not perceptually accurate, it does not follow human perception.
    - It's only a reasonably useful contrast value when **_both_** of the following are true:
        - The text is darker than the background AND
        - The background is lighter than ` #A0A0A0 `
3) Per the examples in this thread, the concerns raised don't appear to be due to APCA
4) The total APCA L<sup>c</sup> contrast scale from black to white is a little more than 100.
    - It is perceptually uniform, so cutting the L<sup>c</sup> in half results in an apparent halving of contrast.
    - The distance between the _middle_ and white or black is around L<sup>c</sup> 51 to L<sup>c</sup> 54
    - The minimum recommended for fluent content text is L<sup>c</sup>60 to 75
    - The minimum recommended for large text is L<sup>c</sup>45 to 60

## Specifics
### Luminance vs Lightness for Readability Contrast
> _contrast calculation ... new algorithm called APCA used in the WCAG 3 draft instead of the previous algorithm that used the perceived luminance. ,,, this method seems to fix a lot of issues that the luminance method didn't consider._

Hi Marco, yes the WCAG 2 method does not follow human perception of suprathreshold contrast, which is critical for readability. APCA does use luminance, but it goes much farther, weighting the luminances per a perception model to achieve uniformity that follows our perception of text on a screen.

> _Chrome also has added the APCA contrast in the dev tools (now only behind an experimental flag and with some bugs 😬)_

I was surprised by the interest and the large number of early adopters. I seriously was not expecting the turhout if you will, so I'm a tad embarrassed that some of the early code was a little less stable. The current version has been going since February, and seems stable, further adjustments are expected to be more like tweaks. 

> _You are right, we should prefer a consistent methodology across Elastic. I reverted the changes ... I will keep the APCA method around for testing._

There are some developers that are doing both WCAG 2 and 3 at one with success (you lose the APCA flexibility though). 

Feel free to ask questions at the APCA GitHub repo in the discussions area.... I'm going to respond to some of your other comments with Caroline's below...

### Mid Contrast, and the W/B Switch Point — Responding to @monfera 
Hello Robert, it appears to me that the fonts may be too small for the given contrast?

One of the changes in APCA is the recognition of spatial frequency as a primary force driving contrast perception. For our purposes, spatial frequency means font size and weight.

Another change is the definition of the "middle" of the contrast range on a display ...  where to flip from black to white text? The short answer is that if we are going to "auto flip" between black and white, we want to do so when relative luminance (Y) is between 0.32Y and 0.40Y, with 0.35Y - 0.36Y being about ideal for most colors. 

This translates to a BG color of equivalent luminance to ` #999 `(0.32Y) to ` #aaa ` (0.4Y) with ` #a0a0a0 ` being a "nearly ideal" 0.351. However, that does not mean that any size font can be used. The APCA contrast for black or white text against ` #a0a0a0 ` is not much more than L<sup>c</sup>50, and the minimum recommended font is about 32px to 36px for normal weight.

In the example below, just the top two lines qualify, bottom row is a fail for fluent readability:

<img alt="DataExample0100mixed" width="554" src="https://user-images.githubusercontent.com/42009457/137234050-7c092cf0-0ddf-459f-91cc-d8e816b854d9.png">

This is using a color from your icicle chart, and now let's look there:

<img width="333" alt="Screen Shot 2021-10-13 at 1 46 28 PM" src="https://user-images.githubusercontent.com/42009457/137234153-30e9ed8e-96a1-4fa0-82e3-1877aeca40dd.png">

The font is fairly thin, and perhaps font-smoothing is set to the faux antialias? While the black font is indeed near black, the white font is no where near white, it's only at 50% the luminance of white, so perceptually is about 65% lightness when we'd want it to be ~95% lightness. 

This has nothing to do with the APCA algorithm, it's a function of the font weight and size, and the way the rasterizer is antialiasing, reducing contrast. One of the stipulations in WCAG 3 is to not use faux antialiasing, and leave "webkit font smoothing" at auto, which allows the device to do subpixel anti-aliasing. Counterintuitively, the anti-alias setting in Webkit-font-smoothing is actually a blending that reduces resolution and contrast.

This same issue is true here:

<img width="262" alt="Screen Shot 2021-10-13 at 1 45 52 PM" src="https://user-images.githubusercontent.com/42009457/137235404-8e6c1103-0fb6-481e-895a-129a687dbc74.png">

Again, with that BG color, only the top two rows in this test sample are recommended. Second from the bottom is "poor but passing" and the bottom row is a fail for fluent readability.

<img alt="DataExample0200mixed" width="554" src="https://user-images.githubusercontent.com/42009457/137235707-56e7f5b9-8454-4f8b-927a-db1818eed6e1.png">

-----
### In response to @cchaos 
Hello Caroline, regarding your concerns with "consistency" & "less contrast", in reverse order:

**2) To your comment "Actually produces less contrast" — this is not true,** though I see how you might come to that conclusion. 

APCA does not produce contrast. APCA does nothing to the colors, it only predicts how a human will perceive them, and their effect on readability. And yes, if you try to compare the math it might appear that APCA allows lower contrast, but the reality is perhaps a bit hidden. For instance, your example:

<img width="547" alt="CarolinesExample" src="https://user-images.githubusercontent.com/42009457/137245268-b7e30d3d-4f20-4e22-9c02-56171ff4c324.png">

Let me ask you if that _seems like_ less than 3:1 contrast? Perhaps it's not fair without a comparison. Take a look at this one below to compare, which one has better contrast? The one above or this one below? 

<img width="305" alt="Screen Shot 2021-10-13 at 9 20 39 PM" src="https://user-images.githubusercontent.com/42009457/137251464-4db91241-f914-4b17-ab8b-15c70826d302.png">

After thinking about this for a moment, click the spoiler for the answer:

<details>
  <summary>**Spoiler: Which is better contrast?**</summary>
  
Okay, so the first example that you provided was the Orange Example I am running on my sites. This problem brought WCAG 2.x to my attention and is part of why the design community loathes WCAG 2 contrast.

In the first example, APCA correctly reports the contrast as readable at Lc61 for the _appropriate font sizes_. WCAG reports a fail at 2.97:1. 

Okay but then on the _second_ one, APCA reports a **total fail** and *prohibits* any text at this level.

### WCAG reports the second one as a _PASS at 4.5:1_ (!!)

Should this second one be a pass? At 4.5:1? The colors are ` #797979 ` and ` #110402 `. APCA fails it for all text, but WCAG 2 says it's 4.5:1 and fine even for body text. Here's a body text sample with those colors:

<img width="647" alt="Screen Shot 2021-10-13 at 9 28 52 PM" src="https://user-images.githubusercontent.com/42009457/137252146-b9ed6321-88ea-4293-950e-e17ad78e [...]