refactor: scale improvements
elastic/elastic-charts pull request #1383
Opened 2021-09-17 06:26 UTC by monfera

## Summary

## Details

## Issues

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-09-17 10:46 UTC, monfera commented
test this

2021-09-17 11:02 UTC, monfera commented
test this

2021-09-17 20:15 UTC, monfera commented
test this

2021-09-17 20:51 UTC, monfera commented
test this

2021-09-17 21:09 UTC, monfera commented on packages/charts/api/charts.api.md
> +    End: HistogramModeAlignment;
Not sure why it changed in this specific PR, can look unless someone has a hunch

2021-09-17 21:13 UTC, monfera commented on packages/charts/src/components/portal/tooltip_portal.tsx
> +  const ps = useMemo(() => mergePartial(base, settings, { mergeOptionalPartialValues: true }), [settings, base]);
`base` got extracted so the `const ps` is in a single line, otherwise `@ts-ignore` isn't effective

2021-09-17 21:42 UTC, monfera commented on packages/charts/src/scales/scale_band.ts
> +
I'm planning to reify the domain as `[T, T, ...T[]]` ie. minimum 2 entries

2021-09-17 22:27 UTC, monfera commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +            domain: xDomain.domain as number[],
A couple of new assertions were necessitated by the removal of a bunch of `any`, these should eventually be revisited with better type guarding or more generic functions but it's already a win to localize where we skip static type tests

2021-09-17 22:31 UTC, monfera commented on packages/charts/src/scales/scale_continuous.ts
> +      return { value: NaN, withinBandwidth: false };
The current `master` has semantics more akin to `value: 0` for the `data.length === 0` case: the question mark will make the `invertWithStep` yielded results go `null`, which then gets `Math.min` / `Math.max`-ed. `null` gets coerced to zero in such cases. No complaints in current `master` because `any`. I think the zero semantics was accidental and more explicit "breaker" value like `NaN` feels better

2021-09-17 22:43 UTC, monfera commented
test this

2021-09-19 16:16 UTC, monfera commented
test this

2021-09-19 16:30 UTC, monfera commented
test this

2021-09-19 16:52 UTC, monfera commented
test this

2021-09-19 19:39 UTC, monfera commented
test this

2021-09-20 05:12 UTC, monfera commented
test this

2021-09-20 05:21 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/domains/nice.ts
> -  return nice.length > 0 && nice.every((d) => d);
Slight change to the meaning: the replacement of this function `!nice.includes(false)` yields `true` with an empty array

2021-09-20 05:27 UTC, monfera commented
test this

2021-09-20 14:16 UTC, monfera commented
test this

2021-09-20 15:03 UTC, nickofthyme commented
@elasticmachine run elasticsearch-ci/docs

2021-09-20 15:03 UTC, nickofthyme commented
@elasticmachine merge upstream

2021-09-20 15:31 UTC, monfera commented
test this

2021-09-20 22:07 UTC, nickofthyme requested changes
Really incredible changes all around Robert! 🎉 

I have two contentions:

### Loosening null/undefined checks

I see a lot of places where we loosed the type checking from check for (`==`) or against (`!=`) `null` and/or `undefined`. This even occurs on values whose types are neither `null` nor `undefined`. I'm not sure what the use case was for these checks, maybe some js checking, but I'd like to make sure there are no regressions by removing them.

### requiring domain `min` and `max`

I do not think the we should require the consumer of charts to specify the full extents. Before it was one or the other. I think they should be optional on the `Axis.domain` spec and default to `NaN`.

2021-09-20 22:07 UTC, nickofthyme commented on packages/charts/src/scales/scale_band.test.ts
> +    expect(scale.isValueInDomain((null as unknown) as 'a' | 'b' | 'c' | 'd')).toBe(false);
I think we could be looser on using `any` inside tests because unit tests are for the logic and not the types in my eyes. Especially in this case where you are casting something that is obviously not the right type for testing a js edge case.

In this case we could say `@ts-expect-error` with a description to show this was intentional and why.

```ts
    // @ts-expect-error: bad input
    expect(scale.isValueInDomain('z')).toBe(false);
    expect(scale.isValueInDomain(null)).toBe(false);
```

the issue with this is that it applied to the whole line so you don't get type checking outside of the one bad variable. If there were more than one intentional error I think this usage would be good but in this particular case I'm in favor of using `any`.

```suggestion
    expect(scale.isValueInDomain('z' as any)).toBe(false);
    expect(scale.isValueInDomain(null)).toBe(false);
```

2021-09-20 22:07 UTC, nickofthyme commented on packages/charts/src/utils/common.test.ts
> -  });
I'd like to keep this.

2021-09-20 22:07 UTC, nickofthyme commented on storybook/webpack.config.js
>    return await config;
remove `async` from function expression too

```suggestion
  return config;
```

2021-09-21 06:39 UTC, monfera commented
Thanks @nickofthyme for checking! 

### Null checks

I'll revisit the places where I switched a `==`/`!==` null check to `===` / `!==`. I grepped these and checked most but not all. Sometimes there was a `== null` check when the value couldn't have been null (just `undefined` or maybe not even that). Likely a result of refactorings over time, which is good (reduction of type variability)

### Domain min/max requirements

I agree that making the prop non-optional is a bit of a departure from our established ways. Charts is consumed by Elastic solutions. The current API feels overly geared toward use cases we increasingly don't cater for (largely outside our control, eg. licensing), with the price of API type complexity that permeates the full depth of our implementation down to render functions (side note, I've long proposed a separation of the API layer to liberate the internals from overly intricate API offerings).

My goals were, in this order:
1. stem all those type variations
2. reduce static and runtime code path divergence by shedding some optionalities or union types; in particular, prevent branching contamination of internals by somewhat arbitrary API complexity 
3. reduce boilerplate (code noise)
4. (minuscule step) move toward a more deliberate, judicious, balanced use for runtime (bundle size etc.) and code source (code readability, and mental space dedicated/required by various aspects)

I'd like to understand why requiring `NaN` in an otherwise required object is burdensome. It's simple to always fill three props. We are not developing the library for individual, ad-hoc library users with wildly different circumstances to roll plots into their data science Jupyter or Observables notebook, so we don't have "retail user" facing requirements. It's likely not as burdensome for the Elastic Developer to use a required property and put `NaN` in it as to read through all the public type permutations. TS is powerful but my feeling is that we're currently on the side of overspending it on union types and optional properties often for no clear gain but of significant cost (while underutilizing TS power via too many `any` with broad downstream reach). I'd like to discuss this as there may be aspects I'm unaware of; my feel is that the developers using our library would also benefit from more regular and less intricately chiselled API choices. Let's work out a more uniform target use of TS, it's over- and underused here and there, depending on the aspect

2021-09-21 06:44 UTC, monfera commented on integration/page_objects/common.ts
>      }
Glad to get rid of the try/catch, haven't analyzed its purpose. As we discussed I'd like to get rid of try/catch in the use of scales too, started that work but shelved at the time, it's best to avoid try/catch use in normal chartmaking code as usually there's a better option

2021-09-21 06:58 UTC, monfera commented on packages/charts/src/chart_types/partition_chart/layout/utils/legend_labels.ts
> +    if (formattedValue && formattedValue !== HIERARCHY_ROOT_KEY) {
For this PR, my goal was mostly, no coercive comparisons. Yet, when viewing some of these, it was appealing to improve the code like here (the single, comapct truthiness check rules out multiple things). In the change you highlighted here, the type safety is at least as strong as before.

I agree there's a real risk of a library emitting unexpected types. Whenever we use a library (whether or not it has an associated type library) we call some shots and live with assumptions about what types may be returned. 

There is value in becoming more runtime-defensive, esp. if we collectively design this. For example, instead of excluding known "bad" values like `null` (and maybe still getting an unexpected `undefined`, `NaN`, whatever) we can use positive checks I've pitched before (and use some in this PR) such as `Number.isFinite()`

I also proposed that we wrap around each dependency we use. For example, D3 scales are a too embedded in Charts. `packages/charts` and even more so, `packages/charts/src` shouldn't use as many node imports for calculations as today, eg. D3 utils, time utils, color utils etc. should be wrapped in simple, compact abstractions outside our `src`, with whatever static and runtime type checks and coercions

2021-09-21 07:00 UTC, monfera commented on integration/server/mocks/@storybook/addon-knobs/index.ts
>    for (const [key, value] of params) {
Glad to get rid of it 💃

2021-09-21 07:05 UTC, monfera commented on packages/charts/src/chart_types/partition_chart/layout/viewmodel/scenegraph.ts
>      return `${accessorFn(node.dataName)}`;
The function is not much longer than the function name. There's no particular or measurable overhead with it. I originally created the `identity` function but we didn't have a lot of use for it, and I felt an equally long named abstraction for `d => d` plus its noisy imports wasn't worth it. Glad to re-add, lmk

2021-09-21 07:06 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/specs.ts
See detailed comments below, let's discuss this

2021-09-21 07:08 UTC, monfera commented on packages/charts/src/scales/scale_band.test.ts
> +    expect(scale.isValueInDomain((null as unknown) as 'a' | 'b' | 'c' | 'd')).toBe(false);
I agree, `any` is absolutely fine by me in tests, in fact usually better

2021-09-21 07:16 UTC, monfera commented on packages/charts/src/utils/common.test.ts
> -  });
If we keep the util, it can stay ofc. Btw. it's an example that shows how the coverage and boundaries of unit testing are arbitrary. If we use `d => d` inlined (which is a good choice too), it's well understood by the new code reader, without having to jump to a function def. It also needs no test coverage. It's interesting that a somewhat arbitrary choice like whether or not to extract / export a `d => d` leads to a test case 

Over time, it'd be great to thematically collect utilities, such as, in this case, maybe FP utils, that'd live in `packages`, with their tests

2021-09-21 11:05 UTC, markov00 reviewed
Thanks for this great refactoring
I also have some doubts on the required `min`,`max` domain, but I think in Kibana at least, every chart is already consumed with both min and max properties.
We definitely need that API ->to->internals middle-layer to transform API values into an unambiguous extended configuration.

2021-09-21 11:05 UTC, markov00 commented on packages/charts/src/scales/scale_band.ts
> +    this.isInverted = inputDomain.length > 1 && this.domain[0] > this.domain[1]; // fixme: we are assuming that it's ordered
you can make this false by default and fix the domain type to `[T,...T[]]`

2021-09-21 11:52 UTC, monfera commented on packages/charts/src/components/portal/tooltip_portal.tsx
> +  const ps = useMemo(() => mergePartial(base, settings, { mergeOptionalPartialValues: true }), [settings, base]);
This got taken care of via @nickofthyme's suggestion

2021-09-21 12:05 UTC, monfera commented
I blindly assumed the need for past `==`/`!=` indeed it's a good idea to revisit these 😄 
![image](https://user-images.githubusercontent.com/1548516/134167179-22c6d5ce-5c8d-45f9-96fe-5d8a00f060bb.png)

2021-09-21 12:54 UTC, nickofthyme commented on .eslintrc.js
> +    '@typescript-eslint/object-curly-spacing': 0,
No action required here btw, just confirming.

2021-09-21 12:57 UTC, nickofthyme commented on packages/charts/src/chart_types/partition_chart/layout/utils/legend_labels.ts
> +    if (formattedValue && formattedValue !== HIERARCHY_ROOT_KEY) {
> In the change you highlighted here, the type safety is at least as strong as before

before, not shown in the code diff, was checking `key == null`.

> There is value in becoming more runtime-defensive

Agreed

> I also proposed that we wrap around each dependency we use

Agreed

2021-09-21 15:12 UTC, monfera commented on packages/charts/src/chart_types/heatmap/state/selectors/get_legend_items_labels.ts
> +      depth: 0,
Beautiful!

2021-09-21 15:18 UTC, monfera commented on packages/charts/src/utils/domain.ts
> +  const uniqueValues = [...new Set(data.filter((d) => (removeNull ? d !== null : true)))];
Thanks, I should've noticed the `true` in a branch this when inlining `domain`, will merge

2021-09-21 18:27 UTC, monfera commented on integration/page_objects/common.ts
>      }
I looked at it and don't have the courage to tamper with it in this PR, I think @nickofthyme you'd have better intuition about what to do with it

2021-09-21 18:32 UTC, monfera commented on packages/charts/src/chart_types/partition_chart/layout/utils/legend_labels.ts
> +    if (formattedValue && formattedValue !== HIERARCHY_ROOT_KEY) {
| before, not shown in the code diff, was checking key == null.

True! I meant the last quoted line, `formattedValue` as a predicate is at least as strong as `formattedValue != null`

2021-09-21 18:34 UTC, monfera commented on packages/charts/src/scales/scale_band.ts
> +  readonly domain: [T, T, ...T[]];
I'll need to check it, having put that type in b/c of some constraint I encountered that demanded two values at least, might have misunderstood some piece of code

2021-09-21 18:37 UTC, monfera commented on packages/charts/src/scales/scale_band.ts
> +    this.isInverted = inputDomain.length > 1 && this.domain[0] > this.domain[1]; // fixme: we are assuming that it's ordered
Oh this was the place that needed two elements 👯‍♀️  I'll set it to `false` (I think it's then not _by default_ as it can't be overridden, but simply, _always_) and see if the type can be made simpler

2021-09-21 18:40 UTC, monfera commented on packages/charts/src/scales/scale_band.ts
> +    this.isInverted = inputDomain.length > 1 && this.domain[0] > this.domain[1]; // fixme: we are assuming that it's ordered
e53232128d567f1e2b647834a1d32f2a0972b2ff

2021-09-21 19:06 UTC, monfera commented
test this

2021-09-21 22:45 UTC, nickofthyme approved these changes
Latest code changes LGTM! Great work Robert!!

2021-09-22 08:09 UTC, markov00 approved these changes
Great work here Robert, thanks for taking care of this.
I failed miserably the last time I've tried typing the scale, but you did it an awesome job here!

2021-09-22 09:44 UTC, merged