fix(settings): change allowBrushingLastHistogramBucket to true
elastic/elastic-charts pull request #1396
Opened 2021-09-21 16:31 UTC by rshen91

## Summary
This PR changes the default boolean value of allowBrushingLastHIstogramBucket to true instead of false. This setting change more accurately shows the correct value when brushing over the last bucket in a histogram

## Details

## Issues
Closes #1371 

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-09-21 17:31 UTC, nickofthyme commented
> This setting wasn't removed and users are still able to set this to false if they would prefer.

What are your thoughts about removing this setting altogether?

2021-09-22 10:40 UTC, markov00 requested changes
Looking at the changes in the test looks like that we aren't properly using the `allowBrushingLastHistogramBucket` with the required constraint that the series needs to be an Histogram (histogramEnabled=true). Instead it looks like we just forget about that and  we use directly `allowBrushingLastHistogramBucket` in the calculation like
``` 
const maxDomainValue = xScale.domain[1] + (allowBrushingLastHistogramBucket ? xScale.minInterval : 0);
```
This create the issue that is visible in the test: in a simple bar chart, with the current default enabled `allowBrushingLastHistogramBucket` we are changing the behavior of the brush. The scope of the `allowBrushingLastHistogramBucket` should only apply to histograms.

I've noticed the same wrong logic applied to the `roundHistogramBrushValues`
we are rounding brush values also to non histogram based charts.

@nickofthyme it looks like that you added those properties, do you remember the reason why these logics are not strictly applied to histogram only charts?

2021-09-22 18:23 UTC, nickofthyme commented
> @nickofthyme it looks like that you added those properties, do you remember the reason why these logics are not strictly applied to histogram only charts?

@markov00 I think you are correct, that should only apply to histogram mode.

2021-09-23 14:47 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
> +  allowBrushingLastHistogramBin: boolean = true,
Nit: `allowBrushingLastHistogramBin` is a mandatory argument to `getXBrushExtent` which we can tell from the presence of a parameter that's to the right of it, `seriesSpecs`, which is mandatory (no question mark, no default). So wherever `getXBrushExtent` is used, we already pass something for `allowBrushingLastHistogramBin` otherwise the type checkers would shout. So the default value `= true` can be removed, assuming we are not passing the function `undefined` for this param (this is the only case the `true` default value would be in effect). So it's worth revisiting the caller places, and pass `true` instead of `undefined` if we currently pass `undefined` anywhere. 

This is a very small thing that supports the larger theme of type simplicity: it's simpler to have `boolean` than `boolean | undefined`. Union types like this, and optional parameters should preferably be avoided, unless it leads to convoluted code

2021-09-23 15:27 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_brush_end_caller.ts
> +  allowBrushingLastHistogramBin: boolean = true,
This is great thanks! 1f5186a

2021-10-04 14:04 UTC, nickofthyme approved these changes
Code changes LGTM. Tested locally on storybook and looks good. 🎉

2021-10-04 14:04 UTC, nickofthyme commented on storybook/stories/interactions/10a_brush_selection_bar_hist.story.tsx
> +      allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', false)}
nit: maybe we make this the default value

```suggestion
      allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', true)}
```

2021-10-04 14:04 UTC, nickofthyme commented on storybook/stories/interactions/12_brush_time_hist.story.tsx
> +        allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', false)}
nit:

```suggestion
        allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', true)}
```

2021-10-05 14:34 UTC, nickofthyme commented
@rshen91 make sure you note the rename here as a breaking change.

2021-10-05 15:25 UTC, rshen91 commented on storybook/stories/interactions/10a_brush_selection_bar_hist.story.tsx
> +      allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', false)}
Good catch thank you 9ebadbd

2021-10-05 15:25 UTC, rshen91 commented on storybook/stories/interactions/12_brush_time_hist.story.tsx
> +        allowBrushingLastHistogramBin={boolean('allowBrushingLastHistogramBin', false)}
9ebadbd for this fix thank you

2021-10-05 20:20 UTC, monfera commented on packages/charts/src/specs/settings.tsx
> +  allowBrushingLastHistogramBin: boolean;
Nice removal of an optional here 😍 Also, the Bucket -> Bin change 👍

2021-10-06 17:34 UTC, markov00 approved these changes
LGTM!

2021-10-06 17:36 UTC, merged