tmp
elastic/elastic-charts pull request #1410
Opened 2021-09-25 11:58 UTC by monfera

## Summary

## Details

## Issues

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-09-28 19:13 UTC, monfera commented
test this

2021-09-29 19:15 UTC, monfera commented
test this

2021-09-29 23:16 UTC, nickofthyme reviewed
I got through about half of the code changes. So far I like the effort to reduce over-handling selector combiner function arguments.

I am not a fan of the merge partial changes using a separate method as opposed to making the option default. Also not a fan of some of the manual object literal indentations.

I still need to finish reviewing the code before looking at the functionality.

2021-09-29 23:16 UTC, nickofthyme commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
I agree with many of these line reductions for object literals but not every **single** object needs to be a single line.

In this case, and others, the old way is more readable with the long line for spread and type casting. I personally favor multiline for readability and flexibility for adding new properties to the object. Idk why these changes are so prevalent in this PR. I think as a team we should decide what is preferred and if possible add linting to support that way.

Currently we have a "user's discretion" approach to this, in that if you are changing a line and see fit that it be reduced or expanded make that change. But to have manual code changes to this effect on otherwise untouched code seems a bit much to me.

2021-09-29 23:16 UTC, nickofthyme commented on packages/charts/src/utils/bbox/canvas_text_bbox_calculator.ts
> +    ? (text: string, padding: number, fontSize, fontFamily, lineHeight = 1, fontWeight = 400) => {
👍🏼 should any of these be optional? It seems this could produce bad measurements if any of these are optionals.

2021-09-29 23:16 UTC, nickofthyme commented on packages/charts/src/utils/common.test.ts
>        });
These test should be for the base method alone not off an options wrapper.

2021-09-30 05:37 UTC, monfera commented
Thanks Nick! 

> I am not a fan of the merge partial changes using a separate method as opposed to making the option default

This is how it had been already 👍 

> not a fan of some of the manual object literal indentations

I'd like to learn more about how y'all read code, as I have the contrary feeling with vertically expansive literals while doing code reading. `prettier` certainly prioritizes a vertical layout and it "waters up" bits of code, good to know it's actually liked by some of us

2021-09-30 05:43 UTC, monfera commented on docs/1-Typesofchart/0-Bar.mdx
> +    <Axis id={'bottom'} position={Position.Bottom} title={'Bottom axis'} ticksForCulledLabels={true} />
While maybe we could settle with `showTicksForCulledLabels`, I'm planning to switch back to the slight misnomer `showOverlappingTicks` in this PR because the work on ensuring no duplicate tick labels, and the variable raster of the time axis work obsolete the entire approach of post-hoc overlap based tick rarification

2021-09-30 05:46 UTC, monfera commented on packages/charts/src/chart_types/goal_chart/state/selectors/scenegraph.ts
>  });
I agree, would be great to tweak the linter such that it's not as wasteful with the vertical space, afterall our code is also not single token / single operator per line. Do you know of such an option, outside of this PR ofc.?

2021-09-30 05:53 UTC, monfera commented on packages/charts/src/utils/common.tsx
> +function mergePartialWithOptions<T>(
My intent with the surface change was to remove code noise at 100+ usage places (all the option objects made code harder to read for me). A small follow-up PR could rework `mergePartialWithOptions` in line with your call, once some of us gets around to doing this. I also wasn't sure if it's cleanroom code or derived from OS code, and if we'll ever need the `false` option and the option should be kept around, or the option param can be removed altogether. I suggest, separate small PR for this

2021-09-30 05:56 UTC, monfera commented on packages/charts/src/state/types.ts
> +  title: string;
Code uniformity, esp. in a domain that's not too demanding w.r.t. to adding or not adding a `title`. Optionals are in effect union types, and union types tend to bifurcate code path and our thought paths when reading the code 😄  Optionals should be used sparingly (worth its own brainstorming when the other team members are back).

Having said this, I feel conflicted over having debug code in our production code to begin with, while I recognize the attraction

2021-09-30 05:59 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/legend/legend.ts
> +  const legendSortFn = getLegendCompareFn(void 0, (a, b) => {
Thanks for the catch, it was going to be a placeholder that unduly survived, I'll remove this and the two others

2021-09-30 06:01 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
I thought that was a joke, in a fixing commit I can prefix with an `obtain` or `figureOut` or something 😄

2021-09-30 06:03 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/rendering/area.ts
> +    .x(({ x }) => (xScale.scale(x) ?? NaN) - xScaleOffset)
Good catch, indeed now that this thing not only doesn't throw but also doesn't yield `null` or `undefined`, there's no need for nullish coalescing here (`.scale()` will return an `NaN`), so I'll remove the `?? NaN` here

2021-09-30 06:08 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +        title: title ?? '',
Just type uniformity for internal simplicity (as in code, and in our minds). It'd be a more spiritual discussion but I feel like there's a higher threshold for what's a distracting level of code noise for those that have been living and breathing our Cartesians for years, vs. someone relatively new to these parts of the code, I regularly feel overpowered and hindered by the compounding variabililty of things like types and assignments (`let`). 

So mine may be just a more precarious "new code reader" perspective

2021-09-30 06:09 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts
> +  const tooltipSortFn = getTooltipCompareFn(void 0, (a, b) => {
Thanks, again it was meant to be temporary, and I used `void 0` so it sticks out like a sore thumb. It worked, right? 😄 Will remove this thing

2021-09-30 06:12 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
> +  pos: Position,
I can change it back, including the places where the var is used 😄 Though this function further changes in the follow-up PR so I might not induce an unrewarding rebase merge conflict just b/c of an internal param name. So let's not set this to resolved

2021-09-30 06:20 UTC, monfera commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
I agree it should be discussed, as there has been no guidance or consensus on this before. I don't feel super keen on reverting such changes in this specific PR, mostly as we've more urgent things to do. Knowing your preferences I'll refrain from such changes in future PRs until we reach consensus (99% of the literals are still your way now)

Btw. I also agree that here specifically, it wasn't bad before, esp. because of the long assertion. When we chat, I'm glad to share why, on a drive-by basis, I converted some of these to a one-liner. On a side note, maybe `mocks` shouldn't even be under `src`

2021-09-30 06:21 UTC, monfera commented on packages/charts/src/utils/bbox/canvas_text_bbox_calculator.ts
> +    ? (text: string, padding: number, fontSize, fontFamily, lineHeight = 1, fontWeight = 400) => {
Yes I was thinking about removing the line height and font weight optionality too, let's do it in a next PR

2021-09-30 06:30 UTC, monfera commented on packages/charts/src/utils/common.test.ts
>        });
Not sure if I understand, or if I understand, whether I'm aligned with this notion. Though it's an internal utility, I don't see particular value in testing the internals of _that_, vs. testing the de facto API (which is `mergePartial`). Because, in the case of the former, we can alter the implementation detail behind `mergePartial`, or even, roll a node dependency and wrap that with `mergePartial` and the test case would still remain valid. I prefer testing an internal API (used in 100s of places in our code) over testing _how_ it does its thing, so our code remains malleable and tests  are stabler. 

Do you have a differing perspective, or have I misunderstood your comment?

2021-09-30 08:07 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/rendering/utils.ts
> +  return (yValue: number) => domainPolarity === Math.sign(yValue);
I might have started with De Morgan's laws or intuitive understanding, I don't recall

The original predicate said, "it's not true that domainPol is up and yValue is down or the other way around"
The new predicate states the gist of it (not 100% identical) more simply, "domainPol and yValue are on the same side of the zero line"

2021-09-30 13:45 UTC, nickofthyme commented on docs/1-Typesofchart/0-Bar.mdx
> +    <Axis id={'bottom'} position={Position.Bottom} title={'Bottom axis'} ticksForCulledLabels={true} />
Ok I think `showTicksForCulledLabels` is good

2021-09-30 13:48 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/state/selectors/scenegraph.ts
>  });
Yeah I think `@typescript-eslint/indent` is the best solution but it's still being ironed out. https://github.com/typescript-eslint/typescript-eslint/issues/1824. Otherwise I think prettier indenting is horrible.

2021-09-30 13:50 UTC, nickofthyme commented on packages/charts/src/utils/common.tsx
> +function mergePartialWithOptions<T>(
I would like to fix this in this PR I really don't like these changes. I'll add a commit if that's ok with you.

2021-09-30 14:01 UTC, nickofthyme commented on packages/charts/src/state/types.ts
> +  title: string;
Yeah to some degree that is true but optionals are a fact of life, we cannot simply require everything to have a value. At the same time changing these one off cases is just splitting hairs and not effecting overall performance at all. And even more this creates unnecessary breaking functional tests in kibana.

I agree it's not ideal to have this debug code in src and I have discuss with Marco about creating a separate versioned package (i.e. `@elastic/charts@33.0.0-debug`) that contains verbose warnings and debug helpers and the normal package would be stripped of all this code. I'm not exactly sure how this would work but I think it's possible. I discuss this a bit here https://github.com/elastic/elastic-charts/issues/379.

> The library would have a “prod” version of the library the strips all comments and helper warnings and optimize the size of the final bundle. I'm thinking some webpack plugin that can remove code like.

2021-09-30 14:08 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
No we have had this discussion before with @markov00. This _function_, keyword _function_, gets, computes or otherwise obtains `tickLabelPosition`, it in itself is **NOT** the `tickLabelPosition`. This creates undo confusion, functions take action unless it's wrapped in an IIFE, also not ideal.

> it's a best practice to actually tell what the function is doing by giving the function name a verb as prefix. [link](https://www.robinwieruch.de/javascript-naming-conventions)

2021-09-30 14:10 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/rendering/utils.ts
> +  return (yValue: number) => domainPolarity === Math.sign(yValue);
Cool, thanks!

2021-09-30 14:12 UTC, nickofthyme commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
> I don't feel super keen on reverting such changes in this specific PR, mostly as we've more urgent things to do

Yeah no need for that I just want to open this up for discussion and like I said in a previous comment, `@typescript-eslint/indent` is the best solution but not ready quite yet.

2021-09-30 14:19 UTC, nickofthyme commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
> On a side note, maybe mocks shouldn't even be under src

Where would it go? I think this is fine just like jest uses `__mocks__` relative to each directory. This directory is excluded from the final bundle.

Also placing this outside of src would cause more problems like how to access the src that it likely depends on, so now we have to link charts to the mocks directory assuming mocks is independent and cannot stick its hand into the src cookie jar. What would be your solution?

2021-09-30 14:34 UTC, nickofthyme commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
Maybe we just have files next to their respective mock like `specs.mock.ts`

2021-09-30 14:37 UTC, nickofthyme commented on packages/charts/src/utils/bbox/canvas_text_bbox_calculator.ts
> +    ? (text: string, padding: number, fontSize, fontFamily, lineHeight = 1, fontWeight = 400) => {
Yeah another PR is fine, if there is a canvas default we should use that but if there is an implicit default such that providing an `undefined` value set the `fontWeight` to `400` that is preferable in my view. That way it's as if you used canvas directly without unknown properties being set.

2021-09-30 14:46 UTC, monfera commented on packages/charts/src/utils/common.tsx
> +function mergePartialWithOptions<T>(
Thanks, fine with me, if it only impacts this `common.tsx` (hmm why not `ts`) and test files, but doesn't cause a change to all the dozens of places where `mergePartial` is currently used. If my understanding of what you plan is incorrect, let's chat

2021-09-30 14:53 UTC, monfera commented on packages/charts/src/state/types.ts
> +  title: string;
Good to know it causes issues in Kibana, glad to restore the `?`. Worth having an eventual discussion about the pros&cons of ternaries, of which this is a kind, esp. in settings where there's no real benefit to the union type. My drive is not as superficial as "spitting hairs" implies, optionals are a fairly troublesome fare

2021-09-30 15:04 UTC, nickofthyme commented on storybook/stories/utils/formatters.ts
> +  const baseLabel = base === Math.E ? 'e' : base;
Will the precision here possibly cause `Math.E === Math.E` to be `false`?

2021-09-30 15:05 UTC, monfera commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
>  What would be your solution?

I'd have the IDE move the file outside `src` and it'll rewire the import links, might try it at some point, and consider moving the "unit" test files with them. It's unrelated to the PR, just wanted to share it's more of a wish than a plan. It seems beneficial to have "real" code only in `src` and nothing else. For example, some tools, like an inspector for superfluous exports may work better if the production code has clearer boundaries. Or grepping for stuff. Sure, often a workaround exists, like exclude file names based on a pattern, but these options are more uneven and haphazard than a simple directory delineation

2021-09-30 15:06 UTC, monfera commented on packages/charts/src/utils/bbox/canvas_text_bbox_calculator.ts
> +    ? (text: string, padding: number, fontSize, fontFamily, lineHeight = 1, fontWeight = 400) => {
I'm with you on the topic of optionals removal 😄 and let's leave this feedback unresolved until I link it to an issue or PR

2021-09-30 15:10 UTC, monfera commented on packages/charts/src/utils/common.test.ts
>        });
Thanks, as long as it touches the approx. two files `common.tsx` and `common.test.ts`, otherwise let's chat before you sink time into it so I can understand. Btw. I don't even understand the overall point, because at another place, what you argued for is that instead of doing the wrapper thing now in the PR, you just knife that option object altogether, and change the signature and recursion of the "real" function. With that, I don't see why you want to change the test, and why you want to test it with choices we no longer use (in fact, remove)

2021-09-30 15:11 UTC, nickofthyme commented on packages/charts/src/state/types.ts
> +  title: string;
Yeah I'm fine discussing this too! I just don't see a performance benefit to removing optional types that outweighs the implications of requiring such values.

2021-09-30 15:13 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +        title: title ?? '',
https://github.com/elastic/elastic-charts/pull/1410#discussion_r718922220

2021-09-30 15:38 UTC, nickofthyme commented on packages/charts/src/utils/common.test.ts
>        });
True there are two ideas at play:

1. Wrapping a function just for the sake of applying default options. I don't like this because it is just as easy to change the default option value from `false` to `true`.
2. IF the above were used it would make sense to test the function that is being wrapped for all the test cases, NOT the wrapped function.

See changes f9374ee

2021-09-30 15:44 UTC, nickofthyme reviewed
Ok here are the changes I would like to keep. The tests still pass with `mergeOptionalPartialValues` now `true` because that is the conservative case. We should add tests to check for `mergeOptionalPartialValues` is `true`.

2021-09-30 15:44 UTC, nickofthyme commented on packages/charts/src/mocks/geometries.ts
> +    return mergePartial<PointGeometry>(MockPointGeometry.base, partial, {}, [{ style }]);
This is not ideal but for the time being I think this is fine as it is not a common usage. We may want to swap the 3rd and 4rd args if this is desirable or possible accept and array of additional values in the 2nd arg.

2021-09-30 15:44 UTC, nickofthyme commented on packages/charts/src/utils/common.test.ts
> +    describe('Maps', () => {
I prefer to keep these tests if and until we decide to remove the map logic.

2021-09-30 15:44 UTC, nickofthyme commented on packages/charts/src/utils/common.test.ts
> +        });
These tests still apply

2021-09-30 15:44 UTC, nickofthyme commented on packages/charts/src/utils/common.tsx
> +export function mergePartial<T>(
I like to keep docs like this that give more detail to the params that are required

2021-09-30 16:06 UTC, nickofthyme commented on storybook/stories/utils/formatters.ts
> +  const baseLabel = base === Math.E ? 'e' : base;
Great yeah was just curious, Thanks!

2021-09-30 19:36 UTC, monfera commented on packages/charts/src/state/types.ts
> +  title: string;
Agree, I don't see or claim any performance benefit for most conversions from the removal of optionals (or union types to homogenous types in general, except in hot loop cases like using the scale with lots of data)

So it's only about avoiding extra code paths, ifs, checks, early bails etc. when some parameter can be odd. For example I really like how Flutter migrated to non-nullability by default. The ifs, checks and code paths add not only the potential of the CPU execution pipeline flushing (which is not my concern here) and payload (minor) but importantly, they often require extra attention from the code reader. Think of an adder function that works with two `number`s vs. one that has optional `number`s. The code is multiple times as long. Lesser relative differences, but at lots of places occur in Charts too, so I guess over 10% of our code mostly just disentangles the fallout of optionals and union types

One more thing, optionals and union types tightly bind us to JavaScript. I see a future where much of our actual logic runs in WASM, and most static languages aren't as fond of union types (if possible at all) as the historically VERY lax JavaScript, and the slightly less lax TypeScript that wanted to match JS usage patterns. There are some other reasons like this too, let's circle back to it

2021-09-30 20:05 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
I respect the majority opinion, with the minority vote as a nod toward functional programming. Ie. the opposite outcome, precisely for the reason you quote, seen as a benefit not a drawback 😄  For a key tenet of FP is the equivalence between a _value_ (that you eg. name as a noun) and an expression that yields the same. The expression, when abstracted out, has a name. Example:

```
const apples = [{ color: red, radius: 3}, { color: green, radius: 4}]
const puree = apples.reduce(blend)
```
can be equivalent with, if eg. you parametrize it for more general cases:
```
const apples = (...) => ...
const puree = apples({count: 2, colors: 'mix', minSize: 3, maxSize: 4}).reduce(blend)
```

A deeper intuition is that in _imperative_ programming, the focus is on the _how_, so it's verb based (do this, emit that, calculate that etc.) while in declarative programming, and within it, FP, the focus is on denotation, values, expressions, composability 

Using `get`, `compute` prefixes etc. is a bit like the comp sci version of 3D pie charts, fine, or appealing for some and worrisome for others

I'm OK using distinct names to avoid the 

```
const apples = apples({count: 2, colors: 'mix', minSize: 3, maxSize: 4})
const puree = apples.reduce(blend) // won't work ofc.
```
and `get` technically gets the job done, via [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) (`get` marks a cheap/simple function, `calculate` marks an arbitrarily less cheap one, this PR removes one such duplication):
```
const apples = getApples({count: 2, colors: 'mix', minSize: 3, maxSize: 4})
const puree = apples.reduce(blend)
```
Hungarian notation fell out of favor. On personal projects, I like more descriptive names that are nouns (FP) not verbs (imperative programming), eg.
```
const ingredients = appleSortiment({count: 2, colors: 'mix', minSize: 3, maxSize: 4})
const puree = ingredients.reduce(blend)
```
So let's continue with `get`/`compute` but now I explained why I assumed the stated need for a verb was a joke. Other folks have diverse arguments for nouns even outside the FP style, like [here](https://www.grinchcentral.com/function-names-to-verb-or-not-to-verb) or [here](https://medium.com/swlh/an-opinionated-guide-to-naming-your-code-aimed-at-new-developers-6f769d60e098):

![image](https://user-images.githubusercontent.com/1548516/135521962-5835040f-f831-4162-a41b-e8946fe61638.png)

2021-09-30 20:06 UTC, monfera commented on packages/charts/src/mocks/series/series.ts
> +    return { ...(MockDataSeriesDatum.simple(datum) as WithIndex<FullDataSeriesDatum>), fittingIndex };
Thanks, you have more insight on the pros/cons, sounds good to me

2021-09-30 20:07 UTC, monfera commented on packages/charts/src/utils/common.test.ts
>        });
Thanks for the commits Nick

2021-09-30 20:08 UTC, monfera commented on packages/charts/src/utils/common.test.ts
> +    describe('Maps', () => {
Sounds fine by me if you see a use for them

2021-09-30 20:25 UTC, nickofthyme reviewed
Ok I've gone through all the code changes with the exceptions of the `scale_continuous.ts`. I need to dig a little deeper into that file and start playing around with storybook.

2021-09-30 20:25 UTC, nickofthyme commented on packages/charts/src/scales/scale_continuous.ts
> +  const orderedDomain: [number, number] = inverted ? [domain[1], domain[0]] : domain;
nit

```suggestion
  const orderedDomain: [min: number, max: number] = inverted ? [domain[1], domain[0]] : domain;
```

2021-09-30 20:25 UTC, nickofthyme commented on packages/charts/src/scales/scale_continuous.ts
> +  ScaleContinuousNumeric,
In the future can we avoid moving around variable and function declarations on such a large file refactor?

git cannot decern what was moved here or there and it makes it so difficult to review the code 1:1 with the previous code. I reverted this back for now but even if the shuffle is after it's been reviewed that's fine but reviewing mixed up files like this in a 1k plus line PR is super tiring to my eyes. 😵

2021-09-30 20:51 UTC, nickofthyme commented on packages/charts/src/state/types.ts
> +  title: string;
Ok those are all fair points but to compare this to Dart `2.9`'s null safety is a little misleading. Dart before null safety would not error on `null` values being passed to non-null types. But now with null safety it does, this is more inline with typescript that would enforce non-null values statically.

```dart
int add(int n1, int n2) {
  return n1 + n2;
}

void main() {
  add(1, null); // no compile error pre 2.9
}
```

![image](https://user-images.githubusercontent.com/19007109/135526963-655abc0e-e593-4a6e-b236-406a84fb8ccb.png)

Dart also allows optional parameters

```dart
void printName(String firstName, {String? lastName}) {
  print('$firstName ${lastName ?? ''}');
}

void main() {
  printName('Nick');
}
```

---

I agree we may see a future of a different runtime than javascript and when that time comes we can make the necessary changes to leverage any advantages in performance.

All I am saying is that right now optional values should not be frowned upon or reduced for the sake of performance. Yes javascript can optimize a function such as `add(n1: number, n2: number)` to be smaller and faster than `add(n1: number, n2?: number)`. This is what I meant by splitting hairs.

The caveat to this is replacing `null` with `NaN`, and maybe others, because that not only removes the union but flows so much nicer into canvas and numerical calculations.

2021-09-30 21:02 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
> `const puree = apples.reduce(blend)`

🤣 

I have no FP experience so I'll take your word on that and from a cursory perspective it does seem as though it could make sense. One of you links show a swift [link](https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)).

> - _Those without side-effects should read as noun phrases, e.g. x.distance(to: y), i.successor()._
> - _Those with side-effects should read as imperative verb phrases, e.g., print(x), x.sort(), x.append(y)._

Though I notice that all these namings pertain more to methods on classes than standalone functions.

If we switch to a LISP, god forbid, I'll be happy to conform with their naming styles.

2021-09-30 21:09 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_over_caller.ts
>  }
I think it's the inlined bulk in the `every`, and the slightly longwinded names rather than the simple boolean expression (one `&&` and one `||`) which is at least matched by, or worse with the preexisting `if/return` hell (not hell at two layers ofc. but it's like the famous callback hell w/ the nesting)

This preserves 
- the single exit point, which is good in such uncomplicated cases
- no imperative branching ladder/tree
- declarative expression over mentally tracing code execution steps
- brevity (which also hints at the simplicity that we have here for the actual logic)

```
  const match = ({ value: next }, index) => {
    const prev = prevGeoms[index].value;
    return prev.x === next.x && prev.y === next.y && prev.accessor === next.accessor;
  };
  return nextGeoms.length > 0 && (nextGeoms.length !== prevGeoms.length || !nextGeoms.every(match));
```
or with a destructuring assignment, and pivoting from the needless former `!every` to `some`:
```
  const differs = ({ value: next }, index) => {
    const { x, y, accessor } = prevGeoms[index].value;
    return x !== next.x || y !== next.y || accessor !== next.accessor;
  };
  return nextGeoms.length > 0 && (nextGeoms.length !== prevGeoms.length || nextGeoms.some(differs));
```
I like you commented here as it made me consider all these other avenues which I didn't spend time on

2021-09-30 21:18 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_over_caller.ts
>  }
I also wonder if we should enable the very widespread idiom
```
return nextGeoms.length && (nextGeoms.length !== prevGeoms.length || nextGeoms.some(differs));
```
Forcing a `> 0` mostly buys clarity for rank beginner JS coders unfamiliar with both the truthiness/falsiness of numbers (common in other languages too) and the length check idiom propagated by lots of libraries

2021-09-30 21:19 UTC, nickofthyme commented on packages/charts/src/state/types.ts
> +  title: string;
Swift also has a nice way of handling `Optionals`

```swift
func testFunction() {
  let someValue:Int? = 5
  guard let temp = someValue else {
    return
  }
  print(temp)
}
```

2021-09-30 21:32 UTC, nickofthyme commented on packages/charts/src/state/types.ts
> +  title: string;
And then there is `scala` type `Option`als 🤮 

```scala
def toInt(s: String): Option[Int] = {
    try {
        Some(Integer.parseInt(s.trim))
    } catch {
        case e: Exception => None
    }
}
```

2021-09-30 21:33 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
While I generally agree that in such cases, it may be sensible to extract out and name some subexpression (like `isFiltered` was here), I respectfully disagree specifically at this snippet

- one `&&` and one `||` is simpler than all that convoluted stuff with the boolean literals and much higher count of operators
- we should have a linter rule that prohibits `true` and `false` outcomes in ternaries, it's an anti-pattern (predicates already yield booleans) and the linter rule would already balk at the not one but two(!) boolean literals in conditional outcomes, it's bad practice, like saying, `const tall = heightFt > 6 ? true : false` rather than `const tall = height > 6` (or one-sided similar stuff) 
- the `isFiltered` word is ambiguous, at least to most ESL speakers, not sure if it's clear to native speakers: does it mean the rejected part or the kept part? So extracting out already wasn't informative
- the verbose `thing !== undefined` isn't more meaningful than `!thing` but... more verbose 😄  I prefer not to have code noise 

However again it's useful to reconsider, maybe `str === ''` is better than `str.length === 0` or some such, or even, 
```
  const isKept = !spec.filterSeriesInTooltip || spec.filterSeriesInTooltip(seriesIdentifier);
  const isVisible = label && isKept;
```
I think it's fine to expect future Charts contributors to be familar with, or able to learn oft used JS semantics like `''` is falsey (but `label !== ''` is of course good too

2021-09-30 21:36 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
Also, you mentioned ternaries here, where I _got rid of_ the preexisting ternary, where is the pat on the back? 🤣

2021-09-30 21:39 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_out_caller.ts
> +  nextProps.highlightedGeometries.length === 0;
LGTM, just don't want to click while you might commit, or if it needs some other touch-up, pls. click the Commit suggestion at an opportune time

2021-09-30 21:49 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
Good find! Yes, maybe the method examples are because these languages are often used with objects, as there doesn't appear to be a cause for a naming convention difference otherwise. It'd feel odd to have a different convention just b/c one is attached to an entity and the other isn't. Turning a method to a function would involve a grammar exercise 😄

2021-09-30 21:52 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/dimensions.ts
> +  smSpecs: SmallMultiplesSpec[] = [],
I'll need to check it, though the small multiples tests pass too. So let's not commit it yet, partly b/c this specific function has since been significantly altered

2021-09-30 21:53 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/dimensions.ts
> +  const smSpec = smSpecs && smSpecs[0];
I'll double check this too (if I understand, you suggest a line deletion here, not replacement)

2021-09-30 21:57 UTC, monfera commented on packages/charts/src/scales/scale_continuous.ts
> +  ScaleContinuousNumeric,
Good point about the difficulty if many things change, let's discuss how and what I can do to make significant changes easier to review, a point for the Monday weekly

> I reverted this back for now

Not sure what you mean by this

2021-09-30 22:07 UTC, monfera commented on packages/charts/src/state/types.ts
> +  title: string;
Good point about Dart, and I shouldn't have cited it also b/c my point about possible non-JS code bits would be relevant for languges that properly and compactly compile to WASM, such as Rust, C or C++. These lower level languages dedicate space for the entire union (if I understand correctly) and there are some caveats, memory safety concerns etc. with certain uses. While I'm no Rust or C++ expert, I wrote some C and C++ before, with my limited knowledge, and type simplicity like simple structs, and simple numerical arrays are simpler, more efficient and easier to figure out. While I'd be comfortable writing low level code over simple data structures, it'd be a needless hurdle to need to figure out unions inside Rust, or some awkward class-based equivalents in C++, not to mention the JS/WASM boundary. It's easier to transfer object ownership of numerical arrays than complex types

2021-09-30 22:18 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_out_caller.ts
> +  nextProps.highlightedGeometries.length === 0;
I'm done committing sorry 😅

2021-09-30 22:20 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_over_caller.ts
>  }
I prefer the verbose equality checks cuz my brain it's two steps. Length is `0`, zero is `false` therefore if length is `0` then true. But I can suffer for the greater good if others don't care.

2021-09-30 22:23 UTC, nickofthyme commented on packages/charts/src/scales/scale_continuous.ts
> +  ScaleContinuousNumeric,
> > I reverted this back for now
>
> Not sure what you mean by this

I reverted your shuffling of the existing code pieces in `scale_continuous.ts`. All the logic is the same but the methods are now in the same order making it easier to see the code diff 1:1.

2021-09-30 22:23 UTC, nickofthyme commented on packages/charts/src/scales/scale_continuous.ts
> +  ScaleContinuousNumeric,
252b94d

2021-09-30 22:38 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
As you pondered the idea of an eslint rule for preventing `true`/`false` yesterday, and I liked the idea a lot, I just did a quick search and only found this [rule](https://eslint.org/docs/rules/no-unneeded-ternary) which covers the dual boolean case only, both outcomes are boolean literals. There might not be a rule for a single-path literal

2021-10-01 00:14 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
Yeah that was probably it. There must be a better lint rule but a quick search show nothing promising. 😢

2021-10-01 00:17 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
> Also, you mentioned ternaries here, where I got rid of the preexisting ternary, where is the pat on the back? 🤣

You surprised me! I thought it would have ended in a quad-nested (:negative_squared_cross_mark: :four:) ternary!

2021-10-01 10:21 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_element_over_caller.ts
>  }
If the numeric zero check helps, let's stick to it, the expense is just one add'l operator

2021-10-01 10:31 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
It'd be great to herd upstream and resolve special cases and user convenience options (like an API padding config via a single number  vs. a windrose object) so the inner code environment is not conducive for the growth of compound branching, whether `if` or ternary 🌳

2021-10-01 10:36 UTC, monfera commented on packages/charts/src/scales/scale_continuous.ts
> +  ScaleContinuousNumeric,
Indeed, much easier to compare the things side by side 🎉

2021-10-01 15:32 UTC, markov00 reviewed
LGTM, really a lot of changes, but I see the benefits on returning always a number from the scales and all the clean up makes a lot of sense!
Thanks Robert for gardening our code so well

![image](https://user-images.githubusercontent.com/1421091/135647355-bfacd599-b1b4-4b44-bc62-b045cd554832.png)

2021-10-01 15:32 UTC, markov00 commented on packages/charts/src/scales/scale_continuous.ts
> +  private readonly inverseProject: (d: number) => number | Date;
Are we returning a Date? isn't better to return only numbers (timestamps in case for date)?

2021-10-01 17:09 UTC, monfera commented on packages/charts/src/scales/scale_continuous.ts
> +  private readonly inverseProject: (d: number) => number | Date;
It's a private method that just wraps the D3 scale function, and the latter can yield `Date`, so it's not like I wanted to add it to the signature, I just had to. Why did I create
```
this.project = (d: number) => d3Scale(d);
this.inverseProject = (d: number) => d3Scale.invert(d);
```
to begin with, since they are used at one or two places each? B/c my goal was to _not_ persist the entire D3 scale object as `Scale` member, just the necessary two projections. This helps tightly control what can even access the D3 scale object. Before the change, any method in `Scale` had direct and full access to the D3 scale object via `this.d3Scale`, now none of them do. 

I can coerce/convert the value to a number but I wanted to retain these lines as one-liner shallow things, can do it if you want that

2021-10-01 17:26 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
> +  const seriesSortFn = getRenderingCompareFn(void 0, (a: SeriesIdentifier, b: SeriesIdentifier) => {
or enable `no-void` eslint rule

2021-10-04 07:49 UTC, markov00 approved these changes

2021-10-04 13:47 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/tooltip/tooltip.ts
>    const value = isHeader ? x : y;
Yes totally! And I really like that idea of number or object padding, margin, etc.

2021-10-04 13:50 UTC, nickofthyme requested changes
Still waiting on some file changes, lmk when you want me to take a look.

2021-10-05 10:27 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
> +  const seriesSortFn = getRenderingCompareFn(void 0, (a: SeriesIdentifier, b: SeriesIdentifier) => {
As there was no current demand for retaining `sortSeriesBy`, its removal got completed: the `void 0`s are removed altogether f2f27e96a1dad8bce092bb5465eaf4edd6b49ed8

2021-10-05 10:32 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
> +  const seriesSortFn = getRenderingCompareFn(void 0, (a: SeriesIdentifier, b: SeriesIdentifier) => {
Added ec90371f78cc815438825cef3553e942386a13aa which turns voids into warnings. It's legit JS and there's no fundamental reason for avoiding it, other than maybe uniform greppability, which isn't very valuable as `undefined` values can legitimately generated in all kinds of ways like optionals, so not sure when we'd grep for `undefined`. So, on the fence about discouraging perfectly good JS

2021-10-05 10:44 UTC, monfera commented on docs/1-Typesofchart/0-Bar.mdx
> +    <Axis id={'bottom'} position={Position.Bottom} title={'Bottom axis'} ticksForCulledLabels={true} />
Commit 9b9dea6a846d281c3dd40c7affdb01121706032b reverts the name change change, my reason is directly above

2021-10-05 11:08 UTC, monfera commented on packages/charts/src/state/types.ts
> +  title: string;
Reverted the optionality removal to avoid having to change library user code 4ba73bb4827ac22c968be2a84778e27d495caafc

2021-10-05 11:12 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
I added a `get` at the beginning for now, as we have so much of these anyway, and let's continue the discussion for verb vs not, Hungarian notation vs not for all the functions 6fe5921b71a5d39e46c4bb916f98e2769b012dd8

2021-10-05 11:35 UTC, monfera commented on packages/charts/src/chart_types/heatmap/state/selectors/get_x_axis_right_overflow.ts
> +        ) / 2;
Looks like the same thing, but this change would add a bunch of new lines for no reason other than prettier line breaking rules, so skipping it if it's OK. My original intent was to divide once, at the end, rather than in the loop

2021-10-05 11:38 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
> +    !isSameEventValue(prevPointerEvent, nextPointerEvent, changeTrigger));
Beautiful! I originally grepped for `? true`, `: false` etc. and I should've done it for `return true` etc. too. Though even with this there are a few dozen occurrences like this, nice set of changes for a future PR

2021-10-05 11:40 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
> +    !isSameEventValue(prevPointerEvent, nextPointerEvent, changeTrigger));
GH balks even after I refreshed, I'll need to do it manually
![image](https://user-images.githubusercontent.com/1548516/136015887-f275126d-0558-45a3-8151-590d344db4ae.png)

2021-10-05 11:49 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
> +    !isSameEventValue(prevPointerEvent, nextPointerEvent, changeTrigger));
Apologies I was apparently mostly praising my own change, and  the way you highlighted the code block was the reason why it didn't allow the committing of your suggestion. I'll apply your further shortening (1st row) and the var name shortenings

2021-10-05 11:56 UTC, monfera commented on packages/charts/src/chart_types/xy_chart/state/selectors/on_pointer_move_caller.ts
> +    !isSameEventValue(prevPointerEvent, nextPointerEvent, changeTrigger));
Done in 50269bedb5d7f972ed2840926d2a43afcc784776 with credit added by hand, it yielded a nice further shortening

2021-10-05 12:00 UTC, monfera commented
Pls let's preformat our suggestions in our IDE, otherwise our hypersensitive CI will yield a bunch of big red crosses due to a couple of spaces 🤣 Also, we get the "red card" for incomplete test runs, which is awkward, b/c it disincentivizes the otherwise normal process of applying suggestions one after the other, such that there's no time for CO to complete

2021-10-05 12:05 UTC, monfera commented
I ended up reverting the "chore: untangle continuous scales file" commit, because it has served its purpose (allowing side by side comparison) and I'd like to avoid merge conflicts in that code. Also, the new order is I think more in line with what Cartesian code seems to follow, which is, put the main thing (class or function) atop, and place most utilities and nuisance bits (looking at you, loong type description) below

2021-10-05 13:49 UTC, nickofthyme approved these changes
New changes LGTM.

2021-10-05 13:52 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/utils/utils.ts
> +  const seriesSortFn = getRenderingCompareFn(void 0, (a: SeriesIdentifier, b: SeriesIdentifier) => {
The idea to me is to prevent uncommon javascript syntax, so when 3rd party contributions come in they are not confused. I bet you 1 in 5 javascript engineers know what `void 0` is. `If` statements are also perfectly fine JS but yet this PR removes dozens 😉, just saying....

2021-10-05 13:58 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
>    { tickLine, tickLabel }: AxisStyle,
This is a tough one because I don't feel this is good JAVASCRIPT best practices. If it comes up again every 3 weeks it will start to get distracting. Until we switch to some other language I don't think is a legitimate concern. Even if we somehow all agree to this we will have to account for dozens of naming collisions (i.e. `const tickLabelPosition = tickLabelPosition()`) and implement it throughout the library consistently.

2021-10-05 14:05 UTC, merged

2021-10-05 14:30 UTC, monfera commented
Thanks, just saw your reply, let's figure out something over time, as for
every verbified function we also have maybe significant or even several
non-verbed ones

On Tue, 5 Oct 2021 at 15:59, Nick Partridge ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In packages/charts/src/chart_types/xy_chart/utils/axis_utils.ts
> <https://github.com/elastic/elastic-charts/pull/1410#discussion_r722270727>
> :
>
> > +/** @internal */
> +export function tickLabelPosition(
>    { tickLine, tickLabel }: AxisStyle,
>
> This is a tough one because I don't feel this is good JAVASCRIPT best
> practices. If it comes up again every 3 weeks it will start to get
> distracting. Until we switch to some other language I don't think is a
> legitimate concern. Even if we somehow all agree to this we will have to
> account for dozens of naming collisions (i.e. const tickLabelPosition =
> tickLabelPosition()) and implement it throughout the library consistently.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elastic-charts/pull/1410#discussion_r722270727>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAL2BZCQJYVKNJ67AHFR55TUFMAC5ANCNFSM5EXRGELQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>