feat(annotations): add annotations to DebugState
elastic/elastic-charts pull request #1434
Opened 2021-10-18 21:20 UTC by rshen91

## Summary
Annotations are now added to debugState. 

## Details
The `DebugStateAnnotations` interface includes a data attribute which ultimately takes in an any type. I would like to restrict this if possible but it's from the dataValues off the LineAnnotationSpec or RectAnnotationSpec. 

## Issues
Closes #1260 

### Checklist

- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] New public API exports have been added to `packages/charts/src/index.ts`

2021-11-01 15:58 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +      ? annotationDebugState.push({
if you are using a map, you don't need to `push`into an array. The output of the map already produce an array of the returned element from the map callback

2021-11-01 15:58 UTC, markov00 commented on packages/charts/src/state/types.ts
> +  data?: any;
can you please describe the API extractor failure?

2021-11-01 16:25 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +      ? annotationDebugState.push({
Thank you! 4c92ed4

2021-11-01 16:30 UTC, rshen91 commented on packages/charts/src/state/types.ts
> +  data?: any;
I get warnings when changing the type from any that result in the yarn api:check failing with results expected same but got worse but now when Im running it, it's not producing those errors d5591a0 for changes

2021-11-02 11:05 UTC, markov00 commented on packages/charts/src/state/types.ts
> +  data?: any;
yep now it looks good no? 
can you remove the comment on the code? 
```// API Extractor failing with LineAnnotationDatum | RectAnnotationDatum, the dataValue in get_debug_state can be any value```

2021-11-02 11:35 UTC, markov00 requested changes

2021-11-02 11:35 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +    return annotation.annotationType === AnnotationType.Rectangle
You probably just move this condition within the returned object in the `domainType` field.

2021-11-02 11:35 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +          color: annotation?.style,
This is actually the style, not the color, we should rename the field here.

I think we should also return not the spec configured style, but the final style computed with the methods: `mergeWithDefaultAnnotationLine` and `mergeWithDefaultAnnotationRect`

2021-11-02 11:35 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +          data: annotation.dataValues[index],
This is an invalid array access: the `index` is the index of the `annotationSpecs` array, but here you want to enumerate the `dataValues` array. You should rewrite the code to return an `DebugStateAnnotations` per each element into the `dataValues` array of each spec

2021-11-02 16:05 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +    return annotation.annotationType === AnnotationType.Rectangle
b9c90f3 thank you!!

2021-11-02 16:05 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +          color: annotation?.style,
b9c90f3 thank you!

2021-11-03 14:42 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +          data: annotation.dataValues[index],
Ok awesome I think I'm following, for [the click handle rect story](http://localhost:9001/?path=/story/annotations-rects--click-handle-rect-annotation&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_left=6&knob-Axis%20title%20padding%20-%20inner_right=6&knob-Axis%20title%20padding%20-%20inner_shared=6&knob-Axis%20title%20padding%20-%20inner_top=6&knob-Axis%20title%20padding%20-%20outer_bottom=6&knob-Axis%20title%20padding%20-%20outer_left=6&knob-Axis%20title%20padding%20-%20outer_right=6&knob-Axis%20title%20padding%20-%20outer_shared=6&knob-Axis%20title%20padding%20-%20outer_top=6&knob-Tick%20label%20offset%20reference_bottom=local&knob-Tick%20label%20offset%20reference_left=local&knob-Tick%20label%20offset%20reference_right=local&knob-Tick%20label%20offset%20reference_shared=local&knob-Tick%20label%20offset%20reference_top=local&knob-Tick%20label%20padding%20-%20inner_bottom=0&knob-Tick%20label%20padding%20-%20inner_left=0&knob-Tick%20label%20padding%20-%20inner_right=0&knob-Tick%20label%20padding%20-%20inner_shared=0&knob-Tick%20label%20padding%20-%20inner_top=0&knob-Tick%20label%20padding%20-%20outer_bottom=0&knob-Tick%20label%20padding%20-%20outer_left=0&knob-Tick%20label%20padding%20-%20outer_right=0&knob-Tick%20label%20padding%20-%20outer_shared=0&knob-Tick%20label%20padding%20-%20outer_top=0&knob-Tick%20label%20rotation_bottom=0&knob-Tick%20label%20rotation_left=0&knob-Tick%20label%20rotation_right=0&knob-Tick%20label%20rotation_shared=0&knob-Tick%20label%20rotation_top=0&knob-Tick%20label%20x%20offset_bottom=0&knob-Tick%20label%20x%20offset_left=0&knob-Tick%20label%20x%20offset_right=0&knob-Tick%20label%20x%20offset_shared=0&knob-Tick%20label%20x%20offset_top=0&knob-Tick%20label%20y%20offset_bottom=0&knob-Tick%20label%20y%20offset_left=0&knob-Tick%20label%20y%20offset_right=0&knob-Tick%20label%20y%20offset_shared=0&knob-Tick%20label%20y%20offset_top=0&knob-Tick%20line%20padding_bottom=10&knob-Tick%20line%20padding_left=10&knob-Tick%20line%20padding_right=10&knob-Tick%20line%20padding_shared=10&knob-Tick%20line%20padding_top=10&knob-Tick%20line%20size_bottom=10&knob-Tick%20line%20size_left=10&knob-Tick%20line%20size_right=10&knob-Tick%20line%20size_shared=10&knob-Tick%20line%20size_top=10&knob-annotation%20values=a,c&knob-data%20values=2.5,7.2&knob-debug=true&knob-debugState=true&knob-debug_general=true&knob-margin%20bottom_general=10&knob-margin%20left_general=10&knob-margin%20right_general=10&knob-margin%20top_general=10&knob-marker%20position=undefined&knob-number%20of%20groups=1&knob-padding%20bottom_general=0&knob-padding%20left_general=0&knob-padding%20right_general=0&knob-padding%20top_general=0&knob-show%20area=true&knob-show%20bar=true&knob-show%20line=true&knob-x%20domain%20axis%20is%20bottom=true) with multiple rectangle and a line annotation, the debug state looks as follows: 

```
'annotations':
  [{'data':{'coordinates':{'x0':0,'x1':1,'y0':0,'y1':4},'details':'details about this annotation'},
  'id':'rect1',
  'color':{'stroke':'#FFEEBC','strokeWidth':0,'opacity':0.25,'fill':'red'},
  'type':'rectangle'},
  {'data':{'coordinates':{'x0':0.8,'x1':2,'y0':1,'y1':5},'details':'details about this other annotation'},
  'id':'rect2',
  'color':{'stroke':'#FFEEBC','strokeWidth':0,'opacity':0.25,'fill':'blue'},
  'type':'rectangle'},
  {'data':{'dataValue':2,'details':'detail-0'},
  'id':'line_annotation',
  'color':{'line':{'stroke':'#777','strokeWidth':1,'opacity':1},
  'details':{'fontSize':10,'fontFamily':'sans-serif','fontStyle':'normal','fill':'#777','padding':0}},'type':'line',
  'domainType':'xDomain'}
  ]}">
```

2021-11-09 15:18 UTC, nickofthyme approved these changes
LGTM, please review the changes I added in 6517523fe05e43f00827ba3928d404c7006ac6d5.

2021-11-09 15:18 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_debug_state.ts
> +}
The `map`s in this loop are not doing anything. I pulled down the branch to take a look and added some knobs for the annotations stories to see it in action, and just cleaned this up while I was at it. See 6517523fe05e43f00827ba3928d404c7006ac6d5

2021-11-10 18:16 UTC, rshen91 commented
jenkins test this please

2021-11-17 15:55 UTC, markov00 requested changes

2021-11-17 15:55 UTC, markov00 commented on packages/charts/src/state/types.ts
> +  data?: LineAnnotationDatum | RectAnnotationDatum;
I think all these properties, expect for the `domainType` are not optional.
The code that compute those values is the following
```ts
data: dataValue,
      id: annotation.id,
      color:
        annotation.annotationType === AnnotationType.Line
          ? mergeWithDefaultAnnotationLine(annotation?.style)
          : mergeWithDefaultAnnotationRect(annotation?.style),
      type: annotation.annotationType,
      domainType: annotation.annotationType === AnnotationType.Line ? annotation.domainType : undefined,
```
and only domainType can be `undefined`

2021-11-17 15:55 UTC, markov00 commented on packages/charts/src/state/types.ts
> +  data?: LineAnnotationDatum | RectAnnotationDatum;
Few other notes on the `color` property:
- the name doesn't reflect the object type: if you are passing the style as property value let's rename the property key to `style` instead of `color`
- from the code, the style is not a `Partial<RectAnnotationStyle | LineAnnotationStyle>` but a `RectAnnotationStyle | LineAnnotationStyle`

2021-11-17 15:55 UTC, markov00 commented on packages/charts/src/state/types.ts
> +  data?: LineAnnotationDatum | RectAnnotationDatum;
One note on the `type`: it's written that API extractor fails on the AnnotationType, but for me it works if i use them like
```
type: typeof AnnotationType.Line | typeof AnnotationType.Rectangle;
```

2021-11-17 16:14 UTC, rshen91 commented on packages/charts/src/state/types.ts
> +  data?: LineAnnotationDatum | RectAnnotationDatum;
f0675bf for changes thank you!

2021-11-17 16:40 UTC, markov00 approved these changes
It looks good for me!
Thanks for all the changes on the exposed APIs

2021-11-17 16:53 UTC, merged