feat(a11y): xy cartesian data table
elastic/elastic-charts pull request #1472
Opened 2021-11-09 22:53 UTC by rshen91

## Summary

## Details

## Issues

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-11-17 21:13 UTC, rshen91 commented
Jenkins test this please

2021-11-19 15:46 UTC, nickofthyme reviewed
Still reviewing just leaving early comments.

2021-11-19 15:46 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +        {debug && <ScreenReaderCartesianTable />}
Debug is only used internally. Is this table visibility meant to be toggle-able in kibana or just have the table in the dom?

2021-11-19 15:46 UTC, nickofthyme commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +              </button>
Is this necessary? Why not just show all the data with a scroll overflow?

2021-11-19 17:53 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +        {debug && <ScreenReaderCartesianTable />}
AFAIK it's so there's the visual table for debugging vs having to navigate through the DOM.

2021-11-19 17:55 UTC, rshen91 commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +              </button>
I think it's easier with keyboard navigation to have a button to click through voiceover to get the next set of data but I can explore the scroll overflow idea and report back 👍🏻

2021-11-22 14:15 UTC, nickofthyme commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +              </button>
But considering the screen reader case where someone is not able to see the chart and the screenreader is used. Are they gonna have to keep pressing the "more" button? If so maybe we limit it to more only over `100` items or something. What do you think?

2021-11-23 16:37 UTC, nickofthyme commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +              </button>
Discussed on zoom

2021-11-23 16:43 UTC, rshen91 commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +              </button>
Thank you for the zoom! I will make a see previous x value button - that makes a lot of sense thank you!

2021-12-24 10:04 UTC, markov00 commented
hey @rshen91 is this still a WIP or we can review it?
I see two missing checkbox in the description, do we need to wait for them for the review?

2021-12-30 13:03 UTC, rshen91 commented
> hey @rshen91 is this still a WIP or we can review it? I see two missing checkbox in the description, do we need to wait for them for the review?

Please feel free to review this thank you!

2022-01-14 20:18 UTC, 1Copenut requested changes
@rshen91 Thank you for the work and care you put into this PR! I've got a few items that are questions as much as change requests. Please feel free to take what's relevant and discard what's not.

Holler at me anytime for a quick chat or another review.

2022-01-14 20:18 UTC, 1Copenut commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +      tabIndex={-1}
I'm seeing a few `tabindex="-1"` declarations in the table and would like to learn more about how focus is being managed, and how users will navigate the table and change the data point to previous or next point.

2022-01-14 20:18 UTC, 1Copenut commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +                <th scope="row">{label}</th>
Is there a way to conditionally make this a `<th scope="row">` element if the previous `isSmallMultiple` prop is false? Looking at the markup, I could see a situation where we have two TH elements that are scoped to the row. That might cause screen readers to behave unexpectedly.

2022-01-14 20:18 UTC, 1Copenut commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +                      <td colSpan={2}>{val.smPanelTitle}</td>
Same comment about possibly changing this to `<th scope="row">` for the first column from line#133

2022-01-14 20:18 UTC, 1Copenut commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +                        <td colSpan={2}>{val.smPanelTitle}</td>
Could we make the first cell a `<th scope="row">` for the small multiple condition? I like tables that scope rows because it adds another layer of richness to the information read back.

2022-01-18 13:30 UTC, zuhairmahd commented
I have tested with JAWS and NVDA.  Both screen readers read the table descriptions, but it is important to note that no actual tables are present in the DOM -- I am told this was intended behaviour because the tables are images.

2022-01-18 20:12 UTC, rshen91 commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +      tabIndex={-1}
Thank you I think I mixed up the appropriate tab index and fixed in 463fb09. Let me know what you think!

2022-01-19 16:59 UTC, rshen91 commented
The `GroupBy` component provides the vertical axes titles in small multiples cases such as https://elastic.github.io/elastic-charts/?path=/story/small-multiples-alpha--grid-lines&globals=theme:light vs being available on the axis spec. Opening an issue to track small multiple screen reader data table for the future. https://github.com/elastic/elastic-charts/issues/1557

2022-01-19 17:31 UTC, 1Copenut approved these changes
👍 LGTM! I like the markup changes for the table rows, having that scoped TH for each body row will be a strong addition. Thank you for the quick turnaround and logging additional issues to track questions.

2022-01-25 14:38 UTC, rshen91 commented
jenkins test this

2022-01-25 22:41 UTC, nickofthyme requested changes
Looking good. Few questions....

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/components/accessibility/partition_data_table.tsx
> +                <tr key={String(`row--${index}`)} ref={rowLimit === index ? tableRowRef : undefined} tabIndex={-1}>
This should not be needed.

```suggestion
                <tr key={`row--${index}`} ref={rowLimit === index ? tableRowRef : undefined} tabIndex={-1}>
```

2022-01-25 22:41 UTC, nickofthyme commented on playground/playground.tsx
> +  const baseTheme = useBaseTheme();
Could you restore this file? I think we should just `.gitignore` it but that's a task for later.

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_screen_reader_data.ts
> +  }${getTitles}`;
Just thought, this looks kinda wonky. It might be easier to read if you pull the first value portion into a variable assignment before.

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/components/__snapshots__/chart.test.tsx.snap
> +                    <figure aria-labelledby={[undefined]} aria-describedby=\\"chart1--defaultSummary\\" aria-live=\\"polite\\">
I don't know if this is the right place but just to create a thread....

I don't see any changes to the story files so I'm not sure where the overlay is coming from on the the changed vrt screenshots. Also peculiar that they are all annotation stories. Do you know what is causing this?

![image](https://user-images.githubusercontent.com/19007109/151070038-bc004ad4-b18c-4344-ae9b-3e221acee513.png)

In any case I don't think it is a good idea to change all these screenshot, nor that the accessibility feature is on by default for the story. But I'd be great if we created a new `integration/tests/accessibility_stories.test.ts` test file to capture the desired use cases.

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/components/accessibility/accessibility.test.tsx
> +
👍🏼

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +            ]);
This is funky, why are you returning the result of the `push`? Defined to return the new `length` property.

![image](https://user-images.githubusercontent.com/19007109/151071338-4ed91c91-dc03-4a3f-b578-39ea750b6978.png)

The second half of the ternary is also hard to follow with the nested variable assignment. Can we clean this up too?

Is this expected? If not, I'd say just replace this with an if/else block.

2022-01-25 22:41 UTC, nickofthyme commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +export const ScreenReaderCartesianTable = memo(connect(mapStateToProps)(ScreenReaderCartesianTableComponent));
Is this meant to always be enabled? Or is there a flag that we can use to determine when to run this extra logic?

2022-01-25 23:23 UTC, rshen91 commented on packages/charts/src/components/accessibility/partition_data_table.tsx
> +                <tr key={String(`row--${index}`)} ref={rowLimit === index ? tableRowRef : undefined} tabIndex={-1}>
Fixed in 51fd846 thank you!

2022-01-25 23:24 UTC, rshen91 commented on playground/playground.tsx
> +  const baseTheme = useBaseTheme();
Nice! Yes, fixed in 51fd846

2022-01-25 23:24 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/state/selectors/get_screen_reader_data.ts
> +  }${getTitles}`;
Smart - refactored in 51fd846

2022-01-25 23:25 UTC, rshen91 commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +export const ScreenReaderCartesianTable = memo(connect(mapStateToProps)(ScreenReaderCartesianTableComponent));
For now it's always enabled. In testing in Kibana it looks like it's easily avoidable by continuing to tab if screen reader users do not want the information. But I think it makes sense to have it enabled by default, thoughts?

2022-01-26 15:12 UTC, rshen91 commented on packages/charts/src/components/__snapshots__/chart.test.tsx.snap
> +                    <figure aria-labelledby={[undefined]} aria-describedby=\\"chart1--defaultSummary\\" aria-live=\\"polite\\">
In line 183 in the xy-chart.tsx file, there's the clause for if debug is specified to show the component visually. The debug mode then adds the 'echScreenReaderOnlyDebug' class in the cartesian data table component making it visually seen for debugging. I'll look into changing this to remove this overlay and add the extra stories so it can show in only the accessibility cases vs debug generally. Thanks!

2022-01-26 16:49 UTC, rshen91 commented on packages/charts/src/components/accessibility/cartesian_data_table.tsx
> +            ]);
I tried to replace this with an if/else block but we have a ternary rule that is changing it back. 

For charts that have two series, this function is creating a value as an array if the xValue is not yet in the formatted data type. If the xValue has appeared, then it's added to the array. This makes it smoother in the `smallDataTableMultipleSeries` to show information that is a comparison of the different series on the same xValues vs when there is one series. I'm trying to clean it up a little with some commenting to hopefully clear it up a little.

2022-12-14 01:08 UTC, nickofthyme commented
Closing to revisit in the future when accessibility is prioritized.

2022-12-14 01:08 UTC, closed without merging