fix(xy): occlude points outside of domain
elastic/elastic-charts pull request #1475
Opened 2021-11-10 16:38 UTC by rshen91

## Summary

Points are removed from rendering that are beyond the yDomain, and no longer show in the tooltip. 

## Details

## Issues
Fixes #1474 

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-11-10 17:37 UTC, nickofthyme reviewed
Could you also add a vrt that hovers at `x = 2` so we show the tooltip is not available at that point? I think adding it to the existing ones is fine since it can test both the point is no visible AND the tooltip is not shown.

2021-11-10 17:37 UTC, nickofthyme commented on storybook/stories/mixed/8_test_points_outside_domain.story.tsx
> +// for testing purposes only
```suggestion
```

2021-11-10 17:37 UTC, nickofthyme commented on integration/tests/mixed_stories.test.ts
> +          'http://localhost:9001/?path=/story/mixed-charts--test-points-outside-of-domain&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_
These knobs are not all related to the story. Can you reset the url to just the story name and copy just the required knobs?

2021-11-10 17:37 UTC, nickofthyme commented on integration/tests/mixed_stories.test.ts
> +          'http://localhost:9001/?path=/story/mixed-charts--test-points-outside-of-domain&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_
Same here.

2021-11-10 17:37 UTC, nickofthyme commented on integration/tests/mixed_stories.test.ts
> +          'http://localhost:9001/?path=/story/mixed-charts--test-points-outside-of-domain&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_
same here

2021-11-10 18:37 UTC, rshen91 commented on integration/tests/mixed_stories.test.ts
> +          'http://localhost:9001/?path=/story/mixed-charts--test-points-outside-of-domain&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_
3c4c585 thank you!

2021-11-10 18:37 UTC, rshen91 commented on integration/tests/mixed_stories.test.ts
> +          'http://localhost:9001/?path=/story/mixed-charts--test-points-outside-of-domain&globals=theme:light&knob-Axis%20title%20padding%20-%20inner_bottom=6&knob-Axis%20title%20padding%20-%20inner_
3c4c585 thank you!

2021-11-10 18:37 UTC, rshen91 commented on storybook/stories/mixed/8_test_points_outside_domain.story.tsx
> +// for testing purposes only
3c4c585 thank you!

2021-11-10 19:03 UTC, rshen91 commented
> Could you also add a vrt that hovers at `x = 2` so we show the tooltip is not available at that point? I think adding it to the existing ones is fine since it can test both the point is no visible AND the tooltip is not shown.

Sorry missed this and added in commit 03b6400

2021-11-10 19:15 UTC, nickofthyme requested changes

2021-11-10 19:15 UTC, nickofthyme commented on storybook/stories/mixed/mixed.stories.tsx
> +export { Example as testPointsOutsideOfDomain } from './8_test_points_outside_domain.story';
This is not related to mixed stories, this is more of a test case. Can you move this to the `Test Case` directory and update the tests and screenshots?

2021-11-10 20:08 UTC, rshen91 commented on storybook/stories/mixed/mixed.stories.tsx
> +export { Example as testPointsOutsideOfDomain } from './8_test_points_outside_domain.story';
fef72c8 thank you!

2021-11-10 21:20 UTC, rshen91 commented
jenkins test this

2021-11-16 12:09 UTC, markov00 commented
@monfera 
> Wondering if any of the brush or hover events emit granular, point by point details, and if so, whether the hidden points need to be part of the point set passed on to these callbacks or not

The brush event doesn't pass the data points details but only the brush extent in domain coordinates.
The hover event only happens when your mouse is actually over the geometry (point in this case) and this is impossible in our situation.

2021-11-16 12:13 UTC, markov00 reviewed
It looks good to me but I'm wondering if we want to hide the tooltip for those values or not.
In particular I see the benefit of showing, in the "cursor" tooltip, also values that are outside the current specified domain, but I think we should investigate with the Lens team if we want or not show those values.
Instead, is definitely a requirement to not render the points that are outside the domain, to avoid having points floating around outside the chart area

2021-11-16 13:27 UTC, markov00 commented
@rshen91 @nickofthyme I've double-checked with @dej611 and for now it is better to keep the point on the tooltip but remove it from the rendering

2021-11-18 09:40 UTC, markov00 commented on integration/tests/test_cases_stories.test.ts
> +  });
The changes are related to the rendering of points. In the added VRTs only the line chart shows points.
Two solutions for me are:
- or we remove the area tests
- or we change the point visibility on the area tests

Remember that both rendering implementation uses the same `renderPoints` function thus having a double check on both rendering is somewhat unnecessary.
Different is if you want to test how the line or area rendering is affected when setting a shorter Y domain.


Moreover, the test name should be changed to something a bit more clear like: 
describe: `Data points outside the configured Y domain`
test: `should not render points outside domain with line chart`

2021-11-18 09:40 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/rendering/rendering.bubble.test.ts
> +      expect(points).toHaveLength(2);
nit: we should update the comment here to describe the fact that also the 3rd point is not rendered due to a Y domain max of 1

2021-11-18 09:40 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/rendering/rendering.lines.test.ts
> +      expect(points.length).toBe(2);
same here: add to the comment the fact that the 3rd point is not rendered due to Y domain max of 1

2021-11-18 09:40 UTC, markov00 commented on storybook/stories/test_cases/8_test_points_outside_of_domain.story.tsx
> +          minInterval: 1,
we usually never configure the `minInterval` for Y axis, we should probably fix this in the `YDomainRange` but we can do that in a different PR

2021-11-18 09:40 UTC, markov00 commented on storybook/stories/test_cases/8_test_points_outside_of_domain.story.tsx
> +          y0Accessors={[([, y]) => y - 1]}
nit: you can move the `showY0Accessor` check inside the `y0Accessor` prop like:
`y0Accessors={showY0Accessor ? [([, y]) => y - 1] : undefined}`

2021-11-18 14:20 UTC, rshen91 commented on storybook/stories/test_cases/8_test_points_outside_of_domain.story.tsx
> +          y0Accessors={[([, y]) => y - 1]}
Thank you! So much cleaner 176abe4

2021-11-18 14:21 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/rendering/rendering.lines.test.ts
> +      expect(points.length).toBe(2);
Good point added this to the comment in 176abe4

2021-11-18 14:21 UTC, rshen91 commented on packages/charts/src/chart_types/xy_chart/rendering/rendering.bubble.test.ts
> +      expect(points).toHaveLength(2);
Thank you! 176abe4

2021-11-18 14:22 UTC, rshen91 commented on integration/tests/test_cases_stories.test.ts
> +  });
I removed the area tests since I agree they're not giving us much difference in the implementation. The story still has the toggle on type of series so thank you! 176abe4

2021-11-18 15:15 UTC, nickofthyme approved these changes
Code changes since LGTM

2021-11-18 15:15 UTC, nickofthyme commented on storybook/stories/test_cases/8_test_points_outside_of_domain.story.tsx
> +          y0Accessors={showY0Accessor ? [([, y]) => y - 1] : undefined}
👍🏼

2021-11-18 15:15 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/rendering/points.ts
> +      indexedGeometryMap.set(pointGeometry, geometryType);
👍🏼 This is cause vrt changes to the updated.

2021-11-18 17:00 UTC, rshen91 commented on storybook/stories/test_cases/8_test_points_outside_of_domain.story.tsx
> +          minInterval: 1,
Revised story in 8ae91e7 thank you

2021-11-18 17:01 UTC, markov00 approved these changes
Looks good to me!

2021-11-18 17:19 UTC, merged