feat(heatmap): Add heatmap titles
elastic/elastic-charts pull request #1503
Opened 2021-11-23 21:45 UTC by rshen91

## Summary

## Details

## Issues
Closes #1221 

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-11-24 14:36 UTC, nickofthyme commented on storybook/stories/heatmap/1_basic.story.tsx
>        },
One note here, I think this is a reasonable spot to add this but this group only defines properties related to the label specifically. It might be confusing to have `title` mixed in with all other label options.

That said, I am moving all properties from this config to the spec that don't have to deal with the theme. A `title` option would seem to fall into the spec bucket. So what if we move these out of the `(y|x)AxisLabel` into a top level option for `yAxisTitle` and `xAxisTitle`? What do you think?

2021-11-24 14:45 UTC, rshen91 commented on storybook/stories/heatmap/1_basic.story.tsx
>        },
Ok! Thanks I can refactor this 👍🏻

2021-11-24 14:55 UTC, rshen91 commented on storybook/stories/heatmap/1_basic.story.tsx
>        },
https://github.com/elastic/elastic-charts/pull/1406/ for reference PR

2021-11-24 17:32 UTC, rshen91 commented on storybook/stories/heatmap/1_basic.story.tsx
>        },
Refactored in a04178c

2021-12-01 17:02 UTC, nickofthyme reviewed
Looking good just a few more things to consider.

2021-12-01 17:03 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +              ...heatmapTheme.axes.axisTitle,
Also on this note, I'm not sure how I feel about using `theme.axes` styles. I think it is good to share but many of the styles for xy are not used on heatmap. I don't see a great alternative though.

@markov00 any thoughts on this?

2021-12-01 17:19 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
>      getGridHeightParamsSelector,
I think the padding...

```ts
const totalVerticalPadding = padding * 2;
```

...is too much, if we just assume it as a single padding not double it looks better. Also we don't account for the double padding when rendering the axis labels.

![Kapture 2021-12-01 at 11 15 54](https://user-images.githubusercontent.com/19007109/144282117-7f1cd3dd-266e-46ce-ada5-eb28f2f4b898.gif)

2021-12-01 19:10 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +            heatmapSpec.yAxisTitle!,
Amazing thank you 7672988 for changes

2021-12-01 19:10 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +  heatmapTheme: Theme,
Yes, smart 7672988 for changes thanks

2021-12-01 19:11 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
> +        : textMeasure(config.yAxisLabel.fontSize, boxedYValues);
omg thank you 7672988 for changes

2021-12-01 20:33 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/specs/heatmap.ts
> +export const defaultProps = {
No need to export this

```suggestion
const defaultProps = {
```

2021-12-01 20:35 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/get_grid_full_height.ts
>      const totalVerticalPadding = padding * 2;
I think we get rid of this `* 2` logic.

```suggestion
    const totalVerticalPadding = padding; // or just replace totalVerticalPadding with padding below
```

2021-12-02 17:58 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +              ...heatmapTheme.axes.axisTitle,
Refactored in eb9c5ab to pull from the config

2021-12-02 17:58 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_dimensions.ts
>      getGridHeightParamsSelector,
Fixed padding in eb9c5ab thanks!

2021-12-02 17:58 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/specs/heatmap.ts
> +export const defaultProps = {
Fixed in eb9c5ab thanks!

2021-12-02 17:58 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_grid_full_height.ts
>      const totalVerticalPadding = padding * 2;
Removed in eb9c5ab thanks!

2021-12-03 10:17 UTC, markov00 requested changes

2021-12-03 10:17 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +              y: xValues[0].y + config.xAxisLabel.fontSize,
This doesn't sound correct. The first element in the `xValues` is not necessarily the tick of the first x column. You can notice that if you apply an x axis title to the `time` heatmap example.

Take a look at how we are rendering the cells, there is a `gridOrigin`property that describes where the grid needs to be rendered in the canvas space.

For the Y position: are we not respecting the style padding, the text color and some other stylings.
<img width="589" alt="Screenshot 2021-12-03 at 11 02 39" src="https://user-images.githubusercontent.com/1421091/144584166-8cfdb8ef-332e-4cbf-956c-b55ba8b1fc23.png">

2021-12-03 10:17 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +            },
since we are forcing `baseline: middle` and `align:center` the `x` and the `y` coordinates needs to follow this logic for the Y title (inverted for the x one):
- the `x` needs to be at: `yAxisTitleOuterPadding + halfTitleFontSize`
- the `y` needs to be at: `gridOrigin.y + halfHeatmapHeight`

The logic for the X title is:
- the `x` position needs to be at: `gridOrigin.x + halfHeatmapWidth`
- the `y` position needs to be at: `containerHeight - xAxisHeight - totalVerticalPadding - legendHeight - xAxisTitleOuterPadding - halfTitleFontSize`


You can probably precompute those values somewhere else in the code and pass just the final coordinates

2021-12-03 10:17 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +    heatmapTheme: getChartThemeSelector(state),
We don't need and we are not using the `theme`  already, so we can get rid of this

2021-12-06 18:45 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +            },
Ok thanks I could use some help figuring out why the basic heatmap story is rendering the x axis title weirdly but I think I've gotten most of the changes in 0ba6e13. Thank you so much for the help on this.

2021-12-06 19:02 UTC, rshen91 commented on packages/charts/src/chart_types/heatmap/renderer/canvas/connected_component.tsx
> +    heatmapTheme: getChartThemeSelector(state),
removed in 0ba6e13

2021-12-06 19:03 UTC, rshen91 commented on packages/charts/api/charts.api.md
> +    axisTitle: TextStyle & Visible;
Im cool with that! Changed in 0ba6e13

2021-12-07 18:54 UTC, rshen91 commented
Since Nick's PR is going to be pulling some properties off the theme vs the config, would it be cool to just put the titles on the theme instead of the config? @markov00 and @nickofthyme thoughts?

2021-12-09 09:12 UTC, markov00 commented
> Since Nick's PR is going to be pulling some properties off the theme vs the config, would it be cool to just put the titles on the theme instead of the config? @markov00 and @nickofthyme thoughts?

@rshen91 My preference is to put the title style in the theme and keep the `title` text as it is today. @nickofthyme ?

2021-12-21 17:43 UTC, markov00 approved these changes

2021-12-21 18:01 UTC, merged