feat(goal): add valueFormatter for tooltip
elastic/elastic-charts pull request #1529
Opened 2021-12-17 16:22 UTC by rshen91

## Summary

## Details

## Issues
Closes #1521 

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2021-12-27 13:26 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/state/selectors/tooltip.ts
> +        formattedValue: valueFormatter ? valueFormatter(value) : `${value}`,
From your typings `valueFormatter` is always available, no need to check for its existence.
```suggestion
        formattedValue: spec.valueFormatter(value),
```

2021-12-27 13:26 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/types/viewmodel_types.ts
> +  valueFormatter: (value: any) => value,
please avoid the usage of `any`. `ValueFormatter` actually is a function with well known type as argument

2021-12-27 13:26 UTC, markov00 commented on storybook/stories/goal/2_gauge_with_target.story.tsx
> +        valueFormatter={useValueFormatter ? (d: any) => `Testing ${d}` : undefined}
You can probably just issue a nice `valueFormatter` that reflects the chart context like 
```
valueFormatter={(d) => `${d}k USD`}
```
and avoid the knob

2021-12-27 14:06 UTC, rshen91 commented on storybook/stories/goal/2_gauge_with_target.story.tsx
> +        valueFormatter={useValueFormatter ? (d: any) => `Testing ${d}` : undefined}
Thank you d41cb16 for changes

2021-12-27 14:07 UTC, rshen91 commented on packages/charts/src/chart_types/goal_chart/layout/types/viewmodel_types.ts
> +  valueFormatter: (value: any) => value,
Smart - d41cb16 for changes

2021-12-27 14:07 UTC, rshen91 commented on packages/charts/src/chart_types/goal_chart/state/selectors/tooltip.ts
> +        formattedValue: valueFormatter ? valueFormatter(value) : `${value}`,
ok that makes sense - d41cb16 for changes thanks

2021-12-27 17:53 UTC, rshen91 commented
@markov00 I think the `centralMajor` prop that already exists will accomplish the valueFormatting behavior for the actual value. I'm going to change the name of the valueFormatter to tooltipValueFormatter though for clarity.

2022-01-04 17:35 UTC, nickofthyme requested changes
Looks good, had a few questions.

2022-01-04 17:35 UTC, nickofthyme commented on storybook/stories/goal/2_gauge_with_target.story.tsx
> +        tooltipValueFormatter={(d) => `${d}k USD`}
Did you want the `$` here too?

```suggestion
        tooltipValueFormatter={(d) => `$${d}k USD`}
```

2022-01-04 17:35 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +export type GoalLabelAccessor = LabelAccessor<BandFillColorAccessorInput> | (() => string);
Why is this necessary? This type is already acceptable to the current type `LabelAccessor<BandFillColorAccessorInput>`.

```suggestion
export type GoalLabelAccessor = LabelAccessor<BandFillColorAccessorInput>;
```

2022-01-04 17:35 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +  centralMajor: string | GoalLabelAccessor | (() => string);
Same here but also this would be a duplicated union of `(() => string) | (() => string)`.

```suggestion
  centralMajor: string | GoalLabelAccessor;
```

2022-01-04 17:35 UTC, nickofthyme commented on packages/charts/src/components/__snapshots__/chart.test.tsx.snap
> +`;
This might cause unit tests to fail.

```suggestion
`;

```

2022-01-04 17:35 UTC, nickofthyme commented on packages/charts/src/components/accessibility/types.tsx
> +      {validGoalChart && goalChartData && typeof goalChartData.maximum === 'number' ? (
Isn't this always a `number`?

https://github.com/elastic/elastic-charts/blob/72224b9bcbdc2ff9eb6c048fdba7dd13fac39db5/packages/charts/src/chart_types/goal_chart/state/selectors/get_goal_chart_data.ts#L13-L18

Are you meaning to check for `NaN`?

2022-01-05 14:32 UTC, rshen91 commented on storybook/stories/goal/2_gauge_with_target.story.tsx
> +        tooltipValueFormatter={(d) => `${d}k USD`}
thank you! 9e61b47

2022-01-05 14:33 UTC, rshen91 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +export type GoalLabelAccessor = LabelAccessor<BandFillColorAccessorInput> | (() => string);
ok sweet - 9e61b47 woo

2022-01-05 14:33 UTC, rshen91 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +  centralMajor: string | GoalLabelAccessor | (() => string);
9e61b47 for changes thanks!

2022-01-05 14:33 UTC, rshen91 commented on packages/charts/src/components/__snapshots__/chart.test.tsx.snap
> +`;
nice thank you! 9e61b47

2022-01-05 14:36 UTC, nickofthyme commented on packages/charts/src/components/accessibility/types.tsx
> +      {validGoalChart && goalChartData && isNaN(goalChartData.maximum) ? (
```suggestion
      {validGoalChart && goalChartData && !isNaN(goalChartData.maximum) ? (
```

2022-01-05 14:37 UTC, nickofthyme commented on packages/charts/src/components/accessibility/types.tsx
> +      {validGoalChart && goalChartData && isNaN(goalChartData.maximum) ? (
Or there is an `isFinite` method to use instead, your choice.

2022-01-05 14:51 UTC, rshen91 commented on packages/charts/src/components/accessibility/types.tsx
> +      {validGoalChart && goalChartData && isNaN(goalChartData.maximum) ? (
ugh lols c0ad38d thanks

2022-01-05 14:53 UTC, nickofthyme approved these changes

2022-01-05 15:19 UTC, merged