feat(goal): auto generated linear ticks
elastic/elastic-charts pull request #1637
Opened 2022-03-31 03:35 UTC by nickofthyme

## Summary

Adds automated linear ticks for goal/gauge charts when to `ticks` value is provided. Adds a new `nice` prop to force ticks to be _niced_ given the specified domain.

## Details

This PR adds linear ticks generation from the provided domain via a `ScaleContinuous`.

## Issues

closes #1238

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2022-03-31 10:40 UTC, markov00 requested changes

2022-03-31 10:40 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  ].reduce(([min, max], value) => [Math.min(min, value), Math.max(max, value)], [Infinity, -Infinity]);
You can use a function called `extent` in `common/math`

2022-03-31 10:40 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +      nice,
Nicing can't be applied only for ticks. Nicing changes the domain of the chart increasing it to the next nice/rounded value.

I think we can't introduce that feature if we don't also change the domain used by the chart scale.

2022-03-31 10:40 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
this was used before to compute the domain min and max values. But now, adding the automatic tick generation a user can't use the bullet graph without bands (the minimal version of it) because the band is used to define a maximum on the scale.
I think we need to rethink the domain definition and introduce a real `domain` prop that will describe the `min, max` values to be used in the chart scale.
The rest should stay:
- the `base` should stay the same (I can have a negative-to-positive bullet with a base on 0)
- the `target` should stay the same (it's a comparative metric that should be within the bullet domain)
- both `bands` and `ticks` can be auto-generated if needed.a

Optional property can be `domainClip: boolean` that can describe the fact that the `actual` value can be clipped within the domain ranges (the bar should not exceed the min, max domain values) or it can overflow the domain values (and in this case the domain can be: extended with that actual value, or we can find an alternative way to describe the fact that value exceed the domain max or min)
@monfera to the rescue

2022-03-31 10:40 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +      range: [0, chartDimensions.width], // TODO apply range based on chart rotation
we don't need a real range here, `[0,1]` is good enough

2022-03-31 10:40 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +    new ScaleContinuous({
The default number of desired ticks is 10, this value is actually too much for a standard bullet/gauge.
We can configure it to something around 3 max.
This needs to be applied until we don't have the mechanism to reduce the number of ticks when they overlap.

2022-03-31 17:08 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +      nice,
reverted in 4a3d090

2022-03-31 17:08 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +      range: [0, chartDimensions.width], // TODO apply range based on chart rotation
4a3d090

2022-03-31 22:57 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  ].reduce(([min, max], value) => [Math.min(min, value), Math.max(max, value)], [Infinity, -Infinity]);
f1857d2

2022-03-31 22:59 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
Ok sounds good. I'm not sure how we should compute the `bands` if they don't supply them. But if they _do_ supply a custom band values we should still use them in the `extents` calculations right?

2022-04-01 16:28 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
I think also `bands` could be marked as `optional`.
In that way we can have:
| `ticks` prop | `bands` prop | ticks | bands |
| ---- | ---- |  ---- |  ---- | 
| undefined | undefined | generated | use bands computed from generated ticks |
| undefined | [] | generated | no band rendered |
| [] | undefined | no ticks | generate bands similar to tick generation | 
| [] | [] | no ticks | no bands |

> But if they do supply a custom band values we should still use them in the extents calculations right?

I think the `extent` should be always limited within the `min,max` of the `domain` prop

2022-04-01 16:33 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +    new ScaleContinuous({
nice dynamic ticks calculation nick!

yea, using `ticks: number | number[]` will probably work. Robert is not a fan of union type, but I see more confusion having that as a separate prop:
```
ticks?: []
desiredTickCount?: number
```
It is less clear how the two interact with each other then the union type proposal

2022-04-01 16:34 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
I've just read the next comment about the `ticks: number | number[]` and the approach can probably be attached to `bands` too

2022-04-01 16:40 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
OK I'll take a stab at it and we can tweak it from there.

So should the `domain` be required? Or should we find the extents from the `base`, `target` and `actual` only when the `domain` is not provided?

2022-04-01 18:19 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +    new ScaleContinuous({
Ok I added this in ed843b6

2022-04-01 19:05 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
Ok I took a stab at this in ed843b6. See the deployed story [here](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks).

| Criteria  | Example |
| - | - |
| No `domain.min` nor `domain.max`, uses computed extents `min` and/or `max`. Computed `min` here contolled by `base` value of `100` and the `max` is controlled by the `target` of `260`. Both `bands` and `ticks` are `undefined` and autogenerated. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=true&knob-auto%20domain%20min=true&knob-auto%20generate%20bands=true&knob-auto%20generate%20ticks=true&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=400&knob-bands[0]=200&knob-bands[1]=250&knob-bands[2]=300). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161324079-ffbf71fa-f77b-45b0-8927-4ab07d537e79.png"> |
| `domain.min = 0` and `domain.max = 400`, uses specified `min` and `max`. Both `bands` and `ticks` are `undefined` and autogenerated. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=&knob-auto%20domain%20min=&knob-auto%20generate%20bands=true&knob-auto%20generate%20ticks=true&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=400&knob-bands[0]=200&knob-bands[1]=250&knob-bands[2]=300). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161323637-459237d6-1bff-4795-a8eb-1a830e57c908.jpg"> |
| The `bands` are set to `[0, 200,250,300]`. The `ticks` are auto computed driven by the `bands` domain. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=true&knob-auto%20domain%20min=true&knob-auto%20generate%20bands=&knob-auto%20generate%20ticks=true&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=400&knob-bands[0]=0&knob-bands[1]=%20200&knob-bands[2]=250&knob-bands[3]=300). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161324453-8b6874dc-70d0-4e9a-9812-e241b51d2482.png"> |
| The `ticks` are set to `[0, 100, 200, 300]`. The `bands` are auto computed driven by the `ticks` domain. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=true&knob-auto%20domain%20min=true&knob-auto%20generate%20bands=true&knob-auto%20generate%20ticks=&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=400&knob-ticks[0]=0&knob-ticks[1]=%20100&knob-ticks[2]=%20200&knob-ticks[3]=%20300). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161324738-b704648f-7da6-4eab-9166-af8101a97ab9.png"> |
| The `bands` are set to `[]`. The `ticks` are auto computed driven by the `base` and `target`. No bands are rendered. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=true&knob-auto%20domain%20min=true&knob-auto%20generate%20bands=&knob-auto%20generate%20ticks=true&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=400&knob-ticks[0]=0&knob-ticks[1]=%20100&knob-ticks[2]=%20200&knob-ticks[3]=%20300). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161325133-4cfc6428-611d-4afe-856e-d173be2a6337.png"> |
| When `domain.min` and `domain.max` are specified, in this case `domain = { min: 0, max: 300 }`. The values outside of the explicit domain are filtered from `ticks` and `bands` values. With `ticks` set to `[-100, 0, 200, 300, 400]` and `bands` set to `[-100, 0, 200, 300, 400]`, both the `-100` and `400` values will be excluded from the rendering for both `ticks` and `bands`. See [example](https://ech-e2e-ci--pr-1637-rqyolfud.web.app/?path=/story/goal-alpha--auto-linear-ticks&globals=theme:light&knob-actual=200&knob-angleEnd%20(%CF%80)=-0.25&knob-angleStart%20(%CF%80)=1.25&knob-auto%20domain%20max=&knob-auto%20domain%20min=&knob-auto%20generate%20bands=&knob-auto%20generate%20ticks=&knob-base=100&knob-target=260&knob-reverse=&knob-domain%20min=0&knob-domain%20max=300&knob-bands[0]=-100&knob-bands[1]=%200&knob-bands[2]=%20200&knob-bands[3]=%20300&knob-bands[4]=%20400&knob-ticks[0]=-100&knob-ticks[1]=%200&knob-ticks[2]=%20100&knob-ticks[3]=%20200&knob-ticks[4]=%20300&knob-ticks[5]=%20400). | <img width="1000vw" src="https://user-images.githubusercontent.com/19007109/161325843-dbc78869-5ace-48d9-99b9-8e8979d955c6.png"> |

@markov00 Let me know if you think any these cases should have a different behavior.

2022-04-05 12:14 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
To summarize what we decided:
1) the `domain` is mandatory with a min and max, both of them finite numbers (if non-finite, we can consider 0 as min and 1 as max).
2) an element in `ticks` that falls outside the domain is filtered out
3) an element in `bands` that falls outside the domain is filtered out
4) auto-ticks and auto-bands are computed based on the `domain`
5) `base`, `target` and `actual` are limited within the domain. If they fall outside, we still use these values but we limit the rendering within the domain. In particular `target` will not be rendered at all, `base` will be clamped to the min value of the domain and the `actual` value will be rendered only within the domain, with its extremes clamped to the min/max of the domain.

2022-04-05 12:28 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +   * array of descrete tick values or aproximate number of desired ticks
```suggestion
   * Array of discrete tick values or approximate number of desired ticks
```

2022-04-05 12:28 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +   * array of descrete band intervals or aproximate number of desired bands
```suggestion
   * array of discrete band intervals or approximate number of desired bands
```

2022-04-05 12:28 UTC, markov00 commented on packages/charts/src/utils/common.ts
> +export const isBetween = (min: number, max: number) => (n: number) => n <= max && n >= min;
is not clear from the name nor the docs if the value is included in the range or excluded.
A possible suggestion can be:
```
isValueInInterval = (min, max, closed = true) => (n: number) => closed ? min >= n && n <= max : min > n && n < max;
```

2022-04-05 12:28 UTC, markov00 commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +        subtype={subtype}
Can we make this dynamic and use bullet by default? I think we should push more for bullet when possible

2022-04-05 12:28 UTC, markov00 commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +        centralMajor="280 MB/s"
this should be dynamic and linked to the actual value

2022-04-05 21:59 UTC, nickofthyme commented on packages/charts/src/utils/common.ts
> +export const isBetween = (min: number, max: number) => (n: number) => n <= max && n >= min;
ec2a590

2022-04-05 21:59 UTC, nickofthyme commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +        subtype={subtype}
6e23e03

2022-04-05 21:59 UTC, nickofthyme commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +        centralMajor="280 MB/s"
6e23e03

2022-04-05 22:50 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
Ok I think I captured all the points above in e9dc2f1, thanks for the summary 🙏. 

> 4. auto-ticks and auto-bands are computed based on the domain

Just to be clear, the ticks/bands are only computed from the domain when left `undefined` right?

2022-04-06 09:58 UTC, markov00 approved these changes
Everything looks good now, thanks for all the updates.
I've put some minor comments about the docs/tsdocs, everything else is great!

2022-04-06 09:58 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +  max: number;
Can you please specify, in a comment that the min and max should be finite numbers?

2022-04-06 09:58 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +   * Domain extents of goal chart. Overrides computed extents.
We don't compute an extent, but we take the domain for granted.
We can say that the chart limits every other value to this domain

2022-04-06 09:58 UTC, markov00 commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +  markdown: `Leaving \`ticks\` and/or \`bands\` as \`undefined\` will automatically generate linear values given the computed or specified domain.
```suggestion
  markdown: `Leaving \`ticks\` and/or \`bands\` as \`undefined\` will automatically generate linear values given the specified domain.
```

2022-04-06 09:58 UTC, markov00 commented on packages/charts/src/chart_types/goal_chart/layout/viewmodel/viewmodel.ts
> +  const [lowestValue, highestValue] = [
>the ticks/bands are only computed from the domain when left undefined right?

yes, when `ticks` and/or `bands` are `undefined` we want to automatically compute the ticks for them based on the provided domain.

2022-04-06 14:03 UTC, nickofthyme commented on storybook/stories/goal/26_auto_linear_ticks.story.tsx
> +  markdown: `Leaving \`ticks\` and/or \`bands\` as \`undefined\` will automatically generate linear values given the computed or specified domain.
94393c4

2022-04-06 14:03 UTC, nickofthyme commented on packages/charts/src/chart_types/goal_chart/specs/index.ts
> +  max: number;
94393c4

2022-04-06 15:35 UTC, merged