fix(bubble): tooltip visibility on hover
elastic/elastic-charts pull request #1674
Opened 2022-05-17 14:31 UTC by nickofthyme

## Summary

Fixes a bug in bubble chart that prevented the hovered values from correctly being active.

### Before

![Screen Recording 2022-05-17 at 09 31 57 AM](https://user-images.githubusercontent.com/19007109/168836673-9049584f-6f18-46ba-8fb0-23708a6ce1b3.gif)

### After

![Screen Recording 2022-05-17 at 09 30 01 AM](https://user-images.githubusercontent.com/19007109/168836246-ea7739b4-0b0d-472d-a672-4dff57ad9b65.gif)

## Details

The issue is that the bubble chart was being filled on the x domain and this created bad `NaN` values in the Delaunay index and excluded those values from the tooltip list.

I'm not sure what actually caused this as I don't see or think of any recent (<16m) changes to the problematic files. Maybe the `NaN` scale changes just brought the issue to light but I don't think that is what caused this.

## Issues

#1673

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] Unit tests have been added or updated to match the most common scenarios

2022-05-17 14:35 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
> -            }
@markov00 This fixes the `debug` error.

2022-05-18 08:48 UTC, markov00 requested changes
The fix should not change the current existing fill behaviour of line/area charts.
I proposed a solution that I tested locally and that could work fine without changing the that behaviour

2022-05-18 08:48 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/utils/fill_series.ts
> +  return (isAreaSeriesSpec(spec) || isLineSeriesSpec(spec)) && (isStacked || !!spec.fit);
I don't think this is the correct way to fix the problem and to me it looks like it doesn't fully respect the original constraints making a general change on how to fill missing values.
I know is a bit convoluted with all those double negations, but the inverted representation you are doing doesn't fully cover all the aspects that where there before.

2022-05-18 08:48 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/rendering/points.ts
>        indexedGeometryMap.set(pointGeometry, geometryType);
What you can don here instead is to check if the `datum` was filled before updating the geometry map with 
```ts
if(!isDatumFilled(datum)) indexedGeometryMap.set(pointGeometry, geometryType);
```

2022-05-18 08:48 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
> -            }
more then fix it avoids the error :D, I like btw the voronoi debug, there is definitely some issue with the closures or something along that blocks that renderer.
I'm fine commenting this out until we don't fix the issue if you don't mind

2022-05-18 13:32 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
> -            }
Oh yeah I forgot about the voronoi debug 🤦‍♂️. I'll add it back and look at the closure.

2022-05-18 13:34 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/fill_series.ts
> +  return (isAreaSeriesSpec(spec) || isLineSeriesSpec(spec)) && (isStacked || !!spec.fit);
That's fine but in general why are we defaulting to fill x values? By saying `isXFillNotRequired` defines only when it is skippable, that way everytime we add new chart types, we would need to update this fill it is not needed.

2022-05-27 13:54 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/utils/fill_series.ts
> +  return (isAreaSeriesSpec(spec) || isLineSeriesSpec(spec)) && (isStacked || !!spec.fit);
I've reverted back this to the current master, this PR https://github.com/elastic/elastic-charts/pull/1688 will take care of fixing this correctly

2022-05-27 13:56 UTC, markov00 commented on packages/charts/src/chart_types/xy_chart/utils/fill_series.ts
> +function isXFillRequired(spec: BasicSeriesSpec, groupScaleType: ScaleType, isStacked: boolean): boolean {
I'm going to fix this in a different PR: https://github.com/elastic/elastic-charts/pull/1688

2022-05-27 14:51 UTC, markov00 approved these changes
I've refactored the fix to push the solution more into the spatial index context rather than an an higher level.
Please @nickofthyme check my comments on this page and review the changes

2022-05-31 15:58 UTC, nickofthyme reviewed
Can't approve my own PR but changes all look good.

2022-05-31 15:58 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/renderer/canvas/renderers.ts
> +              voronoi.render(ctx);
👍🏼

2022-05-31 15:58 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/utils/indexed_geometry_spatial_map.ts
> +    });
Nice!

2022-05-31 15:58 UTC, nickofthyme commented on packages/charts/src/chart_types/xy_chart/rendering/points.ts
> +      if (isFiniteNumber(y) && yDefined(datum, valueAccessor) && isInYDomain && !isDatumFilled(datum)) {
I don't think this check is necessary at all cuz canvas just ignores `NaN` values.

```suggestion
      if (yDefined(datum, valueAccessor) && isInYDomain && !isDatumFilled(datum)) {
```

2022-05-31 16:33 UTC, markov00 approved these changes

2022-06-01 15:39 UTC, merged