feat(metric): add click handling
elastic/elastic-charts pull request #1718
Opened 2022-06-20 14:51 UTC by markov00

## Summary

Add click handling to a metric chart.

## Issues

fix #1706 

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2022-06-21 13:45 UTC, gvnmagni commented
Little question, should we disable the color contrast checking between background and texts when hovering? The following gif is what happens with a background that is close to that limit where labels need to be white or black. Hovering on it, since we make the background lighter, makes the labels to change color which might be a little disturbing 

![metric hover gif](https://user-images.githubusercontent.com/18484576/174814213-377bf36c-8044-4464-9f38-52d82ec0e999.gif)

What do you think?

2022-06-21 16:30 UTC, markov00 commented
> Little question, should we disable the color contrast checking between background and texts when hovering? The following gif is what happens with a background that is close to that limit where labels need to be white or black. Hovering on it, since we make the background lighter, makes the labels to change color which might be a little disturbing
> What do you think?

Good question, I don't actually know. There are two possible solutions probably:
- don't change that color when hovering over with the drawback of having a bit less legible text
- change the color but with a smooth transition, as we are doing with the background.

2022-06-21 16:32 UTC, markov00 commented
Hi @1Copenut, with this PR we are adding the possibility to click on a metric to execute some external action. 
I've considered switching from a set of simple `div`s to a `button` container when that action is available. Do you think this make sense or we can keep the `div` and specify a different role or aria attribute to describe that the element is actionable?

2022-06-23 00:00 UTC, nickofthyme approved these changes
Final deployed version looks good. I have a few comments about the API but overall approve.

2022-06-23 09:58 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      onClick={() => onElementClick && onElementClick([event])}
done in https://github.com/elastic/elastic-charts/pull/1718/commits/ad1dfc5335263a71f81fbf426b53febcde67ead6

2022-06-23 09:58 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      )}
done in done in https://github.com/elastic/elastic-charts/pull/1718/commits/ad1dfc5335263a71f81fbf426b53febcde67ead6

2022-06-23 09:58 UTC, markov00 commented on packages/charts/src/specs/settings.tsx
> +};
true, I've switched to https://github.com/elastic/elastic-charts/pull/1718/commits/85c37dc55cd9c6d7f90c60b432ea0b892ccaf191

2022-06-23 13:29 UTC, nickofthyme commented on packages/charts/src/specs/settings.tsx
> +};
What do you think about adding an optional `id` to each metric in the array?

2022-06-23 13:33 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      onClick={() => onElementClick([event])}
So all of these need to be set whether `onElementClick` is set or not?

2022-06-23 13:33 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      onClick={() => onElementClick && onElementClick([event])}
See https://github.com/elastic/elastic-charts/pull/1718#discussion_r905028359

2022-06-23 14:56 UTC, 1Copenut commented
> Little question, should we disable the color contrast checking between background and texts when hovering?

I'd recommend not disabling the contrast checking on hover and focus. [WCAG Success Criterion 1.4.3: Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) doesn't mention any affordances for contrast ratios to be reduced on interaction states. What do you think about increasing contrast (making the background darker) on these interactions?

2022-06-23 15:02 UTC, markov00 commented on packages/charts/src/specs/settings.tsx
> +};
The metrics grid is actually rendered from a single MetricSpec.  I don't see what the `id`could represent. In particular since that we are mapping the grid cells positions to the datum position from the 2d array. So with that, the row/column indices are the minimal representation of the metric. With those 2 indices, going back to the original datum is even simpler then use an id and scanning a 2d array.

2022-06-23 15:05 UTC, 1Copenut requested changes
I’ve been thinking about this PR for a couple of days. I want to keep the metrics maximally keyboard and screen reader accessible, without losing the awesome semantic data packed into each one. My recommendation is to keep the metric “cards” as DIV elements. I’ll link a couple of articles below that I stand behind as best practices for ensuring cards are clickable, reachable by keyboard, and all information is available in a meaningful order for screen readers.

Please let me know if you’d like to meet up or Zoom call to discuss these recommendations. Thank you!

* https://inclusive-components.design/cards/
* https://css-tricks.com/block-links-the-search-for-a-perfect-solution/

2022-06-23 15:05 UTC, 1Copenut commented on storybook/stories/metric/2_grid.story.tsx
> +        <Settings
More suggestion than change request--what do you think about wrapping the grid of metrics in a UL, and each metric in an LI? I've had similar grids of cards identified as needing to be lists in the past, and think it'd be a nice example to provide in the Storybook. If that's a lot of extra work, maybe something in the docs about making a grid of metrics into a proper list?

2022-06-23 17:31 UTC, 1Copenut commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +  const ComponentType = onElementClick ? 'button' : 'div';
I think leaving the individual metric containers as `<div>` is a good approach. I was more asking if it was easy to wrap the group in a list. Something like this roughly:

```html
<div class="your-grid-classes">
  <ul>
    <li><div>Metric one</div></li>
    <li><div>Metric two</div></li>
```

2022-06-27 21:30 UTC, 1Copenut commented on packages/charts/src/chart_types/metric/renderer/dom/index.tsx
>          className="echMetricContainer"
I'd like to add a `role="list"` here. It's redundant and might need a TS ignore rule, but will ensure VoiceOver announces the proper count of list items.

2022-06-28 08:58 UTC, markov00 commented on packages/charts/src/common/color_library_wrappers.ts
> +export function changeColorLightness(color: Color, lightnessAmount: number, lightnessThreshold: number): Color {
@1Copenut This function is just used to change the background color to a different one, but then, the text color is computed always based on that color.

2022-06-28 09:01 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/index.tsx
>          className="echMetricContainer"
done in [6400c43](https://github.com/elastic/elastic-charts/pull/1718/commits/6400c4357169692f3d93c815b981eb7ec4cb971b)

2022-06-28 09:01 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      role="presentation"
done in [6400c43](https://github.com/elastic/elastic-charts/pull/1718/commits/6400c4357169692f3d93c815b981eb7ec4cb971b)

2022-06-28 09:01 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +      onMouseLeave={() => {
done in [3eeb370](https://github.com/elastic/elastic-charts/pull/1718/commits/3eeb370d4519f2e0a59f741db6ba57fdf8ce007d)

2022-06-28 09:01 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/metric.tsx
> +  const ComponentType = onElementClick ? 'button' : 'div';
done

2022-06-28 14:22 UTC, 1Copenut commented on packages/charts/src/common/color_library_wrappers.ts
> +export function changeColorLightness(color: Color, lightnessAmount: number, lightnessThreshold: number): Color {
Copy that. Can we add documentation to manually check text contrast ratios against standard and lightened/darkened backgrounds? Generally speaking, dark text will meet the 4.5:1 ratio against the standard or a lightened background. White text against a black or blue background that's lightened to gray or a lighter shade of blue could miss the threshold. This is difficult to pick up with automated checks, so I'm asking that designers be aware of the possibility and test color pairs.

2022-06-28 14:32 UTC, 1Copenut approved these changes
LGTM! These latest changes tested very well in VoiceOver on Safari and Firefox. I was able to tab to each of the `h2 > button` elements, and the semantics are well-organized. Thank you for this additional round of changes @markov00

2022-06-29 09:13 UTC, gvnmagni approved these changes

2022-07-04 09:44 UTC, markov00 commented
buildkite update vrt

2022-07-04 10:16 UTC, merged