feat(tooltip): initial sticky interactions
elastic/elastic-charts pull request #1782
Opened 2022-08-10 04:01 UTC by nickofthyme

## Summary

Adds sticky tooltip interaction whenever `Tooltip.actions` are defined.

Features:
- Right-click to stick tooltip
- Select series on stuck tooltip
- Disables stickiness for empty tooltips

TODOs
- add optional listener to catch cancelling selection
- click geoms to add to selection, remove option to click other geoms outside of active x
- remove geom highlights when stuck
- track stuck x positions, as single value array to expect multi-x in the future
- block cursor pointer over tooltip

## Details

Modifies the `interactions` redux state to add tooltip stuck/selection state and account for the stuck state and disable existing interactions like drag and click while stuck.

The <kbd>esc</kbd> option to cancel the brush interaction was added a while ago but was a little loose when adding and removing the keyboard event listeners.

## Issues

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2022-08-14 17:52 UTC, monfera reviewed
Nice work! It's a WIP so all these below may be on your list already:

There are some statefulness issues, for example:
- activating the tooltip, then, as the next step, trying to activate it elsewhere just clears the pinned tooltip
- even after clearing (right-click on another bar) it's not possible to pin the tooltip, it requires that the mouse first be moved, probably to populate x/y values (right-click DOM interactions also pass on coordinates, so I think there should be no requirement for a mousemove)
- activating the tooltip, then left-clicking on another bar (or pretty much anything else, except, apparently, the Esc key or another right-click tooltip activation attempt) doesn't clear the pinned tooltip

It'd feel odd to maintain the pinned status if the user clicks (eg. left-clicks) elsewhere. A click is a strong expression of intent, whether activating something else or cancelling a current modality. Our interaction design for this should be such that it's super easy to get out of the pinned mode. So, starting with "literally everything gets the user out of pinned mode" then remove hover from that list (I think only a subsequent hover should leave the tooltip pinned)

Wondering if the pinned tooltip needs the common ☒ button on the top of the tooltip as another means for cancellation. While also observing Fitts law (ie. the unpin hotspot can/should be larger than the visible ☒ or pin symbol)

(Maybe it's done already) It'd also be great to link to an interaction design document. The current way doesn't just pin the tooltip, it in effect establishes a strong, new modality that overrides everything. Worth comparing it to the more fleeting persistence of such tooltips in Tableau. In any case, it's worth making interaction design choices explicit, and supported with comparisons and arguments

Minor: I'd also rename the PR, because it's more of a pinned thing than a sticky one, and whether the "tooltip" has actions or not is secondary, so I'd just call it "pinned tooltip" or similar. "Sticky" also has the issue that its past participle is "stuck" and that has other connotations (unwanted behavior, like a stuck button)

2022-08-16 15:03 UTC, markov00 commented
Agree with Robert, this only partially is related to the tooltip, this is more a [contextual menu](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) than a sticky/pinned tooltip.

For the interaction/cancellation/clearing it should behave exactly as a right-click context menu in the browser: if you click elsewhere or in one item of the menu,  the menu will disappear immediately

2022-09-16 15:44 UTC, monfera requested changes
I'd like to ask for a refinement in interaction design, the context menu should be more fleeting. Examples:
- I hit the escape key, nothing happens (should clear the thing, I think on any key but definitely on escape, as users expect that, even outside accessibility)
- I can resize the chart area and the tooltip remains (should clear)
- I can visit other browser tabs and applications, interact there and it remains (should clear)

The current concept has unsolved aspects of interaction design, which is expected as the PR is itself also the prototype (may or may not be the most efficient this way). For example, the user can pin the floating, modal context view (it's not a tooltip or a context menu, and I prefer truthful names) and it remains there indefinitely. But the association with the data weakens. It's not obvious which data point the context view relates to. For example, a little arrow triangle at the appropriate part of the context view perimeter could more persistently link the context view to the data point.

I'm also interested in the accessibility concept for this. As it's quite novel, it's not exactly trivial. It'd be great to prototype that before the functionality is released, as there's some chance that the accessibility concept will alter the baseline interaction design. It does not need to be in this PR, just designed before release.

I also got an error when pinning and then trying to scroll with the scrollbar between the chart area and the right-side storybook panel (I wanted to test if scrolling clears the thing): 
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/1548516/190674480-9297b9ab-2851-4c4c-abb6-14d64cbbd3bc.png">

Another issue seems to be related to the fact that canvas resizing is minimized, to avoid thrashing the GL and Canvas2d contexts 60/120 times a second, it's much more expensive than a simple rerender. This chart resizes the canvases in 256 pixel increments. Upon resize, the context view remains in place, losing its adjacency with the data point, then jumps at once when the 256 pixel canvas resize threshold is reached. Though this could be preempted by the above ask of making it more fleeting, such as removing the context view upon resize.

There's also an avoidable warning when pinning:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/1548516/190674646-da1ee31c-699a-49ab-b370-7c079e1d44c5.png">

2022-09-16 16:07 UTC, monfera commented on packages/charts/src/chart_types/flame_chart/internal_chart_state.ts
> +
Nit, this "null value" would fit in one line, blending in with the rest of the file, which is intentionally devoid of real content, all these initial values aren't super informative anyway

2022-09-22 14:50 UTC, nickofthyme reviewed
@monfera thanks for the reviews, here's some direct replies to your comments.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
>   * Side Public License, v 1.
> - activating the tooltip, then, as the next step, trying to activate it elsewhere just clears the pinned tooltip
> - even after clearing (right-click on another bar) it's not possible to pin the tooltip, it requires that the mouse first be moved, probably to populate x/y values (right-click DOM interactions also pass on coordinates, so I think there should be no requirement for a mousemove)
> - activating the tooltip, then left-clicking on another bar (or pretty much anything else, except, apparently, the Esc key or another right-click tooltip activation attempt) doesn't clear the pinned tooltip

These are all good points, I updated the code to fix them or add these interactions.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> modal context view (it's not a tooltip or a context menu, and I prefer truthful names) - @monfera 

> this only partially is related to the tooltip, this is more a [contextual menu](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) than a sticky/pinned tooltip @markov00 

What's the significance of the naming of here? For all intents and purposes it just an extension of our tooltip regardless of the trigger. We are not opening a modal we are pinning/freezing/(insert synonymous verb here) the existing tooltip.

Is this naming for external purposes or internal as well?

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> It's not obvious which data point the context view relates to. For example, a little arrow triangle at the appropriate part of the context view perimeter could more persistently link the context view to the data point.

This is a good _point_ but I think this decision falls on @gvnmagni, that can be added in a later PR

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> I'm also interested in the accessibility concept for this. As it's quite novel, it's not exactly trivial. It'd be great to prototype that before the functionality is released, as there's some chance that the accessibility concept will alter the baseline interaction design. It does not need to be in this PR, just designed before release.

There is currently no accessibility related geoms to even trigger the tooltip. As far as accessibility when the tooltip is open we can improve that with help from the accessibility peeps.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> I also got an error when pinning and then trying to scroll with the scrollbar between the chart area and the right-side storybook panel (I wanted to test if scrolling clears the thing):

Yeah this is related to the `scrollIntoView` logic that sounds like we are going to remove for a different approach.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> Another issue seems to be related to the fact that canvas resizing is minimized, to avoid thrashing the GL and Canvas2d contexts 60/120 times a second, it's much more expensive than a simple rerender. This chart resizes the canvases in 256 pixel increments. Upon resize, the context view remains in place, losing its adjacency with the data point, then jumps at once when the 256 pixel canvas resize threshold is reached. Though this could be preempted by the above ask of making it more fleeting, such as removing the context view upon resize.

This is beyond my understanding, we could zoom about this and find a solution.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> activating the tooltip, then, as the next step, trying to activate it elsewhere just clears the pinned tooltip

This is as designed, as we demoed the chrome context menu. When you open the context menu, then click somewhere else no action is taken requiring a second `click`, or whatever, before it applies that action.

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> even after clearing (right-click on another bar) it's not possible to pin the tooltip, it requires that the mouse first be moved, probably to populate x/y values (right-click DOM interactions also pass on coordinates, so I think there should be no requirement for a mousemove)

@markov00 what do you think about this?

Basically should we activate the hover when the tooltip is unpinned, or wait for the user to move their mouse?

![Screen Recording 2022-09-22 at 07 44 40 AM](https://user-images.githubusercontent.com/19007109/191778566-6fd0ae47-5fe1-4337-9fa1-a7bde96aa1eb.gif)

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> It'd feel odd to maintain the pinned status if the user clicks (eg. left-clicks) elsewhere. A click is a strong expression of intent, whether activating something else or cancelling a current modality. Our interaction design for this should be such that it's super easy to get out of the pinned mode. So, starting with "literally everything gets the user out of pinned mode" then remove hover from that list (I think only a subsequent hover should leave the tooltip pinned)

Yup good points, we changed this to be easily dismissible and less _strong_ 💪🏼 .

2022-09-22 14:50 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> Wondering if the pinned tooltip needs the common ☒ button on the top of the tooltip as another means for cancellation. While also observing Fitts law (ie. the unpin hotspot can/should be larger than the visible ☒ or pin symbol)

This was decided as not necessary

2022-09-22 16:26 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/internal_chart_state.ts
> +
See f7b05f6

2022-09-22 17:22 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
A similar interaction is used in the current flame chart for `click` action. Notice when you click the chart focuses the selected element but the cursor lands on a value and the position is not updated until the cursor is moved.

![Screen Recording 2022-09-22 at 10 20 45 AM](https://user-images.githubusercontent.com/19007109/191811642-0de38a88-6c4c-40ef-8497-87ee20129250.gif)

2022-09-23 14:04 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
I think we should separate the concept, and consider tooltip only what is visible at hover and we can call context menu what we call now pinned tooltip.
In the long run that pinnet tooltip could be a real context menu that appear when you click on an axis, on a title, on a white space and this is no longer a tooltip, but a real menu.

2022-09-23 14:12 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
IMHO when you are inspecting and using a BI tool you never stop your mouse from moving. It could annoy someone for now, but is definitely a minimal defect for now.
I've double-checked the standard OS behaviour and what happens is:
- if you click a button/link when a context menu is open, the button/link doesn't trigger
- if you right-click on a different place when you already have a context menu open then the context menu just moves to the new right-clicked position
- if you have a context menu is open and you move over a section/button/link/image with a default onHover behavior (like show a tooltip) the tooltip is shown when you click there and make the context menu disappear.

We probably should follow that behavior, but for now, I will put this adjustment as one of the last items on the priority list

2022-09-23 14:12 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
No necessary, exactly, this is a non standard  behaviour for context menu.

2022-09-23 16:54 UTC, markov00 commented on packages/charts/src/components/tooltip/components/tooltip_wrapper.tsx
> +            setTimeout(onSelect, 0, selected);
If I'm not wrong the `onSelect` takes 2 arguments, the selected and the all items array.
ESLint is also shouting on that line

2022-09-23 16:54 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/tooltip.ts
> +            displayOnly: true,
By default this and the X value should be selectable and the cell value not.

Since both axes' values don't have a color we can probably use something like a neutral color. In @gvnmagni's animations the filters are just actions on the values directly and nothing was selectable, but in this first step we can just have them selectable
<img width="285" alt="Screenshot 2022-09-23 at 18 34 26" src="https://user-images.githubusercontent.com/1421091/192009457-a9ca0f33-b40a-4882-b9fc-c4968cf8a5b8.png">

2022-09-23 16:54 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> +    this.onTooltipPinned(!this.tooltipPinned);
I think we should mark the tooltip pinned only if we are over a node, if not it cause an issue:
if you try to click on a white area, the tooltip doesn't appear anymore until you press esc or click somewhere

2022-09-23 16:54 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> +    }
I see the pain of rewriting this logic :(

2022-09-23 16:54 UTC, markov00 commented on packages/charts/src/components/tooltip/components/tooltip_table_body.tsx
> +
We should get rid of this and use the other visibility method defined:
- show up to 5 series
- if more then 5, then show only the highlighted ones (up to 5)
- everything else is shown in the context menu

This mean that the context menu is available not only if there are actions but also if there are more then 5 series

2022-09-23 17:24 UTC, nickofthyme commented on packages/charts/src/components/tooltip/components/tooltip_table_body.tsx
> +
Yes working on this now.

I think _five_ is arbitrary since the items can overflow and increase the height size of each row independently.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/19007109/192022721-4831bbc7-ed53-4231-92b4-75e01e32010e.png">

2022-09-26 07:40 UTC, gvnmagni commented on packages/charts/src/components/tooltip/components/tooltip_table_body.tsx
> +
good point

2022-09-26 07:41 UTC, gvnmagni commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
I genuinely lack some context I'm afraid! 😄

2022-09-28 15:13 UTC, nickofthyme commented on packages/charts/src/components/tooltip/components/tooltip_wrapper.tsx
> +            setTimeout(onSelect, 0, selected);
See 06cc1ac

2022-09-29 16:29 UTC, flash1293 commented
It seems like if there is a custom tooltip bit, it won't render the "right click to stick" message anymore:
<img width="477" alt="Screenshot 2022-09-29 at 18 18 25" src="https://user-images.githubusercontent.com/1508364/193087248-039939da-916e-4bae-bcc6-8ebce955f6b3.png">

It still works though:
<img width="398" alt="Screenshot 2022-09-29 at 18 18 29" src="https://user-images.githubusercontent.com/1508364/193087255-41a025ea-db36-46f1-a758-b68218bd02e0.png">


Maybe I'm using it wrong

2022-09-29 17:28 UTC, nickofthyme commented
@flash1293 Nope you are correct, I am working on adding support for the `customTooltip` option.

2022-09-30 07:16 UTC, flash1293 commented
Not sure whether this is some kind of bug with my way of loading this branch, but the actions are not typed: 
<img width="406" alt="Screenshot 2022-09-30 at 09 15 45" src="https://user-images.githubusercontent.com/1508364/193213082-eb757d5c-3a7e-42ec-b56c-ac443df1fd1a.png">

2022-10-05 07:56 UTC, flash1293 commented
I tested a bit more and the current api is a bit limiting. There can only be one set of actions for a chart no matter what value the user clicked. This is an assumption that holds true most of the time, but not necessarily always.

Also due to this setup it's not possible to only fetch some information if the user is actually opening the tooltip which might be necessary at some point (we could work around it right now, but not forever) - for example we might want to disable an action if a certain saved object is created already, but we need to check with an additional request. We can only send this request if the user actually pinned the tooltip - right now there is no place to do this

What I'm suggesting is instead of a prop which takes a list of actions, having a prop which takes a component to render the actions on its own

e.g. like this:
old:
```
  actions: {[ label: "abc", onSelect: (values) => handleClick(values) ]}
```

new:

```
import { TooltipAction } from '@elastic/charts';

function TooltipActions(values) {
  useEffect(() => {
    // some async stuff
  })
  return <>
    <TooltipAction label="abc" onClick={() => handleClick(values)}>
  <>
}

// ...
actions: {TooltipActions}
```

it will also come in handy later for having more sophisticated interactivity in there instead of just a list of links to click (I remember some mockups with mini-forms in there).

Let me know what you think.

2022-10-11 23:22 UTC, nickofthyme commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
@gvnmagni I think the ask here is should we have a carrot UI on the tooltip to point to the selected element(s).

![Image 2022-10-11 at 4 19 52 PM](https://user-images.githubusercontent.com/19007109/195215957-dbcab80b-bd38-456f-bd7b-734bc2ec15e4.jpg)

2022-10-11 23:23 UTC, nickofthyme commented on packages/charts/src/components/tooltip/components/tooltip_table_body.tsx
> +
Fixed by UI to truncate values until pinned to a fixed height and configurable number of max elements, this would default to 5 (+ ½) items in the tooltip.

2022-10-12 00:16 UTC, nickofthyme commented
@monfera I'm getting an issue where pinning the tooltip then quickly clicking outside of the chart, causes the chart to go blank on the next render and following renders.

![Screen Recording 2022-10-11 at 05 10 44 PM](https://user-images.githubusercontent.com/19007109/195220606-37e8bbc1-8a19-4415-a86d-7274f3399a5b.gif)

I believe it is somehow related to `contextRestoreHandler` specifically the code in the `setTimeout` below. Increasing this timeout makes it easier to trigger the blank chart (i.e. time to pin and blur chart). Any thoughts on why this maybe the case?

https://github.com/elastic/elastic-charts/blob/accb50a790c1785c8b691e66f52587a88611dd66/packages/charts/src/chart_types/flame_chart/flame_chart.tsx#L1192-L1195

2022-10-13 14:06 UTC, markov00 commented
> 98f5436

Hey @nickofthyme this https://github.com/elastic/elastic-charts/pull/1782/commits/98f5436fafacba186c1a582b53f89b1e1816c045 should solve the issue. You where registering a mousemove listener when handling the context menu click. This cause the `handleMouseDragMove` to be called making the glitch to appear. You can better reproduce the problem by right-click on a node and by dragging outside the context menu.

2022-10-24 19:35 UTC, nickofthyme commented
@gvnmagni These changes are nearly code complete, just fixing up the code checks and doing a final check on screenshots. Please take a look at let me know if there are any changes you'd like to make. I am missing a few colors for the dark mode namely the tooltip hover highlighter color and the action text color. If they are the same that's fine just want to make sure as the figma colors don't match any of the eui color values [here](https://eui.elastic.co/#/theming/colors/values).

2022-10-24 19:45 UTC, nickofthyme commented
buildkite update vrt

2022-10-25 10:39 UTC, gvnmagni commented
Thank you Nick! I believe @markov00 is already working on both the colors and will be fixed soon!

2022-10-26 08:00 UTC, gvnmagni approved these changes

2022-11-01 18:55 UTC, nickofthyme commented
buildkite update vrt

2022-11-02 04:04 UTC, nickofthyme commented
buildkite update vrt

2022-11-02 16:14 UTC, nickofthyme commented on packages/charts/src/components/tooltip/components/_tooltip.scss
> +      background-color: transparentize($euiColorLightShade, 0.5);
This does not work because the `__tableRow` has `display: contents` for sizing the grid columns. So it must be applied to the children.

```suggestion
      .echTooltip__tableCell:not(.echTooltip__colorCell),
      .echTooltip__colorCell .echTooltip__colorStrip--spacer {	
        background-color: transparentize($euiColorLightShade, 0.5);	
      }
```

2022-11-03 16:34 UTC, markov00 commented
> ## Deployments - [f4d0656](https://github.com/elastic/elastic-charts/commit/f4d065613cede38c85797c5214ddccb1f8b5c7a5)
> * Storybook ([link](https://ech-e2e-ci--pr-1782-aq31oo2m.web.app))
> * e2e server ([link](https://ech-e2e-ci--pr-1782-aq31oo2m.web.app/e2e))
> * Playwright report ([link](https://ech-e2e-ci--pr-1782-aq31oo2m.web.app/e2e-report))

The changes on the VRTs from master looks good to me and only related to:
- the added tooltip border
- a tooltip rendered with the prompt if the list of values where too long

2022-11-03 16:36 UTC, markov00 commented
buildkite update screenshots

2022-11-03 16:37 UTC, nickofthyme commented
buildkite update vrt

2022-11-03 17:45 UTC, nickofthyme commented
buildkite update vrt

2022-11-03 19:29 UTC, nickofthyme commented
buildkite test this

2022-11-03 21:57 UTC, nickofthyme commented
buildkite test this

2022-11-04 17:03 UTC, nickofthyme commented
buildkite update vrt

2022-11-04 17:28 UTC, nickofthyme commented
buildkite update vrt

2022-11-04 18:07 UTC, nickofthyme commented
buildkite update vrt

2022-11-07 09:27 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
moved to https://github.com/elastic/elastic-charts/issues/1859

2022-11-07 09:29 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
added to https://github.com/elastic/elastic-charts/issues/1859

2022-11-07 09:29 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
> +    this.onTooltipPinned(!this.tooltipPinned);
done

2022-11-07 09:31 UTC, markov00 commented on packages/charts/src/chart_types/flame_chart/flame_chart.tsx
>   * Side Public License, v 1.
added to https://github.com/elastic/elastic-charts/issues/1859

2022-11-07 14:00 UTC, markov00 requested changes
Everything looks good expect for the fact that the `control+click` on mac doesn't works as expected. It initially pins the tooltip but a subsequent mouse movement will unpin the tooltip.
`control+click` should follow the same behaviour of the `secondary click` on mac (usually the two finger click)

2022-11-07 17:56 UTC, nickofthyme commented
> Everything looks good expect for the fact that the `control+click` on mac doesn't works as expected. It initially pins the tooltip but a subsequent mouse movement will unpin the tooltip. `control+click` should follow the same behaviour of the `secondary click` on mac (usually the two finger click)

Good catch, fixed in 0367fed

2022-11-08 10:25 UTC, markov00 approved these changes
Everything looks good to me, amazing work Nick!

2022-11-08 16:18 UTC, merged