feat(heatmap): small multiples
elastic/elastic-charts pull request #1933
Opened 2023-01-12 17:04 UTC by nickofthyme

## Summary

## Details

## Issues

### Checklist

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [ ] The `:theme` label has been added and the `@elastic/eui-design` team has been pinged when there are `Theme` API changes
- [ ] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

2023-02-08 15:32 UTC, nickofthyme commented on .eslintrc.js
> +        // alphabetize: { order: 'asc', caseInsensitive: true }, // todo replace with directory gradient ordering
This was causing differences between my VScode eslint fixer and the cli fixer. Not sure what's going on but best to comment it out for now.

2023-02-14 13:42 UTC, markov00 commented on .eslintrc.js
> +        // alphabetize: { order: 'asc', caseInsensitive: true }, // todo replace with directory gradient ordering
Are you up-to-date with the dependencies? in particular with eslint I've noticed similar issues in the past

2023-02-15 02:32 UTC, nickofthyme commented on .eslintrc.js
> +        // alphabetize: { order: 'asc', caseInsensitive: true }, // todo replace with directory gradient ordering
I'll check...

2023-02-15 02:32 UTC, nickofthyme commented
buildkite update vrt

2023-02-15 04:23 UTC, nickofthyme commented
buildkite update vrt

2023-02-24 21:17 UTC, nickofthyme commented
buildkite update vrt

2023-02-24 21:20 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +    const rightIndex = xValues.indexOf(endValue) + 1;
I'm not sure what the point of using `bisect` was here other than bigO performance, but this was causing a lot of issues related to brushing. Namely selecting the wrong end index, always one short of the desired index.

2023-02-24 21:21 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
>      const isLeftOutOfRange = leftIndex > xValues.length - 1 || leftIndex < 0;
I don't know if this logic for `isRightOutOfRange` and `isLeftOutOfRange` is still needed or what its purpose was. I think it may have been related to the `bisect` logic but I think it's safe to remove.

2023-02-28 04:43 UTC, nickofthyme commented
buildkite update screenshots

2023-02-28 15:12 UTC, markov00 reviewed
I've done a general code review + tested on storybook the small multiple story.
It looks pretty stable and works fine, but I'd like to check a bit more some edge cases and configurations (like chart padding/margin, label text/formats etc)
I've left a few comments, none of them related to issues/bugs, but mostly questions

2023-02-28 15:17 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
>      const isLeftOutOfRange = leftIndex > xValues.length - 1 || leftIndex < 0;
The logic here just picks always a value within the scale, even if, due to some circumstances, the indices are out of range (-1 for missing index, and > length for the "leftIndex") this will always pick something within the scale domain

2023-02-28 15:17 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +    const rightIndex = xValues.indexOf(endValue) + 1;
You are right, no need to keep bisect here

2023-02-28 23:49 UTC, nickofthyme commented on .eslintrc.js
> +        // alphabetize: { order: 'asc', caseInsensitive: true }, // todo replace with directory gradient ordering
Ok it's consistent now, I reverted the config change and ran an auto fix to revert the changes.

2023-03-02 22:26 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +export function getPerPanelMap<T>(
I don't think so, this was the previous naming. `Map` here refers more to the verb mapping not so much map. But it could be named better, maybe `mapOverPanels` or something.

2023-03-02 22:28 UTC, nickofthyme commented on .eslintrc.js
> +        // alphabetize: { order: 'asc', caseInsensitive: true }, // todo replace with directory gradient ordering
Fixed with 7bb0da7 and b16295f

2023-03-02 22:34 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/get_debug_state.ts
> +    const [heatmapViewModel] = geoms.heatmapViewModels;
Yeah this is only for the Axes though because they are all the same. I tried to limit too many changes to this type but happy to make this an array of axes but they would all be identical if and until the axes are allowed to be heterogenous between rows and columns.

Also updated the use of `cellFontSize` in 858c3dbfc102a20e85859d2f29407cd6404ff54a

2023-03-02 22:36 UTC, nickofthyme commented on packages/charts/api/charts.api.md
> +//
Yup, I also exported `HeatmapCellDatum`. See 48a62a529d0b68de5ead2d71fc52017d3c5e1317

2023-03-02 22:41 UTC, nickofthyme commented on packages/charts/src/utils/common.tsx
> +  if (offset) return clamp(value, lowerBound + offset, upperBound + offset) - offset;
Yeah, I thought you might say that. I'm fine pulling it out. See c73adf3a30d41e70a3a23ee03d7ac849a18a408e

2023-03-02 22:45 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_element_sizes.ts
> +      : yValueCount;
I'm not sure, I struggled to get this limiting height to work for small multiples with out causing a circular reference between selectors. Maybe we can chat about this on Monday?

2023-03-02 22:56 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/utils/axis.ts
> +/*
That's correct, This is part of the solution to the 🐔 & 🥚 situation for the axes dimensions. Having all this in a single selector would cause a circular reference so I split `compute_chart_dimensions.ts` apart and added `compute_chart_element_sizes.ts`. There is a bit of code duplication between them and these utils are an attempt to limit this but I'm at a loss for a better solution. I'm certainly open to suggestions!

2023-03-02 22:58 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/renderer/canvas/canvas_renderers.ts
> +            ctx.translate(x, y);
Good point, removed in cd5b7653b2c346d7285cbf96544c9e9ffdf55fdc

2023-03-02 23:07 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +  horizontalValue: any,
Yeah good catch, this was pre-existing code. See bc926981a5eb99455a97287e4f010e54c0f7bb5a.

https://github.com/elastic/elastic-charts/blob/3992759f7377a54a71b25a0758bf9ed6ca2eab63/packages/charts/src/chart_types/xy_chart/state/selectors/compute_per_panel_axes_geoms.ts#L24-L34

2023-03-02 23:08 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +  smVerticalAccessorValue?: string | number;
Good call bc926981a5eb99455a97287e4f010e54c0f7bb5a

2023-03-02 23:08 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +  verticalValue: Value;
Yup 👍🏼 bc926981a5eb99455a97287e4f010e54c0f7bb5a

2023-03-02 23:13 UTC, nickofthyme commented on packages/charts/src/scales/scale_band.ts
> +  }
Yeah, this was strange to me because of how the `ScaleBand` class handles an `inputDomain` of zero length.

https://github.com/elastic/elastic-charts/blob/3992759f7377a54a71b25a0758bf9ed6ca2eab63/packages/charts/src/scales/scale_band.ts#L64

2023-03-02 23:14 UTC, nickofthyme commented on packages/charts/src/scales/scale_band.ts
> +  }
But basically the `isNullDomain` is to check if the `inputDomain` was zero length. Any ideas how to make this better?

2023-03-02 23:15 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +  domain.length > 0 && domain[0] !== undefined;
Not sure let me look into this more...

2023-03-06 08:13 UTC, markov00 commented on packages/charts/src/utils/common.tsx
> +  if (offset) return clamp(value, lowerBound + offset, upperBound + offset) - offset;
Great thanks

2023-03-06 08:25 UTC, markov00 commented on packages/charts/src/scales/scale_band.ts
> +  }
Oh I see, now I remember, I think this is tech debt that we introduced when operating with small multiples: a domain with just a single `undefined` element in it is used to handle every chart as a small multiple (considering for example a single chart as a small multiple of 1 element).

We should probably write that in some comments and doc about that function, open an issue and track the rename/refactoring in a different PR

2023-03-06 08:29 UTC, markov00 commented on packages/charts/src/common/panel_utils.ts
> +export function getPerPanelMap<T>(
Isn't the return type an array of `PerPanelMap`? so in my broken English I'm getting a set of "perpanelmap"s but my genitive use is not the proper one :D

2023-03-06 08:32 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/utils/axis.ts
> +/*
It is all good to me, just wondering if I read the code correctly

2023-03-06 08:33 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/get_debug_state.ts
> +    const [heatmapViewModel] = geoms.heatmapViewModels;
you are right, agree we don't need to change it much.
It will definitely change in the future when we allow relative scales on small multiples

2023-03-06 08:34 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_element_sizes.ts
> +      : yValueCount;
sure, let's have a chat

2023-03-06 13:58 UTC, markov00 requested changes

2023-03-06 13:58 UTC, markov00 commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +    const rightIndex = xValues.indexOf(endValue) + 1;
Hey @nickofthyme I think there still an issue here: the picked area now is always 1 cell more than requested.

https://user-images.githubusercontent.com/1421091/223130506-4cc83fdc-43c4-4a7d-b02a-df7ae78d90a5.mov

2023-03-07 18:56 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/state/selectors/compute_chart_element_sizes.ts
> +      : yValueCount;
Ok I removed all pagingation-esque code logic in 697e53c

2023-03-07 19:04 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +export function getPerPanelMap<T>(
Just gonna keep this as-is for now.

2023-03-07 19:16 UTC, nickofthyme commented on packages/charts/src/scales/scale_band.ts
> +  }
Added note here b4687cf and opened #1990

2023-03-07 19:17 UTC, nickofthyme commented on packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts
> +    const rightIndex = xValues.indexOf(endValue) + 1;
Fixed in c865acc

2023-03-07 19:41 UTC, nickofthyme commented on packages/charts/src/common/panel_utils.ts
> +  domain.length > 0 && domain[0] !== undefined;
You are correct, I just removed `isNullDomain` in favor of `hasSMDomain`, see 8857c44

2023-03-08 13:47 UTC, markov00 approved these changes
I tested the changes and the brushing error seems solved.
There still some wrong screenshots about the newly added story probably due to a missing fixed random seed.
Everything else looks good to me

2023-03-08 16:41 UTC, nickofthyme commented
buildkite update screenshots

2023-03-08 16:56 UTC, nickofthyme commented
buildkite update screenshots

2023-03-08 17:17 UTC, nickofthyme commented
buildkite update screenshots

2023-03-08 22:55 UTC, nickofthyme commented
buildkite update screenshots

2023-03-09 19:57 UTC, nickofthyme commented
buildkite test this

2023-03-10 23:36 UTC, merged