docs: remove legacy unused docs
elastic/elastic-charts pull request #2003
Opened 2023-03-23 09:47 UTC by markov00

## Summary

This PR removes the docs, created years ago and never published.
It also removes the storybook docs addon that was used for these docs.

2023-03-23 10:51 UTC, stratoula commented
I love PRs that remove code 😍

2023-03-23 18:01 UTC, markov00 commented
> I love PRs that remove code 😍

hehe, this actually removes docs but those are legacy docs :D

2023-03-23 18:30 UTC, nickofthyme requested changes
Everything looks good regarding the `/docs` removal. But the `docs` addon needs to stay if we still want the story source tab to work.

2023-03-23 18:30 UTC, nickofthyme commented on storybook/main.js
>      '@storybook/addon-knobs',
This needs to stay, the `docs` addon is required for the `storysource` to work.

PS: @stratoula another reason I loath storybook, took me DAYS to figure this out back in the day!

2023-03-23 18:30 UTC, nickofthyme commented on storybook/parameters.ts
> -    },
I think we put this back too

2023-03-24 07:59 UTC, stratoula commented on storybook/main.js
>      '@storybook/addon-knobs',
I feel your pain Nick :D

2023-03-24 09:33 UTC, markov00 commented on storybook/main.js
>      '@storybook/addon-knobs',
oh really??? come on storysource, you can handle that yourself.... you don't need everything else

2023-03-24 18:08 UTC, nickofthyme approved these changes

2023-03-27 10:29 UTC, merged