[tooltip] increase tooltip width to 500px and truncate items to 2 lines
elastic/elastic-charts pull request #2261
Opened 2023-11-28 14:10 UTC by mbondyra

## Summary

Fixes https://github.com/elastic/elastic-charts/issues/2048 (I am not sure if we consider this issue fixed after merging this one)

Auto-expands the tooltip containter to 500px for wider content. The data items in the tooltip now truncate to 2 lines instead of just one.

2023-11-28 14:33 UTC, markov00 commented on packages/charts/src/components/tooltip/components/_tooltip.scss
> +    overflow: hidden;
you can probably use also the `lineClamp` sass mixin, it has a few more properties but it should work

2023-11-28 14:40 UTC, mbondyra commented on packages/charts/src/chart_types/metric/renderer/dom/_text.scss
> -@mixin lineClamp($maxLines) {
this was not used in any place so I moved it to generic mixins

2023-11-28 17:28 UTC, markov00 requested changes

2023-11-28 19:29 UTC, mbondyra commented
Thank you @markov00 great tips! I addressed all your comments! 🙇🏼‍♀️

2023-11-29 09:09 UTC, markov00 approved these changes
Changes looks good to me, tested on deployed storybook.
Just re-generate the changed screenshots from the CI rather than from the local machine to correctly match with what the CI is going to match.

2023-11-29 09:11 UTC, mbondyra commented
buildkite update vrt

2023-11-29 10:32 UTC, merged