chore(bullet): bullet improvements, bug fixes and renaming
elastic/elastic-charts pull request #2319
Opened 2024-01-29 19:21 UTC by nickofthyme

## Summary

Fixes a few bugs, adds features for bullet replacement and does a little cleanup.

- [x] Fix bug related to colors on metric mode, see #2244
- [x] Renames `BulletGraph` to `Bullet` to stay consistent with other chart naming and remove redundant verbiage.
- [ ] Adds support for independent ticks and color bands, see #2307.

## Issues

fixes #2244
closes #2307

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] New public API exports have been added to `packages/charts/src/index.ts`
- [ ] Unit tests have been added or updated to match the most common scenarios
- [ ] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)
- [ ] Visual changes have been tested with `light` and `dark` themes

2024-02-02 02:09 UTC, nickofthyme commented
buildkite update screenshots

2024-02-05 15:46 UTC, nickofthyme commented
@markov00 could you take a look at this when you have time?

2024-02-09 11:05 UTC, markov00 requested changes

2024-02-09 11:05 UTC, markov00 commented on e2e/tests/bullet_stories.test.ts
I'm not sure why, but looking at the color story seems that configuration number 2 ("array of colors via palettes" there is also a typo in the name) doesn't seem to reflect the the config steps.

2024-02-09 21:36 UTC, nickofthyme commented
buildkite update screenshots

2024-02-09 21:52 UTC, nickofthyme commented on packages/charts/src/chart_types/bullet_graph/utils/color.ts
> +  ) as ScaleInputs;
> Concerning `} as ScaleInputs`

I must have forgot about doing that and it was not correctly conforming. I ended up fixing the logic for the Complex color band config so that it can also have independent ticks. So this code/typing has been addressed and fixed in a better way.

2024-02-09 21:52 UTC, nickofthyme commented on packages/charts/src/chart_types/bullet_graph/utils/color.ts
> +  ) as ScaleInputs;
> It also probably create the following issue visible in the chart where the last color band exceeds the chart size

Yes I saw this too and fixed it to clamp all start and end values to not exceed the domain.

2024-02-09 21:58 UTC, nickofthyme commented on packages/charts/src/chart_types/bullet_graph/utils/color.ts
> +  ) as ScaleInputs;
> There is also the second problem where there is always a color even if I've added an "empty" space between the first and second color band

I assume you are referring to when the consumer would define a complex color config and leave a **gap** in the ranges. Say for example your ranges are `0 -> 20` - `30 -> 40` - `40 -> 100`. You'd end up with something like below with a gap from `10 -> 20`.

<img width="564" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/23fc571b-f2ab-422d-9f63-37853c874309">

I think I mentioned this last time we talked saying that this complex config does little verification or correcting of the config we receive and we assume it to be correct namely the following:
- All ranges are ordered from min to max
- All ranges are compatible with each other such that there is no overlapping or excluded ranges
    
Ideally we validate the config and fix it the best we can based on what is provided, filling or clamping as needed. But I think this could be a future enhancement as this is not yet used.

2024-02-09 22:03 UTC, nickofthyme commented on e2e/tests/bullet_stories.test.ts
Not sure what you mean by this? I have this config 2 pulling from a list of palettes which are an array of colors.

Typo fixed in ba6616e 😅

2024-02-09 22:05 UTC, nickofthyme commented on packages/charts/src/utils/common.tsx
> +type SortTestFn = (n1?: number, n2?: number) => boolean;
Good catch! Fixed it in 8fbde1b and added tests for the `descending` case.

2024-02-09 22:35 UTC, nickofthyme commented
buildkite update screenshots

2024-02-12 22:23 UTC, nickofthyme commented
buildkite update screenshots

2024-02-12 22:26 UTC, nickofthyme commented
buildkite update screenshots

2024-02-13 10:11 UTC, markov00 commented on packages/charts/src/chart_types/bullet_graph/utils/color.ts
> +  ) as ScaleInputs;
discussed offline

2024-02-13 15:31 UTC, merged