[Legend] Provide interaction label helps via API
elastic/elastic-charts pull request #2418
Opened 2024-04-29 09:59 UTC by dej611

## Summary

Provide a new prop for legend interactions in the `Settings` component.

<img width="1137" alt="Screenshot 2024-04-29 at 11 52 59" src="https://github.com/elastic/elastic-charts/assets/924948/ca750f65-2a26-4a4b-9ec8-07b3dd8faef4">

## Details

The new `legendItemLabels` prop provides a set of labels to extends the current interaction label helps for component consumers to provide better messaging on interactions.
As nice side effect this change makes it possible to properly handle the i18n side of messaging making the consumer responsible for that.

## Issues

This is a complementary feature of #2385

### Checklist

- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] The proper documentation and/or storybook story has been added or updated

2024-04-29 13:52 UTC, dej611 commented
buildkite update screenshots

2024-04-30 04:04 UTC, nickofthyme commented
buildkite update screenshots

2024-04-30 13:57 UTC, markov00 requested changes
I don't think we need this for now, we have multiple other strings that need to be i18nzed so I believe we should consider a more general approach than a scoped i18n set of labels just for the legend here.
For now is also fine having hardcoded english strings. We should then provide a way to internationalize tokens like EUI is doing

2024-05-02 10:01 UTC, dej611 commented
buildkite update screenshots

2024-05-14 16:37 UTC, markov00 commented on packages/charts/src/components/legend/label.tsx
> +
Now we can just change this to the right text (CTRL or Command) and we can merge this PR

2024-05-15 07:44 UTC, dej611 commented on packages/charts/src/components/legend/label.tsx
> +
Merged latest `main` and changed the modifier key with [7aa871c](https://github.com/elastic/elastic-charts/pull/2418/commits/7aa871c2b96d9980a2b1fad452226c5bb1de9020)

2024-05-15 10:53 UTC, markov00 commented on packages/charts/src/components/legend/label.tsx
> +
This guidance should reflect the current hide/show logic that depends on the number of visible/hidden series. not just on the current series visibility status.
This for example shows a wrong message:
<img width="362" alt="Screenshot 2024-05-15 at 12 50 48" src="https://github.com/elastic/elastic-charts/assets/1421091/9fbf0e38-fa54-415d-8ce2-ed0b0103acdf">
The click will just show the series, like the cmd+click because.

2024-05-15 12:03 UTC, dej611 commented on packages/charts/src/components/legend/label.tsx
> +
Fixed via [5136ced](https://github.com/elastic/elastic-charts/pull/2418/commits/5136cedc7bdf30a88ccab6b54a81869795177a0f)
Also added a E2E to check it on various stages to avoid future regressions with [62fe3da](https://github.com/elastic/elastic-charts/pull/2418/commits/62fe3da35f5e36978875e1f1a356d8c0ee3f18fe)

2024-05-16 09:31 UTC, markov00 approved these changes
All good for me, works as expected!

2024-05-17 08:34 UTC, merged