fix (Metric): chart not rendered when the trend is empty
elastic/elastic-charts pull request #2447
Opened 2024-05-30 15:28 UTC by alexwizp

Closes: https://github.com/elastic/elastic-charts/issues/2445

## Summary

This change ensures that the chart component can handle `empty` trend data appropriately, preventing rendering failures and console errors.

## Screen 

Screen:

`Trend was set to []`

<img width="1669" alt="image" src="https://github.com/elastic/elastic-charts/assets/20072247/56a60143-5145-4f0f-b9b2-6c4e72f222cf">

No `console` issues

2024-05-30 16:49 UTC, markov00 requested changes
This doesn't solve the issue completely.

The root cause is a couple of lines below that changed line where:
```
  const [xMin, xMax] = [sortedTrendData.at(0)!.x, sortedTrendData.at(-1)!.x];
```
We need to avoid these type of assertions because they can cause all sort of issues around them (cc @dej611)

Even if with a single element the chart renders, the SVG is malformed (will contain NaN numbers that throws in the console).

The correct fix should check if the trend contains at least 2 elements. If not you should assure a correct background/foreground color selection (changing it to `if(trend.length < 2) return null` doesn't solves it quickly unfortunately)

2024-05-30 16:49 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  if (!trend?.length) {
there is no need for the optional chaining. `trend` is always an array in typescript

2024-05-30 18:21 UTC, alexwizp commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  if (!trend?.length) {
@markov00, the optional chaining is used here because we already have this condition checked before. However, based on your comment, I see that the correct fix should be more complex. Could someone more involved in the `Chart` project prepare a fix for this?

I believe this issue is the reason for the flaky `CI` in `Kibana`.

2024-05-30 18:54 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  if (!trend?.length) {
Yeah I can take a look. Thanks @alexwizp

2024-05-31 03:49 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  if (!trend?.length) {
@markov00 Check new changes.

2024-05-31 03:52 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> -  }
I removed this `null` return completely and let it just render what it can given the computed values. This only renders sparklines for trend with 2 or more values.

If we block this it does not render the require `Sparkline` elements to property fill the metric, see first (white) metric in the demo below...

<img width="716" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/869a87dc-1fd8-4eb0-bb59-8d97b25f6971">

When it should look like...

<img width="711" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/36106f00-76de-4caf-b70f-4667774e42cd">

2024-05-31 03:53 UTC, nickofthyme commented
buildkite update screenshots

2024-05-31 08:16 UTC, markov00 requested changes

2024-05-31 08:16 UTC, markov00 commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  const xMax = sortedTrendData.at(-1)?.x ?? NaN;
this doesn't solves the problem either.
if the trend has 1 only value then the x scale will first do a division by zero then it returns NaN on the path generation causing the SVG to errors out with something like `MNaN,0LNaN,1Z`

2024-05-31 09:30 UTC, alexwizp commented
@markov00  what if we base our logic for showing the trend on meeting two conditions: the difference between `xMin` and `xMax` should not be 0, and `yMax` should not be zero either? I think it will be more correct instead of  checking the length of `trend`/`sortedTrendData`.

2024-05-31 15:59 UTC, nickofthyme approved these changes
New changes LGTM, let's see what @markov00 thinks.

2024-05-31 16:03 UTC, nickofthyme commented on packages/charts/src/chart_types/metric/renderer/dom/sparkline.tsx
> +  const xMax = sortedTrendData.at(-1)?.x ?? NaN;
Good point, I didn't check the console errors. Looks like the latests changes fix this.

2024-06-03 16:07 UTC, markov00 approved these changes
LGTM, thanks for taking care of it

2024-06-03 16:08 UTC, merged