feat(bar_chart): add Alignment offset to value labels
elastic/elastic-charts pull request #784
Opened 2020-08-19 09:53 UTC by dej611

Make it possible to position value labels based on bar relative geometry

## Summary

This is a draft proposal for value label positioning within the bar chart with relative alignment.

![value-positioning](https://user-images.githubusercontent.com/924948/90619969-2a964000-e212-11ea-95ee-167ce17f5e65.gif)

There are still some open questions, such:
* [ ] what should the `default` value be? Each chart rotation configuration has its own default alignment, so, for the moment, I've just extended the `TextAlignment` in this scenario to handle `undefined` values
* [ ] Should explicit positioning have a different behaviour from similar "default" positioning?
  * for instance when there are short bars the default configuration may propose an "overlapping" solution, but what about explicit alignment?

### Checklist

- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2020-08-24 13:16 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +  let alignmentOffsetY = 0;
We can probably simplify this if:
- we create a utility function that rotates the `BarGeometry` or better it's simplified version `Rect` so that we can apply the same alignment independently from the rotation
- we can also split the computation of vertical alignment by the horizontal alignment to reduce the scope of each function

2020-08-24 13:35 UTC, dej611 commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +  let alignmentOffsetY = 0;
I get the first bit,

> we can also split the computation of vertical alignment by the horizontal alignment to reduce the scope of each function

but can you expand on this?

2020-08-25 07:50 UTC, markov00 commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +  let alignmentOffsetY = 0;
Instead of having both the alignmentOffsetX and alignmentOffsetY computed on the same function, you can split it into two functions:
`computeAlignmentOffsetX` and `computeAlignmentOffsetY`

2020-09-29 08:55 UTC, markov00 requested changes
Everything seems to work fine except for a 180 degree rotation where: the vertical alignment is not working well
<img width="889" alt="Screenshot 2020-09-29 at 10 52 06" src="https://user-images.githubusercontent.com/1421091/94535629-15192a80-0242-11eb-9a87-9adf185edd0a.png">
<img width="906" alt="Screenshot 2020-09-29 at 10 51 59" src="https://user-images.githubusercontent.com/1421091/94535633-15b1c100-0242-11eb-85b7-2d1d9d06e193.png">


<img width="881" alt="Screenshot 2020-09-29 at 10 52 12" src="https://user-images.githubusercontent.com/1421091/94535618-121e3a00-0242-11eb-836c-8279e20db4a4.png">

Also please note that the `debug` rectangle doesn't reflect the alignment: try to flag the `debug` check on the label story and you will see the issue when changing the alignment

2020-09-29 16:01 UTC, nickofthyme commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +};
Yeah I don't think this is necessary, we could just make a comment on each of the switch cases below. Unless you are planning to expose this constant to the consumer for simplicity.

2020-09-29 16:04 UTC, nickofthyme reviewed
Tested locally and works great, just left a few comments.

2020-09-29 16:20 UTC, dej611 commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +};
Yes, the original idea was to export them as they may be more readable than numbers.
Not really in the scope of this PR, but they helped to code the solution giving some more semantic.

2020-09-29 17:09 UTC, nickofthyme commented on src/chart_types/xy_chart/renderer/canvas/values/bar.ts
> +};
If that's the case I think we should rename the enum from `CHART_ROTATION` to something more descriptive.

2020-10-12 11:41 UTC, markov00 approved these changes
LGTM, adding some functional test will be great to avoid regressions:
please take a look at: `integration/tests/interactions.test.ts` on how to create VRTs with different knob options

2020-10-12 20:36 UTC, wylieconlon reviewed
Works well!

2020-10-13 13:11 UTC, merged

2020-10-19 13:49 UTC, markov00 commented
:tada: This PR is included in version 24.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v24.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/24.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: