feat: blind sorting option for vislib
elastic/elastic-charts pull request #813
Opened 2020-09-09 16:06 UTC by nickofthyme

## Summary

Allows a blind sorting option on `Settings` called `vislibSort` to loop through all `yAccessors` then all the data.

This option is bind as in not added to the `SettingSpec` to avoid usage, outside of vislib, until #795 allows a sorting alternative.

## Screenshot
![Screen Recording 2020-09-09 at 10 50 AM](https://user-images.githubusercontent.com/19007109/92623654-28ad2300-f28c-11ea-919a-9797b20b63fe.gif)

> Notice the change in the order of the y accessors between the options.

## Sample playground

```tsx
import React from 'react';

import { Chart, Settings, Position, Axis, BarSeries, ScaleType } from '../src';

const data = [
  // Flight Delay Minutes |	Cancelled: Descending |	OriginAirportID: Descending	Count |	Max AvgTicketPrice
  { x: 0, g1: 'false', g2: 'USA', y1: 2, y2: 847.323974609375 },
  { x: 0, g1: 'true', g2: 'Canada', y1: 1, y2: 652.268005371094 },
  { x: 30, g1: 'false', g2: 'Canada', y1: 5, y2: 1127.20959472656 },
  { x: 30, g1: 'true', g2: 'USA', y1: 1, y2: 214.78987121582 },
  { x: 60, g1: 'false', g2: 'Canada', y1: 4, y2: 990.88916015625 },
  { x: 60, g1: 'true', g2: 'USA', y1: 1, y2: 724.3603515625 },
  { x: 90, g1: 'false', g2: 'USA', y1: 3, y2: 951.81787109375 },
  { x: 90, g1: 'true', g2: 'USA', y1: 1, y2: 430.475891113281 },
  { x: 120, g1: 'false', g2: 'Canada', y1: 2, y2: 447.469512939453 },
  { x: 120, g1: 'true', g2: 'Canada', y1: 1, y2: 834.467712402344 },
  { x: 150, g1: 'false', g2: 'Canada', y1: 2, y2: 887.178100585938 },
  { x: 150, g1: 'true', g2: 'Canada', y1: 1, y2: 1176.63818359375 },
  { x: 180, g1: 'false', g2: 'USA', y1: 2, y2: 985.899963378906 },
  { x: 180, g1: 'true', g2: 'Canada', y1: 1, y2: 441.242462158203 },
  { x: 210, g1: 'false', g2: 'Canada', y1: 3, y2: 732.609436035156 },
  { x: 210, g1: 'true', g2: 'USA', y1: 1, y2: 728.790283203125 },
  { x: 240, g1: 'false', g2: 'Canada', y1: 3, y2: 526.108581542969 },
  { x: 240, g1: 'true', g2: 'USA', y1: 2, y2: 759.218139648438 },
  { x: 270, g1: 'false', g2: 'USA', y1: 3, y2: 754.231323242188 },
  { x: 270, g1: 'true', g2: 'Canada', y1: 1, y2: 574.996276855469 },
  { x: 300, g1: 'false', g2: 'Canada', y1: 4, y2: 946.468078613281 },
  { x: 300, g1: 'true', g2: 'Canada', y1: 2, y2: 999.1396484375 },
  { x: 330, g1: 'false', g2: 'USA', y1: 2, y2: 881.044494628906 },
  { x: 330, g1: 'true', g2: 'Canada', y1: 1, y2: 382.457763671875 },
  { x: 360, g1: 'false', g2: 'Canada', y1: 2, y2: 1165.59765625 },
  { x: 360, g1: 'true', g2: 'Canada', y1: 1, y2: 820.462463378906 },
];

export class Playground extends React.Component {
  render() {
    return (
      <div className="testing">
        <div className="chart">
          <Chart className="story-chart">
            <Settings
              // @ts-ignore
              vislibSort
              showLegend
              showLegendExtra
              legendPosition={Position.Right}
            />
            <Axis id="bottom" position={Position.Bottom} title="Bottom axis" showOverlappingTicks />
            <Axis id="left2" title="Left axis" position={Position.Left} tickFormat={(d: any) => Number(d).toFixed(2)} />

            <BarSeries
              id="bars1"
              xScaleType={ScaleType.Linear}
              yScaleType={ScaleType.Linear}
              xAccessor="x"
              yAccessors={['y1', 'y2']}
              splitSeriesAccessors={['g1', 'g2']}
              data={data}
            />
          </Chart>
        </div>
      </div>
    );
  }
}
```

### Checklist

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [x] Unit tests were updated or added to match the most common scenarios

2020-09-09 16:30 UTC, monfera requested changes
Will continue comparing logic after the asked changes are addressed, if it's okay

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
> +      settingsSpec.vislibSort,
Though planned as temporary, let's use a name that tells what it is, even if it's longer, than what's otherwise a temporarily good name that'll become cryptic

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +          return null;
We're in a `forEach`, no need to return a value

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +          return null;
Same

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +    data.forEach((datum) => {
There's a level of code duplication in the branch, it'd be OK to distinguish between the cases in a more fine grained way

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +        return null;
Won't repeat comments on like things as they'd go away upon DRYing up the code

2020-09-09 16:30 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +      yAccessors.forEach((accessor, index) => {
The DRY approach would also favor code review as now it's a bit hard to contrast how the added logic deviates from the preexisting version

2020-09-09 17:14 UTC, nickofthyme commented
@monfera I would normally agree with your approach to be DRY, by maybe pulling the logic into a separate function that handles the checks and adding the value to the `dataSeries` if necessary, This would also require mutation the `dataSeries` Map from this helper function. However, in this case that seems a little excessive for a temporary use case that I imagine will soon be removed in favor of #795.

Would that be ok with you?

2020-09-09 17:17 UTC, nickofthyme commented on src/chart_types/xy_chart/state/selectors/compute_series_domains.ts
> +      settingsSpec.vislibSort,
4355c0d

2020-09-09 17:17 UTC, nickofthyme commented on src/chart_types/xy_chart/utils/series.ts
> +          return null;
4355c0d

2020-09-09 17:17 UTC, nickofthyme commented on src/chart_types/xy_chart/utils/series.ts
> +          return null;
4355c0d

2020-09-09 17:19 UTC, monfera commented
@nickofthyme thanks for the change, I'm fine with temporary non-DRYness there

2020-09-10 07:47 UTC, monfera approved these changes
LGTM, with the understanding that the change is a relatively short term workaround (explaining the avoidance of semantic naming and more DRYness)

2020-09-10 12:55 UTC, merged

2020-09-14 16:50 UTC, markov00 commented
:tada: This PR is included in version 21.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v21.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/21.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: