feat: order ordinal buckets by sum
elastic/elastic-charts pull request #814
Opened 2020-09-09 22:24 UTC by nickofthyme

## Summary

Sort ordinal bucket labels by sum of all bucket values. The `orderOrdinalBucketsBySum` option is added to the `Settings` spec to enable this functionality.

These changes only affects `Ordinal` scales.

## Screenshots
![Screen Recording 2020-09-09 at 05 22 PM](https://user-images.githubusercontent.com/19007109/92660924-08e42200-f2c1-11ea-9f78-a9fed618a2a2.gif)

### Checklist

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios

2020-09-10 09:32 UTC, monfera requested changes
Works great, added some notes, the request part is the removal of the word `bucket` and answering if making the API more general would make sense, to avoid a future breaking change when some other agg eg. `count` or `avg` is added, and serve the `asc` order which is equally important to `desc`.

2020-09-10 09:32 UTC, monfera commented on src/specs/settings.tsx
> +  orderOrdinalBucketsBySum?: boolean;
Also, is it always a descending order? The term `orderOrdinalBucketsBySum` doesn't signal that, and `bucket` doesn't add value there and is a term we probably want to move away from in the future(*), the name could be, `orderBySumDesc` (ordinal, or binned data is implied).

If it makes sense to generalize, then of course it can be `orderBy` which handles maybe `"sum"` and `"desc"` initially. An ascending order is super useful when the user wants to analyze eg. latencies, as interested in the lowest values to see best case, or any kind of goodness metric, like throughput, where the user wants to see the worst cases (= lowest throughput).

(*) `bucket` is possibly misleading when we talk about ordinals; ordinals are already discrete values and don't need binning, continuous values do. Also, we don't have `bucket` in `charts` except one place `allowBrushingLastHistogramBucket` which should be renamed eg. to `allowBrushingLastHistogramBin`  whenever we're introducing other breaking API changes. `bucket` is more of an ES term and carries no well defined meaning in charting.

2020-09-10 15:05 UTC, nickofthyme commented on src/chart_types/xy_chart/utils/series.ts
> +  xValueSums: Map<string | number, number>,
Yeah I agree this could be more extensible to use count, min, max, average or a custom metric. However, I think this can be addressed in https://github.com/elastic/elastic-charts/issues/795 to provide a more robust api for such sorting.

This feature is another final thing needed for the vislib replacement. I was debating whether to add it to the `SettingsSpec` or just use a blind prop. What do you think?

The only thing I think that might be worth it, is to make `orderOrdinalBucketsBySum` into `asc | desc` instead of a `boolean`, but beyond that is a little out of scope.

2020-09-10 15:09 UTC, nickofthyme commented on src/chart_types/xy_chart/utils/series.ts
> +          return (xValueSums.get(v2) ?? 0) - (xValueSums.get(v1) ?? 0);
Not that I can see, since `cleanedDatum.y1` is a `number` or `undefined`. But good to make sure.

https://github.com/elastic/elastic-charts/blob/b374265dc6fca7bbc10ccce888cd13118a2e2f94/src/chart_types/xy_chart/utils/series.ts#L172

2020-09-10 16:17 UTC, nickofthyme commented on src/specs/settings.tsx
> +  orderOrdinalBucketsBySum?: boolean;
Ok I updated the naming to bin and added the `asc` or `desc` option.

We can change the `allowBrushingLastHistogramBucket` at another time.

2020-09-10 16:19 UTC, nickofthyme commented
@monfera see https://github.com/elastic/elastic-charts/pull/814/files/b374265dc6fca7bbc10ccce888cd13118a2e2f94..5246a5abc7e0950cbae1d6d30fb38cfc954b8297 for all changes

2020-09-10 16:38 UTC, monfera commented on src/chart_types/xy_chart/utils/series.ts
> +  xValueSums: Map<string | number, number>,
> I think this can be addressed in #795 to provide a more robust api

So that will be a breaking change, isn't it simpler to avoid it? I wasn't suggesting implementing count, min, max etc. right now (ie. `"sum"` is enough, and can even be the default), just trying to use names in the API that we know will be outdated in no time. So mostly, a naming thing and _maybe_, if feasible, a type signature that permits a string for an agg spec and a direction spec as optionals (or something similar).

> whether to add it to the SettingsSpec or just use a blind prop

I don't have as much info as you do; the feature, albeit triggered by vislib, isn't vislib specific, so if we go for a somewhat stable API (see earlier point) I'd put it in `SettingsSpec`, if it's super temporary, then a blind one is OK I guess. Depends in part on what you think the consumer will be happy with

2020-09-10 16:45 UTC, monfera approved these changes
Thanks Nick for the changes!
The only item remaining is that, if I understand, `orderOrdinalBinsBySum` would soon get obsoleted with the introduction of alternative ordering aggs (count, min, max, avg etc.), we could remove `Sum` from the name and pick something like `{ binAgg = 'sum', direction = 'desc' }` as value. But you likely have more info on the tradeoff and need for expediency.

2020-09-10 22:01 UTC, nickofthyme commented
jenkins retest this please

2020-09-12 03:08 UTC, merged

2020-09-14 16:50 UTC, markov00 commented
:tada: This PR is included in version 21.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v21.2.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/21.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: