fix: legend dark mode hover color
elastic/elastic-charts pull request #820
Opened 2020-09-15 00:18 UTC by nickofthyme

## Summary

Fixes https://github.com/elastic/kibana/issues/77283

Fixes bad styles for dark theme after changes to legend item hover styles in https://github.com/elastic/elastic-charts/pull/749

![Screen Recording 2020-09-14 at 07 12 PM](https://user-images.githubusercontent.com/19007109/93150447-c9517780-f6be-11ea-93f7-f26783cf0114.gif)

### Checklist

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2020-09-15 09:20 UTC, markov00 approved these changes
LGTM

2020-09-15 14:09 UTC, cchaos submitted a review, later dismissed

2020-09-15 14:09 UTC, cchaos commented on src/components/legend/_legend_item.scss
>    &:hover {
This should actually only get background color on `:focus`. Leaving the underline as the hover state.
```suggestion
  &:focus {
```

2020-09-15 14:20 UTC, nickofthyme commented on src/components/legend/_legend_item.scss
>    &:hover {
Unfortunately, at the moment we don't have accessible interactions on the legend and thus `focus` would do nothing. This will be revisited in https://github.com/elastic/elastic-charts/issues/580.

Are you ok with it being `hover` until then?

2020-09-15 18:17 UTC, miukimiu requested changes

2020-09-15 18:17 UTC, miukimiu commented on src/components/legend/_legend_item.scss
> +    background-color: $euiFocusBackgroundColor;
I've been testing the colors and we can change to:

```suggestion
    background-color: $euiColorLightestShade;
```

I was first thinking to remove the background but then it seemed confusing because **hovering all the legend highlights the series**. 

I just think we decided on the wrong color on #820. So let's reserve the `$euiFocusBackgroundColor` for the upcoming `focus` states and use the  `$euiFocusBackgroundColor` when hovering the legend.

2020-09-15 21:20 UTC, nickofthyme commented on src/components/legend/_legend_item.scss
> +    background-color: $euiFocusBackgroundColor;
merged suggestion 0d54de7

2020-09-15 21:56 UTC, merged

2020-09-16 17:12 UTC, markov00 commented
:tada: This PR is included in version 21.3.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v21.3.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/21.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: