feat(legend): add keyboard navigation
elastic/elastic-charts pull request #880
Opened 2020-10-27 16:41 UTC by rshen91

## Summary

Summarize your PR.

If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2020-11-06 22:27 UTC, rshen91 commented
There are vrts failing for small pixel amounts is it ok to update the stories @markov00 @nickofthyme ?

2020-11-09 19:45 UTC, nickofthyme commented
@rshen91 Sorry, yes. I would say it's always appropriate to update the vrt screenshots, then on the PR we can just review what changed in screenshot. Sometimes minor changes somehow create small pixel differences.

2020-11-11 14:09 UTC, markov00 reviewed
Thanks Rachel, with just few changes to the code it looks great!
I'd like to note a few issues:
1) the focus style doesn't looks like the focus style used in EUI. Here I'd like to ask @miukimiu her opinion about that and if we need background + border in the same style as EUI
2) I've noticed an issue with the keyboard: if you enable the color picker with the keyboard we are not passing the focus to the color picker element. Moreover, as shown on the gif, tabbing to the legend item label with the color picker open and clicking on that label cause a crash on the chart
![Nov-11-2020 14-46-13](https://user-images.githubusercontent.com/1421091/98821501-f062c600-242f-11eb-892b-a8183ccadd84.gif)
3) Can you prepare a story that "pass" the focus to the color picker? I'm not sure if this is something that happens automatically or we should implement that through our code
4) if possible instead of updating all these screenshot, it could be better to fix the difference in the padding of the updated DOM structure
5) @myasonik I'd like your opinion on the area-labels and the role applied to the legend.

2020-11-11 17:59 UTC, myasonik requested changes

2020-11-11 17:59 UTC, myasonik commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +        tabIndex={0}
Canvas doesn't seem to be intractable in any way via keyboard. Not sure why we need a tab stop here?

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/color.tsx
> +        <button type="button" className="echLegendItem__color" aria-label="series hidden" title="series hidden">
This button seems to have no action. Is that intended? Seems this text and the following button should be a single element so it'll read something like `Series hidden: ${seriesName}`

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/color.tsx
>          onClick={hasColorPicker ? onClick : undefined}
Similar to above, if there is no action, it shouldn't be a button.

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/color.tsx
> +        aria-label={hasColorPicker ? 'change series color' : 'series color'}
We should also mention what the current color and buttons are assumed to be interactive so I think we can tweak this to something like:
```suggestion
        aria-label={`series color: ${colorName}`}
```

But putting this together with my comment above, we cannot leave an `aria-label` on a `div`. In that case, we should add the label to the `<svg>` of the icon.

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/extra.tsx
> +    <div className={extraClassNames} title={`${extra}`} aria-label={`${extra}`}>
`aria-label` doesn't work on elements with no semantic value such as `div` or `span` (unless their role is also changed).

Also, this label just restates the inner text so there's really no need to add it. 

```suggestion
    <div className={extraClassNames} title={`${extra}`}>
```

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/label.tsx
> +  const labelWithExtra = getExtra(label, extra);
I dunno if we need to add this at all... The `extra` content seems to always be the next element so screen readers will read it next and it seems like it's never visually hidden either.

2020-11-11 17:59 UTC, myasonik commented on src/components/legend/legend.tsx
> +        <ul style={legendListStyle} className="echLegendList" role="listbox">
Why are we adding `role=listbox` here? 

`listbox` is the role given to `<select>` elements and has a lot of custom controls required to implement a custom one.

2020-11-11 17:59 UTC, myasonik commented on stories/legend/11_legend_actions.tsx
>    return (
Can't leave a comment lower than this, but [`ownFocus`](https://elastic.github.io/eui/#/layout/popover#removing-the-focus-trap) needs to be added to this Popover otherwise there is no way for a keyboard user to realistically navigate into it.

2020-11-11 18:02 UTC, myasonik commented on stories/legend/11_legend_actions.tsx
>    return (
This will fix the first half of 2 and 3 in the issues Marco left above

2020-11-11 19:26 UTC, myasonik commented on stories/legend/11_legend_actions.tsx
>    return (
EUI 30.3.0 changes the default of `ownFocus` to `true` so if y'all are good at staying up to date then this change might not be necessary.

2020-11-11 21:30 UTC, nickofthyme reviewed
Looking good, just a few comments on top of @myasonik's

2020-11-11 21:30 UTC, nickofthyme commented on src/components/legend/color.tsx
> +        <button type="button" className="echLegendItem__color" aria-label="series hidden" title="series hidden">
Yeah this is just an icon here when `isSeriesHidden`, the legend label is the clickable element.

2020-11-11 21:30 UTC, nickofthyme commented on src/components/legend/color.tsx
>          onClick={hasColorPicker ? onClick : undefined}
@myasonik this is actionable only when `hasColorPicker` is `true`. So you are saying just separate this for action and inactionable elements?

2020-11-11 21:30 UTC, nickofthyme commented on src/components/legend/color.tsx
> +        aria-label={hasColorPicker ? 'change series color' : 'series color'}
Yeah I think we just split this and have the actionable element say ```aria-label={`series color: ${colorName}`}``` and the actionable say ```aria-label={`change series color: ${colorName}`}```

2020-11-11 21:30 UTC, nickofthyme commented on src/components/legend/color.tsx
> +        type="button"
Also this should have a `tabIndex={0}` when `hasColorPicker` is false

```suggestion
        type="button"
        tabIndex={hasColorPicker ? undefined : 0}
        
```

2020-11-11 22:07 UTC, myasonik commented on src/components/legend/color.tsx
>          onClick={hasColorPicker ? onClick : undefined}
Yeah, exactly

2020-11-11 22:09 UTC, myasonik commented on src/components/legend/color.tsx
> +        type="button"
> Also this should have a `tabIndex={0}` when `hasColorPicker` is false

Why's that? Won't it not have any action when `hasColorPicker == false`? If so, then it shouldn't be a `<button>` and it shouldn't be a tab stop (i.e., `tabIndex={0}`). If it does still have an action, then it should stay a `<button>` which doesn't need a `tabIndex` defined.

2020-11-11 23:48 UTC, myasonik commented on src/components/legend/color.tsx
> +          <Icon type="eyeClosed" viewBox="-3 -3 22 22" aria-label="series color is hidden" />
🤔 It's not the "series color" that's hidden, it's the series itself, right?

I think this might be more clear? (But I'm also no wordsmith so would love to hear from others)

```suggestion
          <Icon type="eyeClosed" viewBox="-3 -3 22 22" aria-label="series ${seriesName} is hidden" />
```

Also, how does elastic-charts handle internationalization? We need to make sure these strings are i18n-able for Kibana.

2020-11-11 23:48 UTC, myasonik commented on src/components/legend/color.tsx
> +          <Icon type="dot" color={color} aria-label="change series color" />
Are names for these colors defined anywhere? Would be good to put that into the label. Worst case, even putting the hex code would be better than nothing... 

```suggestion
          <Icon type="dot" color={color} aria-label="change series color, currently ${colorName}" />
```

2020-11-11 23:48 UTC, myasonik commented on src/components/legend/color.tsx
> +        <Icon type="dot" color={color} aria-label={hasColorPicker ? 'change series color' : 'series color'} />
Can remove the `aria-label` conditional, and would be good to add a color name here

```suggestion
        <Icon type="dot" color={color} aria-label={`series color: ${colorName}`} />
```

2020-11-11 23:48 UTC, myasonik commented on stories/legend/11_legend_actions.tsx
> +      ownFocus
One more popover below to add this too - line 142

2020-11-11 23:53 UTC, rshen91 commented on stories/legend/11_legend_actions.tsx
> +      ownFocus
ah! Thank you

2020-11-12 09:12 UTC, markov00 commented on src/components/legend/color.tsx
> +          <Icon type="eyeClosed" viewBox="-3 -3 22 22" aria-label="series color is hidden" />
Not at the moment, we have just a very limited set of strings at the moment, but one next step will be to add i18n support

2020-11-12 09:16 UTC, markov00 commented on src/components/legend/color.tsx
> +          <Icon type="dot" color={color} aria-label="change series color" />
We don't have a naming mapping for the colors as these are actually passed to the charts by the consumer. A conversion from hex to actual name is out of the scope of the chart lib at the moment. Something like that can be built and shared across all kibana, a approximation mapping like the one provided by https://chir.ag/projects/name-that-color/#6195ED can be an interesting solution and can go into the same direction of the i18n

2020-11-12 16:07 UTC, rshen91 commented on stories/legend/11_legend_actions.tsx
> +      ownFocus
Updated in f7e2f27

2020-11-12 16:08 UTC, rshen91 commented on src/components/legend/color.tsx
> +        type="button"
I think f7e2f27 is working as expected with your feedback, let me know what you think (and if I'm misunderstanding) when you have a chance. Thank you!

2020-11-12 16:22 UTC, miukimiu requested changes

2020-11-12 16:22 UTC, miukimiu commented on src/components/legend/_legend.scss
> +    box-shadow: inset 0 0 0 $euiSizeXS / 4 $euiFocusRingColor;
Thanks, @rshen91 for introducing this keyboard navigation. It's a very good improvement! 🎉 

I tested this PR locally and I would suggest use our EUI variables and mixins to create the focus styles:

```suggestion
   @include euiFocusRing;
   background-color: $euiFocusBackgroundColor;
   border-radius: $euiBorderRadius / 2;
```

It will look like this:
<img width="231" alt="Screenshot 2020-11-12 at 16 10 41" src="https://user-images.githubusercontent.com/2750668/98965441-f45f1880-2501-11eb-8db4-faba474b2652.png">

<img width="228" alt="Screenshot 2020-11-12 at 16 18 06" src="https://user-images.githubusercontent.com/2750668/98966049-b31b3880-2502-11eb-866a-a12faad84543.png">

I tested these for different examples like the **Legend - Color Picker** and it doesn't look good. It seems that the legends have different styles so the `euiFocusRing` doesn't surround the legend properly. Is it possible to fix this?

<img width="522" alt="Screenshot 2020-11-12 at 16 11 41" src="https://user-images.githubusercontent.com/2750668/98965923-8e26c580-2502-11eb-95e4-54fc906a7417.png">

2020-11-12 17:02 UTC, nickofthyme commented on stories/legend/11_legend_actions.tsx
> +      ownFocus
👍

2020-11-12 17:04 UTC, nickofthyme commented on src/components/legend/_legend.scss
> +    box-shadow: inset 0 0 0 $euiSizeXS / 4 $euiFocusRingColor;
@miukimiu Would the hover state change at all?

2020-11-12 17:12 UTC, myasonik commented on src/components/legend/color.tsx
> +          <Icon type="dot" color={color} aria-label="change series color" />
Then hex code is fine for now

2020-11-12 20:53 UTC, rshen91 commented on src/components/legend/_legend.scss
> +    box-shadow: inset 0 0 0 $euiSizeXS / 4 $euiFocusRingColor;
Thank you so much for the help- please see 5b842fe when you have a chance

2020-11-16 16:14 UTC, rshen91 commented on src/components/legend/color.tsx
> +        <Icon type="dot" color={color} aria-label={hasColorPicker ? 'change series color' : 'series color'} />
Please see bc14508

2020-11-16 16:15 UTC, rshen91 commented on src/components/legend/label.tsx
> +  const labelWithExtra = getExtra(label, extra);
When I tested with VoiceOver it wasn't saying the extra. Let me know if I should test differently - thank you

2020-11-16 21:37 UTC, myasonik commented on src/components/legend/label.tsx
> +  const labelWithExtra = getExtra(label, extra);
It won't read it as part of the button when tabbing through the layout, but it's available when reading the list item. CTRL+OPTION+arrow keys lets you navigate forward and backward through content.

2020-11-16 21:43 UTC, myasonik commented on src/components/legend/label.tsx
> +  const labelWithExtra = getExtra(label, extra);
Running through it with VO, one thing I found confusing is knowing what to expect this button to do. Instead of adding the extra content to the tail end of the label, what do you think about adding some instructions like "Activate to hide series in graph." (And swapping it to "Activate to show series in graph." when it's hidden.)

2020-11-16 22:10 UTC, rshen91 commented on src/components/legend/label.tsx
> +  const labelWithExtra = getExtra(label, extra);
Thank you for the clarification! Please see for edits in commit dc373e8

2020-11-16 22:18 UTC, myasonik approved these changes
Just the two `aria-label` changes left from me and this looks ready to ship on the a11y side! 🎉

2020-11-16 22:18 UTC, myasonik commented on src/components/legend/label.tsx
> +      aria-label={isSeriesHidden ? `Activate to show series in graph` : `Activate to hide series in graph`}
`aria-label` replaces the contents of the button so we need to restate the `label` in here as well.

```suggestion
      aria-label={isSeriesHidden ? `${label}; Activate to show series in graph` : `${label}; Activate to hide series in graph`}
```

2020-11-16 22:26 UTC, rshen91 commented on src/components/legend/label.tsx
> +      aria-label={isSeriesHidden ? `Activate to show series in graph` : `Activate to hide series in graph`}
Changed in dc373e8! Thanks!

2020-11-17 13:02 UTC, miukimiu approved these changes
Tested in Chrome, Edge, and Firefox.  I'm suggesting two small changes but all the rest looks good. 🎉

2020-11-17 13:05 UTC, miukimiu commented on src/components/legend/_legend.scss
> +    box-shadow: inset 0 0 0 $euiSizeXS / 4 $euiFocusRingColor;
@nickofthyme I don't think we need to change the hover state for now.

2020-11-17 14:17 UTC, rshen91 commented on src/components/legend/color.tsx
> +          <Icon type="dot" color={color} aria-label="change series color" />
Thank you for catching this - edited in 07eadda

2020-11-17 15:38 UTC, rshen91 commented on src/components/legend/_legend.scss
> +    }
🙇‍♀️ thank you f751a99

2020-11-17 15:38 UTC, rshen91 commented on src/components/legend/_legend_item.scss
Thank you for the help! Commit f751a99 for changes

2020-11-17 16:09 UTC, nickofthyme requested changes

2020-11-17 16:09 UTC, nickofthyme commented on src/components/legend/_legend.scss
> +      display: flex;
Why are we making this change? The display grid is used to spread the columns nicely that is not achievable with `flex`

2020-11-23 21:10 UTC, rshen91 commented on src/components/legend/_legend.scss
> +      display: flex;
thanks - edited in ef51a44

2020-12-02 15:15 UTC, markov00 requested changes
Few points to address:
- the updated screenshot `integration/tests/__image_snapshots__/annotations-stories-test-ts-annotations-stories-rotation-rotation-negative-90-1-snap.png` is actually wrong: the Y axis is reversed, it should appear with the 4 on the top: https://elastic.github.io/elastic-charts/?path=/story/annotations-lines--single-bar-histogram&knob-debug=&knob-chartRotation=-90
- there is one missing thing that we should probably do internally: we should return the focus to the button that opened a color picker/modal on close. @myasonik is there any good practices for that that we can use?

2020-12-02 15:15 UTC, markov00 commented on src/components/legend/color.tsx
> +          <Icon type="eyeClosed" viewBox="-3 -3 22 22" aria-label="series color is hidden" />
@rshen91 can you fix the wording of this as suggested by Michael?

2020-12-02 15:34 UTC, rshen91 commented on src/components/legend/color.tsx
> +          <Icon type="eyeClosed" viewBox="-3 -3 22 22" aria-label="series color is hidden" />
Yes thank you good catch - please see ecc7797

2020-12-02 15:35 UTC, rshen91 commented
Updated the annotation story in ecc7797 🤞

2020-12-02 21:51 UTC, myasonik commented
> there is one missing thing that we should probably do internally: we should return the focus to the button that opened a color picker/modal on close. @myasonik is there any good practices for that that we can use?

EUI usually tries to handle this for you but I think it's breaking because we chnage the button icon depending on what was set in the modal. Anyway, EUI expects that this doesn't work 100% of the time so there is an `closePopover` callback available on `EuiPopover` which you can use to manually call `.focus()` on a DOM element.

2020-12-03 16:03 UTC, nickofthyme commented on src/components/legend/_legend.scss
> +    }
@miukimiu Is there a way we could add a transparent border to this so there is no jump in height and width when the border is added?

![Screen Recording 2020-11-17 at 12 53 PM](https://user-images.githubusercontent.com/2750668/99392635-e8919e80-28d3-11eb-84fb-bf7ac1ddef68.gif)

2020-12-04 16:20 UTC, nickofthyme commented on integration/page_objects/common.ts
> +    });
Rather than adding all the css here you could just add a class to the `#story-root` element. No need to fuss with creating a style tag and appending it to the dom.

```
const storyRoot = document.getElementById('story-root');
if (storyRoot) {
  storyRoot.classList.add('disable-animations')
}
```

> Sidenote: `getElementById` implies the type of selector so using `#` won't work

2020-12-04 16:23 UTC, nickofthyme commented on .storybook/style.scss
> +  // }
By adding the class you can then do...

```scss
#story-root {
  .disable-animations {
    *,
    *::after,
    *::before{
      transition-delay: 0s !important;
      transition-duration: 0s !important;
      animation-delay: -0.0001s !important;
      animation-duration: 0s !important;
      animation-play-state: paused !important;
      caret-color: transparent !important;
    }
  }
}
```

2020-12-04 20:49 UTC, rshen91 commented
jenkins test this please

2020-12-04 21:44 UTC, rshen91 commented
@nickofthyme and @markov00 in 3631426 I added a workaround for the vrts that were failing in legend_stories and area_stories with disableAnimations(). Can you let me know your thoughts?

2020-12-05 00:14 UTC, nickofthyme commented on integration/page_objects/common.ts
> +    await this.loadElementFromURL(url, '#story-root');
This is a good thought. It must replace the `#story-root` after each navigation.

But as long as you use this in the `action` function you don't need to call `loadElementFromURL`.

```suggestion
```

2020-12-05 00:16 UTC, nickofthyme commented on integration/tests/area_stories.test.ts
> +        );
No need to repeat the URL navigation again. The `disableAnimations` method can just be used as a helper functions in the `action`.

```suggestion
        await common.disableAnimations();
```

2020-12-05 00:16 UTC, nickofthyme commented on integration/tests/area_stories.test.ts
> +        );
Same as above. Lmk if this don't work.

```suggestion
        await common.disableAnimations();
```

2020-12-05 00:17 UTC, nickofthyme commented on integration/tests/legend_stories.test.ts
> +    });
Is this needed?

2020-12-06 19:45 UTC, rshen91 commented on integration/tests/area_stories.test.ts
> +        );
It works! Thank you! Please see 5bdb611

2020-12-06 19:45 UTC, rshen91 commented on integration/tests/legend_stories.test.ts
> +    });
Good call - totally not needed - removed in 5bdb611

2020-12-06 19:45 UTC, rshen91 commented on integration/tests/area_stories.test.ts
> +        );
🎉 Good point - please see 5bdb611

2020-12-09 14:17 UTC, markov00 approved these changes
LGTM, tested locally and works perfectly.

2020-12-09 14:17 UTC, markov00 commented on integration/page_objects/common.ts
> +    // await this.loadElementFromURL(url, '#story-root');
remove this line

2020-12-09 14:17 UTC, markov00 commented on integration/tests/area_stories.test.ts
> +        // 'http://localhost:9001/?path=/story/area-chart--with-negative-and-positive&knob-Y scale=log',
remove these commented URLs

2020-12-09 14:43 UTC, rshen91 commented on integration/tests/area_stories.test.ts
> +        // 'http://localhost:9001/?path=/story/area-chart--with-negative-and-positive&knob-Y scale=log',
removed in 55f1628 thanks!

2020-12-09 14:44 UTC, rshen91 commented on integration/page_objects/common.ts
> +    // await this.loadElementFromURL(url, '#story-root');
removed in 55f1628 thanks!

2020-12-09 15:53 UTC, nickofthyme requested changes
The final result is SUPER clean and smooth, way to go!

I have a few nits about the vrt helper methods. Also, I wonder if we could move the mouse before the tab to show the focus state only and not the focused and hover state.

![image](https://user-images.githubusercontent.com/19007109/101652302-b58a8880-3a03-11eb-90be-57f1936c154d.png)

2020-12-09 15:53 UTC, nickofthyme commented on .storybook/style_test.scss
> +@import '../node_modules/@elastic/eui/src/theme_light.scss';
Doesn't look like you are using this file

2020-12-09 15:53 UTC, nickofthyme commented on integration/page_objects/common.ts
> +  action?: () => void | Promise<void> | Iterable<unknown>;
What is this for?

2020-12-09 15:53 UTC, nickofthyme commented on integration/page_objects/common.ts
> +/* eslint-disable no-await-in-loop */
Can you just disable the line not the whole file?

2020-12-09 15:53 UTC, nickofthyme commented on integration/page_objects/common.ts
> +        await page.keyboard.press('Tab');
```suggestion
        // eslint-disable-next-line no-await-in-loop
        await page.keyboard.press('Tab');
```

2020-12-09 15:53 UTC, nickofthyme commented on integration/page_objects/common.ts
> +        await page.keyboard.press('Enter');
```suggestion
        // eslint-disable-next-line no-await-in-loop
        await page.keyboard.press('Enter');
```

2020-12-09 15:53 UTC, nickofthyme commented on integration/page_objects/common.ts
> +      await this.clickMouseRelativeToDOMElement({ top: 242, left: 910 }, this.chartSelector);
This should be a generic method, why are there specific `top` and `left` values? Is the purpose of this to just click the element to the tap?

2020-12-09 16:52 UTC, rshen91 commented on integration/page_objects/common.ts
> +      await this.clickMouseRelativeToDOMElement({ top: 242, left: 910 }, this.chartSelector);
Yep! Just to make sure that storybook tabbing doesn't go down all the individual stories in the pane before reaching the iframe

2020-12-09 16:53 UTC, rshen91 commented on integration/page_objects/common.ts
> +/* eslint-disable no-await-in-loop */
Yep this makes sense - made changes in 02a06fe

2020-12-09 17:43 UTC, nickofthyme approved these changes

2020-12-09 19:01 UTC, rshen91 commented on integration/page_objects/common.ts
> +        await page.keyboard.press('Tab');
changed in a5acd93

2020-12-09 19:01 UTC, rshen91 commented on .storybook/style_test.scss
> +@import '../node_modules/@elastic/eui/src/theme_light.scss';
changed in a5acd93

2020-12-09 19:28 UTC, merged

2021-01-30 15:43 UTC, markov00 commented
:tada: This PR is included in version 24.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v24.5.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/24.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: