Display Pie chart legend extra
elastic/elastic-charts pull request #939
Opened 2020-12-07 11:38 UTC by shahzad31

## Summary

Summarize your PR.

If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2020-12-08 17:40 UTC, nickofthyme requested changes
This is awesome, thanks for your help! 🎉 

Everything looks good, I found 2 issues thus far.

First, it looks like the indent is not correctly accounting for the width of the legend item and the value is being pushed to the right. You can fix this by changing `marginLeft` here to `paddingLeft`.

 https://github.com/elastic/elastic-charts/blob/3c823fdbc8437c907c02b58c1aa8e084bc7611d1/src/components/legend/legend_item.tsx#L217-L221

![Screen Recording 2020-12-08 at 11 30 AM](https://user-images.githubusercontent.com/19007109/101520114-a47d4100-3949-11eb-948e-155b89e987cb.gif)

Secondly, the values of the nested items appear to be incorrect. Notice below that Asia is `$677 Bn` in the chart but `$174 Bn` in the legend. Not sure where this issue is originating in the code.

<img width="759" alt="Image 2020-12-08 at 11 37 29 AM" src="https://user-images.githubusercontent.com/19007109/101520443-1fdef280-394a-11eb-9aa4-a21f496a83e4.png">

2020-12-09 12:11 UTC, markov00 commented
> Secondly, the values of the nested items appear to be incorrect. Notice below that Asia is `$677 Bn` in the chart but `$174 Bn` in the legend. It looks like using the flattened values will override keys in separate branches, you likely need to do this logic on the tree form because in the flattened version you lose the reference to the parent key.

Hey @monfera can you please check this PR and see if your current work on fixing the hierarchical legend fixes also this value? Thanks

2020-12-09 18:05 UTC, monfera commented
@markov00 we touched on this on our call with @nickofthyme and he suggests the values are OK as they are and no action is needed in relation to this item. Nick, please tell if I misinterpreted it

2020-12-09 19:58 UTC, nickofthyme commented
@monfera that's correct. @Shahzad I can take a look today if you'd like.

2020-12-09 20:31 UTC, shahzad31 commented
@nickofthyme sure , please go ahead, i am unable to figure out, how to parse legends info in a tree form.

2020-12-16 15:24 UTC, nickofthyme commented
@monfera I lied 🤥. After looking into this, the way we display the legend I don't know the parent "key" so I would need your changes from #947

2021-01-14 19:32 UTC, nickofthyme submitted a review, later dismissed

2021-01-15 16:28 UTC, monfera requested changes
Great PR 🎉  Only requesting some changes because of the attempt at hoisting some definition, namely the concept of `Category`, see `category.ts` in the legend strategy PR. It wasn't a fully arbitrary choice; series keys and legend labels have commonality. Basically, both represent category. So it fell out, besides my slant toward moving to more semantic concepts than `string`. Looking forward to nominal typing, or if it doesn't come soon enough, branded types in `elastic-charts`, because `string` is not very safe, now a lot of things that are semantically related just happen to be all `string`s

2021-01-15 16:28 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
```suggestion
    return pieSpec && !isInvalidLegendMaxDepth(legendMaxDepth)) 
        ? getExtraValueMap(pieSpec, tree)
        : legendExtraValues;
```

2021-01-15 16:28 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
Also, I'd prefer positive predicates in general, eg. `isValidLegendMaxDepth`  over `!isInvalidLegendMaxDepth`

2021-01-15 16:28 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +
```suggestion
```

2021-01-15 16:28 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +
... as the `for` loop will bail anyway

2021-01-15 16:28 UTC, monfera commented on src/commons/legend.ts
> +export type LegendItemChildId = string | number;
I'm not sure about it, in the other PR I also redefined it, hoisted the definition to `CategoryKey` but that gets channeled to a lot of places; if you think it really needs to admit a number here too, I'd need to understand more about it before approving this broadening, as it might be important, not sure yet. For this reason maybe it's better for the legendStrategy PR go in first, as it still retains the `string`

2021-01-15 16:28 UTC, monfera commented on src/commons/legend.ts
> +  path?: number[];
The legend strategy PR also adds it, however as a mandatory prop, and also structured, so it'd be useful to rebase this PR on that; in part b/c my day is wrapping up sooner than yours :-D

2021-01-15 16:28 UTC, monfera commented on src/commons/legend.ts
> +  path?: number[];
Btw. mandatory props have a lot of benefit in the realm of typing and code simplicity; no need for runtime conditions or type guards, so wherever possible, I'd prefer mandatory over optional. Maybe there are counterarguments that'd shift my understanding

2021-01-15 16:35 UTC, nickofthyme commented on src/commons/legend.ts
> +export type LegendItemChildId = string | number;
I added this because the `childId` can be a `number` or `string` and the map with be type sensitive. Meaning if I convert the `childId` to a string I need to do that everywhere. This just simplifies the type checking.

Do you know a specific case where this would adversely affect the code?

2021-01-19 22:33 UTC, nickofthyme commented on src/commons/legend.ts
> +  path?: number[];
True, I was simply using that to find the right key using a path or key but the path is defined such that it works already (i.e. the `value` is the `seriesIdentifier.key`)

2021-01-19 22:43 UTC, nickofthyme commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +
69c7dc8

2021-01-19 22:43 UTC, nickofthyme commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
69c7dc8

2021-01-19 22:58 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
Good changes here, though would still prefer a positive predicate over a negative one, though totally not a blocker.

I've a question here: this extracts, and only keys on the concatenated `value` ie. series keys; won't this approach need the structure information downstream of this? The legend strategies PR firmly detached the notion of sufficiency of knowing the label even for just highlighting the value, at least for non-single layer charts such as partition charts. I'll look at it in more detail tomorrow, just wanted to check if/how this info won't be needed, ie. why eg. not key on the concatentated `{index, value}` tuples rather than on just the `value`.

```
keys.set(path.map(({ value: v }) => v).join('__'), values);
```

2021-01-19 22:59 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +
👍

2021-01-19 23:24 UTC, monfera commented on src/commons/legend.ts
> +export type LegendItemChildId = string | number;
I don't immediately understand the need; tried to trace and it appears to be, ultimately, `string`: 

- `values.set(key, formattedValue);`, line 68 in `getExtraValueMap` has `key: string` from line 61, so no number there
- I haven't checked the ton of other uses of though many of them appear to ultimately use `CategoryKey` therefore, now, `string`, eg. `const seriesTooltipValues = new Map<SeriesKey, LegendItemExtraValues>();` in `tooltip.ts`
- `computeLegendSelector` in `src/chart_types/partition_chart/state/selectors/compute_legend.ts` used to not need the number; specifically, the `dataName` inside `ShapeViewModel.quadViewModel`, which extends `ShapeTreeNode`, has `dataName` as `CategoryKey`
- having grepped the code for `childId`, no obvious number assignment turned up; things like `dataName` and `BandedAccessorType` get assigned

It'd be great to avoid the potential leakiness of admitting `number` here, so I'd like to better understand where exactly it's neaded; you said

> the childId can be a number or string

but on cursory look it's not universally true so the list of specific places would be neat; ie. where would a conversion from numbers to strings would need to take place. 

It'd be useful for me to know what the ultimate _meaning_ of the `childId` is and why it's desirable for numbers to be admitted.

I don't immediately see test cases that exercise anything called `childId` with numbers either, but again, it's late hours for me 😄

2021-01-20 15:27 UTC, nickofthyme commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
I just assume not mess with existing naming (i.e. `isInvalidLegendMaxDepth`) because there's likely a lot of this around. I typically use positive or negative such that I don't have to `!` it.

2021-01-20 15:30 UTC, nickofthyme commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
Yes you are right about the `value` that should be `index` instead. See 13811eb051abb5a2399507d8b10c50b7f24c75bf

2021-01-20 15:34 UTC, nickofthyme commented on src/commons/legend.ts
> +export type LegendItemChildId = string | number;
Yup you are right. This was a remnant from before I used the `path.join` logic. Thanks for being persistent. See a2972a0

2021-01-20 15:37 UTC, monfera commented on src/commons/legend.ts
> +export type LegendItemChildId = string | number;
Haha mostly blind luck, could've been needed, it gets used in numerous places

2021-01-20 15:42 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
Thanks! Fair enough not to add possibly sweeping changes to this PR. We could maybe brainstorm about whether we should prefer positive predicates at all, not just the general avoidance of `non` or `un` but also some legit words like `invalid`; there's no specific line we can draw between negative and positive words and it might be something noone else cares about, it's a miniscule stylistic thing

2021-01-20 15:43 UTC, monfera commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
Re the `value` vs `index` change, the current test suite is insensitive to whether it yields the desired thing, it'd be neat to make it fail if the info is insufficient, I guess it depends on mock structure to trigger a difference

2021-01-20 19:04 UTC, nickofthyme commented on src/chart_types/partition_chart/state/selectors/get_legend_items_extra.ts
> +    return getExtraValueMap(pieSpec, tree);
See dac6d17

2021-01-20 19:24 UTC, monfera approved these changes
Looks good and super useful, great job  🎉 and thanks for the changes too! Good to merge on green

2021-01-20 19:51 UTC, merged

2021-01-30 15:42 UTC, markov00 commented
:tada: This PR is included in version 24.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v24.5.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/24.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: