feat: add data table component to xy charts
elastic/elastic-charts pull request #949
Opened 2020-12-14 19:53 UTC by rshen91

## Summary

Summarize your PR.

If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

2021-02-11 13:38 UTC, markov00 requested changes
I don't have a lot of knowledge about how screen readers works but it, from what I've tested I see the potential pitfalls here and we should step back a bit from the problem.
There are multiple cases that we should consider and all of them require an accurate design on the accessible table to represent correctly the data, in particular:
- are we correctly describing multiple series? are we describing correctly their types and values?
- are we representing stacked series? do we need to show summary statistics for each stacked set?

I think we should write down a table format proposal for various use cases, validate it with a11y team and then work on implement it in the correct way

2021-02-11 13:38 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +          </tr>,
This is a bit weird, because it is interpreted as a row with only the first column available.
There is no `scope` here and we should probably span the content to cover all the columns

2021-02-11 13:38 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +            aria-labelledby="alt text for chart data"
please check every `aria` attributes and fix them with their correct usage

2021-03-03 16:35 UTC, monfera commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          </HeadingLevel>
Does the empty content (row 180) serve some specific purpose?

2021-03-03 16:38 UTC, monfera commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +      <figure>
Just for my learning for a11y, I'm wondering if `the <figure>` tag should be annotated, eg. with `aria-label`; I see things in the <canvas> element, and right below in `<HeadingLevel>`—is there a reference that tells us to wrap things around with `<figure>`?

2021-03-03 16:40 UTC, monfera commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    description: undefined,
Would it help keeping types simple, if `description` got initialized to eg. the empty string like `generatedDescription` right below? Can still conditionalize on empty vs non-empty strings in use

2021-03-03 16:43 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  if (!d) return [];
If `d` is `DataSeries`, this condition will never be true, so I think there's no need for this bail line

2021-03-03 16:54 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  for (let i = 0; i < keysAndValues.length; i++) {
Minor: `reduce` would probably be a little more streamlined to not need an external accumulator in row 592 (glad to chat/zoom), and `keysAndValues` could be renamed `entries`, and eg. destructuring would be better than [0]/[1] indexing, eg.
```
return entries.reduce((result, [key, value]) => {
     if(key !== 'datum' && value !== null || value !== undefined) {
       result.push(key);
     }
     return result;
  }), []);     
  ```
Also, I'm interested in why there's a need for iterating through `data` as we might be doing that elsewhere too, though maybe I'll run into the reason in the code as I go through

2021-03-03 16:58 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  if (!d) return [];
Same - may not be needed

2021-03-03 17:01 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  d.data.map((value) => {
Combining functional mapping (to get a result) and side effects (pushing into `values` that's outside the `map` has pros&cons, wondering if it's possible to do separately while still preserving performance

2021-03-03 17:16 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +    return keysAndValues.map((val) => {
Same here, a `map` shouldn't be used for just its side effect; we return the `keysAndValues.map` here but the outer `map` isn't using it anywhere, should be a `forEach` for clarity, as the most minimal change.

Although I'd look into some other coding approach; basically the entire 13 row function body is roughly equivalent to the equally not speed optimized 3 row version (I haven't tested)
```
return d.data.flatMap(value => Object.entries(value)
  .filter(([k, v]) => k !== 'datum' && tyeof val === 'number'))
  .map(([k]) => k);
```

2021-03-03 17:18 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +      if (val[0] !== 'datum' && val[1] !== null && val[1] !== undefined && typeof val[1] === 'number') {
No need to check if the value is null or undefined, as it won't be a `number` if it's either of them, so it's enough to test if it's a number. Unless we want to retain `NaN` and infinities, a nice predicate is `Number.isFinite()`

2021-03-03 17:20 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +function parseDataForKeys(d: DataSeries) {
We have several functions of roughly the same shape, runtime behavior and improvement options; in this case, it's worth looking into bringing them together one common function, may or may not be possible but it's good to try for more DRYness

2021-03-03 17:45 UTC, monfera commented on src/chart_types/xy_chart/state/utils/utils.ts
> +function parseDataForKeys(d: DataSeries) {
This function looks identical to `parseDataForKeysStacked` two functions above and similar or maybe identical to some others I saw. A need to do copy & paste is warning that we could do something more DRY

2021-03-05 22:38 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  if (!d) return [];
Thank you so much for this review - I updated based on this feedback mainly in commit cd8c964. 🙇‍♀️

2021-03-05 22:38 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  for (let i = 0; i < keysAndValues.length; i++) {
Yeah I think your suggestion is more streamlined - incorporated in commit cd8c964

2021-03-05 22:39 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  if (!d) return [];
👍 Removed in cd8c964

2021-03-05 22:39 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +  d.data.map((value) => {
Smart! Incorporated in commit cd8c964

2021-03-08 15:36 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +    return keysAndValues.map((val) => {
Thank you! Commit cd8c964

2021-03-08 15:36 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +function parseDataForKeys(d: DataSeries) {
DRY is awesome cd8c964

2021-03-08 15:36 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +function parseDataForKeys(d: DataSeries) {
Please see cd8c964 🙇

2021-03-08 15:50 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +      if (val[0] !== 'datum' && val[1] !== null && val[1] !== undefined && typeof val[1] === 'number') {
I missed this one sorry! a45b9e2

2021-03-09 23:28 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +    description: undefined,
Sorry this needed to be cleaned up - 3c3f54e

2021-03-09 23:29 UTC, rshen91 commented on src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx
> +          </HeadingLevel>
This was outdated and I needed to clean it up :yikes: 3c3f54e

2021-03-15 13:44 UTC, rshen91 commented on src/chart_types/xy_chart/state/utils/utils.ts
> +/** @internal */
Thank you! TIL - removed these

2021-03-15 13:44 UTC, rshen91 commented on src/chart_types/xy_chart/state/selectors/is_brush_available.ts
> +    if (!scales.xScale || settingsSpec.dataTable?.showDataTable === true) {
Yep this is removed - I was hitting a strange error that I can't reproduce now 😅

2021-03-16 16:23 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +  const { seriesName, axesTitles, splitAccessor, seriesType, yScales } = d[0];
This line will fail if the `showDefaultDescription` prop was set to `false` on the `Settings` component

2021-03-16 16:23 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +    const scaleType = axisDirection === 'x-' ? xScale.type : yScales.get(titles[i][1]!)?.type;
It's better to not infer the scale from the axis direction.
Please just list all the yScales and the xScale, independently if they are on the bottom or top, left or right.

2021-03-16 16:23 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +        : `${i}. A ${axisDirection}axis is the scale type ${scaleType} and is titled ${axisTitle} with the domain ${axisDomain}. `;
if the axis doesn't have a title, we don't need to say that, we don't need to use the `__global__` name for that.
Just say: `The X axis is temporal scale` or with title, `The X axis, named blablabla, is a linear scale`

2021-03-16 16:23 UTC, markov00 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +    titleDomain +=
instead of concatenate the strings like that, collect all of them in an array and then join it with the appropriate separator (a space, a new line or nothing depending on your templates)

2021-03-16 18:11 UTC, rshen91 commented on src/state/selectors/get_screen_reader_settings.ts
> +  },
Thank you! b9aaa1d

2021-03-16 18:16 UTC, rshen91 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +    : ` ${new Date(startDomain).toTimeString()} to ${new Date(endDomain).toTimeString()}`;
Thank you, good catch, please see 9e75754

2021-03-16 18:22 UTC, rshen91 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +  });
Thank you! cf0cbe6

2021-03-16 18:37 UTC, rshen91 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +  const { seriesName, axesTitles, splitAccessor, seriesType, yScales } = d[0];
Good point, fixed in fac7927

2021-03-16 18:37 UTC, rshen91 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +  });
Ah good catch fixed in cf0cbe6

2021-03-16 20:19 UTC, rshen91 commented on src/components/screen_reader_data_table/screen_reader_data_table.tsx
> +        : `${i}. A ${axisDirection}axis is the scale type ${scaleType} and is titled ${axisTitle} with the domain ${axisDomain}. `;
Updated in b9aaa1d

2021-03-22 20:50 UTC, rshen91 commented
Closing for new and cleaner issue here https://github.com/elastic/elastic-charts/pull/1084

2021-03-22 20:50 UTC, closed without merging