fix(legend): remove ids for circles
elastic/elastic-charts pull request #973
Opened 2021-01-13 15:33 UTC by rshen91

## Summary

Updating the changes in #971 

### Checklist

- [x] Unit tests were updated or added to match the most common scenarios

2021-01-13 15:57 UTC, markov00 requested changes

2021-01-13 15:57 UTC, markov00 commented on src/components/icons/assets/dot.tsx
> +        aria-labelledby={color}
we can remove that `aria-labelledby` because we don't have something to associated this with.
Using `color` there is wrong because labelledby accept a DOM element id

2021-01-13 16:14 UTC, rshen91 commented on src/components/icons/assets/dot.tsx
> +        aria-labelledby={color}
🙌  thank you - a5096c1

2021-01-13 16:21 UTC, markov00 approved these changes
Good to merge as soon as it is green

2021-01-13 16:45 UTC, merged

2021-01-30 15:42 UTC, markov00 commented
:tada: This PR is included in version 24.5.0 :tada:

The release is available on:
- [GitHub release](https://github.com/elastic/elastic-charts/releases/tag/v24.5.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@elastic/charts/v/24.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: